//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKFilter.h"

@interface _TuSDKGPUFaceFilter : TuSDKFilter
{
    int eyePowerUniform;
    int chinPowerUniform;
    int leftEyeCoordinateUniform;
    int rightEyeCoordinateUniform;
    int mouthCoordinateUniform;
    double _eyeEnlargeSize;
    double _chinSize;
}

@property(nonatomic) double chinSize; // @synthesize chinSize=_chinSize;
@property(nonatomic) double eyeEnlargeSize; // @synthesize eyeEnlargeSize=_eyeEnlargeSize;
- (void)resetPosition;
- (void)setLeftEyePosition:(struct CGPoint)arg1 rightEye:(struct CGPoint)arg2 mouth:(struct CGPoint)arg3;
- (id)init;

@end

