//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKFilter.h"

@class TuSDKNKImageColorArgument;

@interface _TuSDKNKImageAutoColorAnalysisFiler : TuSDKFilter
{
    int maxRGBAUniform;
    int minRGBAUniform;
    int midRGBUniform;
    TuSDKNKImageColorArgument *_args;
}

@property(retain, nonatomic) TuSDKNKImageColorArgument *args; // @synthesize args=_args;
- (void).cxx_destruct;
- (void)setMidR:(float)arg1 G:(float)arg2 B:(float)arg3;
- (void)setMinR:(float)arg1 G:(float)arg2 B:(float)arg3 A:(float)arg4;
- (void)setMaxR:(float)arg1 G:(float)arg2 B:(float)arg3 A:(float)arg4;
- (id)init;

@end

