//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKThreeInputFilter.h"

@interface _TuSDKGPULightHolyFilter : TuSDKThreeInputFilter
{
    int intensityUniform;
    int contrastUniform;
    int mixUniform;
    double _intensity;
    double _mix;
    double _contrast;
}

@property(nonatomic) double contrast; // @synthesize contrast=_contrast;
@property(nonatomic) double mix; // @synthesize mix=_mix;
@property(nonatomic) double intensity; // @synthesize intensity=_intensity;
- (id)init;

@end

