//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKGPUImageFilter.h"

@interface _TuSDKGPUFaceBeautyFilter : TuSDKGPUImageFilter
{
    int eyePowerUniform;
    int chinPowerUniform;
    int screenRatioUniform;
    int faceInfoUniform;
    double _eyeEnlargeSize;
    double _chinSize;
    double _screenRatio;
}

@property(nonatomic) double screenRatio; // @synthesize screenRatio=_screenRatio;
@property(nonatomic) double chinSize; // @synthesize chinSize=_chinSize;
@property(nonatomic) double eyeEnlargeSize; // @synthesize eyeEnlargeSize=_eyeEnlargeSize;
- (void)resetPosition;
- (struct CGPoint)getReferPoint:(id)arg1 fromPoint:(id)arg2;
- (void)setFaceFeatures:(id)arg1;
- (void)updateFaceFeatures:(id)arg1 angle:(float)arg2;
- (struct CGRect)circleCalc:(struct CGPoint)arg1 point2:(struct CGPoint)arg2 point3:(struct CGPoint)arg3 ratio:(float)arg4;
- (void)setInputSize:(struct CGSize)arg1 atIndex:(long long)arg2;
- (id)init;

@end

