//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSManagedObjectContext, NSManagedObjectModel, NSPersistentStoreCoordinator;

@interface AFRCDManager : NSObject
{
    NSManagedObjectContext *_managedObjectContext;
    NSManagedObjectModel *_managedObjectModel;
    NSPersistentStoreCoordinator *_persistentStoreCoordinator;
    unsigned long long _maxPersonID;
}

@property(nonatomic) unsigned long long maxPersonID; // @synthesize maxPersonID=_maxPersonID;
- (void).cxx_destruct;
- (void)saveContext:(id)arg1;
@property(readonly, nonatomic) NSManagedObjectContext *managedObjectContext; // @synthesize managedObjectContext=_managedObjectContext;
@property(readonly, nonatomic) NSPersistentStoreCoordinator *persistentStoreCoordinator; // @synthesize persistentStoreCoordinator=_persistentStoreCoordinator;
@property(readonly, nonatomic) NSManagedObjectModel *managedObjectModel; // @synthesize managedObjectModel=_managedObjectModel;
- (id)applicationDocumentsDirectory;
- (_Bool)updatePersonFeatureData:(id)arg1;
- (_Bool)addPerson:(id)arg1;
- (id)allPersons;
- (unsigned long long)getFrModeVersion;
- (void)setFrModelVersion:(unsigned long long)arg1;
- (void)reset;
- (id)init;

@end

