//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSData, NSString;

@interface AFRCDPerson : NSManagedObject
{
}

+ (id)fetchRequest;

// Remaining properties
@property(retain, nonatomic) NSData *faceFeatureData; // @dynamic faceFeatureData;
@property(nonatomic) int faceID; // @dynamic faceID;
@property(retain, nonatomic) NSData *faceThumb; // @dynamic faceThumb;
@property(nonatomic) int faceThumbHeight; // @dynamic faceThumbHeight;
@property(nonatomic) int faceThumbWidth; // @dynamic faceThumbWidth;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(nonatomic) int personID; // @dynamic personID;

@end

