//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AFRManager, AFRPerson;
@protocol AFVideoProcessorDelegate, OS_dispatch_semaphore;

@interface AFVideoProcessor : NSObject
{
    void *_arcsoftFD;
    void *_memBufferFD;
    void *_arcsoftFT;
    void *_memBufferFT;
    void *_arcsoftFR;
    void *_memBufferFR;
    void *_arcsoftAge;
    void *_memBufferAge;
    void *_arcsoftGender;
    void *_memBufferGender;
    struct __tag_ASVL_OFFSCREEN *_offscreenForProcessFR;
    NSObject<OS_dispatch_semaphore> *_processSemaphore;
    NSObject<OS_dispatch_semaphore> *_processFRSemaphore;
    _Bool _detectFaceUseFD;
    _Bool _frModelVersionChecked;
    id <AFVideoProcessorDelegate> _delegate;
    AFRManager *_frManager;
    AFRPerson *_frPerson;
}

@property(retain) AFRPerson *frPerson; // @synthesize frPerson=_frPerson;
@property(retain, nonatomic) AFRManager *frManager; // @synthesize frManager=_frManager;
@property(nonatomic) _Bool frModelVersionChecked; // @synthesize frModelVersionChecked=_frModelVersionChecked;
@property(nonatomic) __weak id <AFVideoProcessorDelegate> delegate; // @synthesize delegate=_delegate;
@property _Bool detectFaceUseFD; // @synthesize detectFaceUseFD=_detectFaceUseFD;
- (void).cxx_destruct;
- (struct __tag_ASVL_OFFSCREEN *)copyOffscreenForProcessFR:(struct __tag_ASVL_OFFSCREEN *)arg1;
- (_Bool)registerDetectedPerson:(id)arg1;
- (id)process:(struct __tag_ASVL_OFFSCREEN *)arg1;
- (void)uninitProcessor;
- (void)initProcessor;

@end

