//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AssetsLibrary/ALAssetsLibrary.h>

@interface ALAssetsLibrary (CustomPhotoAlbum)
+ (_Bool)lsqSaveVideo:(id)arg1 toAblum:(id)arg2 completionBlock:(CDUnknownBlockType)arg3 ablumCompletionBlock:(CDUnknownBlockType)arg4;
+ (_Bool)lsqSaveImage:(id)arg1 metadata:(id)arg2 toAblum:(id)arg3 completionBlock:(CDUnknownBlockType)arg4 ablumCompletionBlock:(CDUnknownBlockType)arg5;
+ (_Bool)lsqSaveImageData:(id)arg1 metadata:(id)arg2 toAblum:(id)arg3 completionBlock:(CDUnknownBlockType)arg4 ablumCompletionBlock:(CDUnknownBlockType)arg5;
+ (_Bool)lsqSaveImageData:(id)arg1 toAblum:(id)arg2 completionBlock:(CDUnknownBlockType)arg3 ablumCompletionBlock:(CDUnknownBlockType)arg4;
+ (_Bool)lsqSaveImageData:(id)arg1 toAblum:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
+ (_Bool)lsqSaveImageData:(id)arg1 metadata:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
+ (_Bool)lsqSaveImageData:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)lsqAddALAsset:(id)arg1 toAblum:(id)arg2 ablumCompletionBlock:(CDUnknownBlockType)arg3;
- (void)lsqImageSavedWithAblum:(id)arg1 assetURL:(id)arg2 error:(id)arg3 completionBlock:(CDUnknownBlockType)arg4 ablumCompletionBlock:(CDUnknownBlockType)arg5;
@end

