//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableData, NSString;

@interface AsyncReceivePacket : NSObject
{
    double timeout;
    long long tag;
    NSMutableData *buffer;
    NSString *host;
    unsigned short port;
}

- (void)dealloc;
- (id)initWithTimeout:(double)arg1 tag:(long long)arg2;

@end

