//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AVFoundation/AVCaptureDevice.h>

@interface AVCaptureDevice (TuSDKTSAVCaptureDeviceExtend)
+ (struct CGPoint)lsqConvertPoint:(struct CGPoint)arg1 withPosition:(long long)arg2 outputImageOrientation:(long long)arg3;
+ (id)lsqGetCameraWithType:(long long)arg1;
+ (id)lsqGetBackOrFrontCamera;
+ (long long)lsqFirstFrontCameraPosition;
+ (long long)lsqFirstBackCameraPosition;
+ (_Bool)lsqShowAlertIfNotSupportCameraWithController:(id)arg1;
+ (int)lsqCameraCounts;
+ (_Bool)lsqHasVideoAuthor;
@end

