//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSDate;

@interface BlockModel : NSObject <NSCopying>
{
    NSDate *_addStamp;
    CDUnknownBlockType _block;
}

@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(retain, nonatomic) NSDate *addStamp; // @synthesize addStamp=_addStamp;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

