//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DDBaseListenConnectionViewController.h"

@class UILabel;

@interface DDAboutDroneViewController : DDBaseListenConnectionViewController
{
    UILabel *_nameLabel;
    UILabel *_freeSpaceLabel;
    UILabel *_versionFirmwareLabel;
    UILabel *_versionOFLabel;
    UILabel *_versionCameraLabel;
    UILabel *_snLabel;
    UILabel *_nameInfoLabel;
    UILabel *_freeSpaceInfoLabel;
    UILabel *_versionFirmwareInfoLabel;
    UILabel *_versionOFInfoLabel;
    UILabel *_versionCameraInfoLabel;
    UILabel *_snInfoLabel;
}

@property(retain, nonatomic) UILabel *snInfoLabel; // @synthesize snInfoLabel=_snInfoLabel;
@property(retain, nonatomic) UILabel *versionCameraInfoLabel; // @synthesize versionCameraInfoLabel=_versionCameraInfoLabel;
@property(retain, nonatomic) UILabel *versionOFInfoLabel; // @synthesize versionOFInfoLabel=_versionOFInfoLabel;
@property(retain, nonatomic) UILabel *versionFirmwareInfoLabel; // @synthesize versionFirmwareInfoLabel=_versionFirmwareInfoLabel;
@property(retain, nonatomic) UILabel *freeSpaceInfoLabel; // @synthesize freeSpaceInfoLabel=_freeSpaceInfoLabel;
@property(retain, nonatomic) UILabel *nameInfoLabel; // @synthesize nameInfoLabel=_nameInfoLabel;
@property(retain, nonatomic) UILabel *snLabel; // @synthesize snLabel=_snLabel;
@property(retain, nonatomic) UILabel *versionCameraLabel; // @synthesize versionCameraLabel=_versionCameraLabel;
@property(retain, nonatomic) UILabel *versionOFLabel; // @synthesize versionOFLabel=_versionOFLabel;
@property(retain, nonatomic) UILabel *versionFirmwareLabel; // @synthesize versionFirmwareLabel=_versionFirmwareLabel;
@property(retain, nonatomic) UILabel *freeSpaceLabel; // @synthesize freeSpaceLabel=_freeSpaceLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void).cxx_destruct;
- (void)initUI;
- (void)initData;
- (void)showProgress:(_Bool)arg1;
- (void)requestSDFreeSpace;
- (id)spaceValue:(double)arg1;
- (void)updateSDFreeSpace:(double)arg1;
- (void)updateSN:(id)arg1;
- (void)updateVersion:(id)arg1;
- (void)notifyMessage:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

