//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSTimer, UIButton;

@interface DDCameraOperateView : UIView
{
    _Bool _isLandscape;
    _Bool _isStopTimeOut;
    _Bool _isRecording;
    _Bool _buttonEnabled;
    unsigned long long _shotMode;
    CDUnknownBlockType _block;
    UIButton *_switchButton;
    UIButton *_cameraButton;
    NSTimer *_timeoutTimer;
}

@property(retain, nonatomic) NSTimer *timeoutTimer; // @synthesize timeoutTimer=_timeoutTimer;
@property(retain, nonatomic) UIButton *cameraButton; // @synthesize cameraButton=_cameraButton;
@property(retain, nonatomic) UIButton *switchButton; // @synthesize switchButton=_switchButton;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(nonatomic) _Bool buttonEnabled; // @synthesize buttonEnabled=_buttonEnabled;
@property(nonatomic) _Bool isRecording; // @synthesize isRecording=_isRecording;
- (void).cxx_destruct;
- (void)updateView:(unsigned long long)arg1;
@property(nonatomic) unsigned long long shotMode; // @synthesize shotMode=_shotMode;
- (void)stopTimeout;
- (void)timeout;
- (void)startTimeout;
- (void)updateCameraButton:(unsigned long long)arg1;
- (void)cameraButtonClicked;
- (void)updateSwitchButton:(unsigned long long)arg1;
- (void)switchButtonClicked;
- (void)initUI;
- (void)initData:(unsigned long long)arg1;
- (id)initWithShotMode:(unsigned long long)arg1 isLandscape:(_Bool)arg2;

@end

