//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DDControlData : NSObject
{
    float _gaz;
    float _accelero_theta;
    float _accelero_phi;
    float _yaw;
}

@property(nonatomic) float yaw; // @synthesize yaw=_yaw;
@property(nonatomic) float accelero_phi; // @synthesize accelero_phi=_accelero_phi;
@property(nonatomic) float accelero_theta; // @synthesize accelero_theta=_accelero_theta;
@property(nonatomic) float gaz; // @synthesize gaz=_gaz;

@end

