//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView;

@interface DDConnectionHelperView : UIView
{
    CDUnknownBlockType _block;
    UIButton *_closeButton;
    UIImageView *_helpAnimation;
}

@property(retain, nonatomic) UIImageView *helpAnimation; // @synthesize helpAnimation=_helpAnimation;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void).cxx_destruct;
- (void)closeView;
- (void)loadCloseButton;
- (void)initUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

