//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class DDDronePhotosHandler, MWPhotoBrowser, NSString;

@protocol DDDronePhotosHandlerDelegate <NSObject>
- (void)photos:(DDDronePhotosHandler *)arg1 showAlertMessage:(NSString *)arg2;
- (void)photos:(DDDronePhotosHandler *)arg1 showProgress:(_Bool)arg2 message:(NSString *)arg3 progress:(float)arg4;
- (void)photos:(DDDronePhotosHandler *)arg1 numberOfPhotos:(unsigned long long)arg2;
- (void)photos:(DDDronePhotosHandler *)arg1 hiddenNavAndTabbar:(_Bool)arg2;
- (void)photos:(DDDronePhotosHandler *)arg1 willLoad:(_Bool)arg2;
- (void)getPhotos:(DDDronePhotosHandler *)arg1 browser:(MWPhotoBrowser *)arg2;
@end

