//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface DDEventBody : NSObject
{
    NSString *_info;
    unsigned long long _level;
    double _time;
}

@property(nonatomic) double time; // @synthesize time=_time;
@property(nonatomic) unsigned long long level; // @synthesize level=_level;
@property(retain, nonatomic) NSString *info; // @synthesize info=_info;
- (void).cxx_destruct;
- (id)initWithMesage:(unsigned long long)arg1;

@end

