//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DDFaceTrace : NSObject
{
    _Bool _faceTraceEnable;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool faceTraceEnable; // @synthesize faceTraceEnable=_faceTraceEnable;
- (void)faceTrace:(CDStruct_b8308255)arg1;

@end

