//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DDBaseListenConnectionViewController.h"

@class DDButton, DDPopupProgressView, DDUpdateHandler, UILabel;

@interface DDFirmwareUpdateViewController : DDBaseListenConnectionViewController
{
    _Bool _newViesion;
    _Bool _lowBattery;
    DDUpdateHandler *_updateHandler;
    DDButton *_updateButton;
    UILabel *_infoLabel;
    DDPopupProgressView *_progressView;
}

@property(retain, nonatomic) DDPopupProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
@property(retain, nonatomic) DDButton *updateButton; // @synthesize updateButton=_updateButton;
@property(retain, nonatomic) DDUpdateHandler *updateHandler; // @synthesize updateHandler=_updateHandler;
- (void).cxx_destruct;
- (void)hideProgess;
- (void)showProgress;
- (void)updateButtonClick;
- (void)updateView:(_Bool)arg1;
- (void)initUI;
- (void)initData;
- (void)showNoSpaceDialog;
- (void)requestSDFreeSpace;
- (void)notifyMessage:(id)arg1;
- (void)receiveNotify;
- (void)removeNotify;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

