//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DDFlightStatus : NSObject
{
    long long _pacc;
    long long _hacc;
    long long _vacc;
    unsigned long long _ap_mode;
    long long _sta;
    long long _wifi;
    long long _voltage;
    long long _capcity;
}

@property(nonatomic) long long capcity; // @synthesize capcity=_capcity;
@property(nonatomic) long long voltage; // @synthesize voltage=_voltage;
@property(nonatomic) long long wifi; // @synthesize wifi=_wifi;
@property(nonatomic) long long sta; // @synthesize sta=_sta;
@property(nonatomic) unsigned long long ap_mode; // @synthesize ap_mode=_ap_mode;
@property(nonatomic) long long vacc; // @synthesize vacc=_vacc;
@property(nonatomic) long long hacc; // @synthesize hacc=_hacc;
@property(nonatomic) long long pacc; // @synthesize pacc=_pacc;
@property(readonly, nonatomic) _Bool barometerAbnormal;
@property(readonly, nonatomic) _Bool accelerationAbnormal;
@property(readonly, nonatomic) _Bool magnetometerAbnormal;

@end

