//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DDFlightViewController.h"

@class JoystickGravitySelfie, NSObject, UIImageView;
@protocol OS_dispatch_source;

@interface DDFlightPortraitViewController : DDFlightViewController
{
    double _statusBarHeight;
    double _notifyViewHeight;
    double _displayViewHeight;
    double _sliderViewHeight;
    double _controlAreaHeight;
    double _notifyButtonWidth;
    NSObject<OS_dispatch_source> *_timer;
    JoystickGravitySelfie *_joystickGravitySelfie;
    UIImageView *_tutorshipStepView;
}

@property(retain, nonatomic) UIImageView *tutorshipStepView; // @synthesize tutorshipStepView=_tutorshipStepView;
@property(retain, nonatomic) JoystickGravitySelfie *joystickGravitySelfie; // @synthesize joystickGravitySelfie=_joystickGravitySelfie;
- (void).cxx_destruct;
- (void)updateTutorshipStep:(unsigned long long)arg1;
- (void)showStepView;
- (void)startTimer;
- (void)setupTutorshipView;
- (void)setupCountDownView;
- (void)setupCameraSettingsView;
- (void)setupCameraButton;
- (void)setupFlightButton;
- (void)setupRecordIndView;
- (void)setupButtonView;
- (void)setupNotifyView;
- (void)setupSliderView;
- (void)setupStatusBarView;
- (void)setupControlAreaView;
- (void)setupDisplayView;
- (void)setupView;
- (void)initData;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

