//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DDFlightViewController.h"

@class JoystickGravity, JoystickRocker, UIButton;

@interface DDFlightLandscapeViewController : DDFlightViewController
{
    double _controlAreaHeight;
    double _notifyViewWidth;
    double _notifyViewHeight;
    double _sliderBottomOffset;
    JoystickRocker *_joystickRoker;
    JoystickGravity *_joystickGravity;
    UIButton *_switchOperatButton;
}

@property(retain, nonatomic) UIButton *switchOperatButton; // @synthesize switchOperatButton=_switchOperatButton;
@property(retain, nonatomic) JoystickGravity *joystickGravity; // @synthesize joystickGravity=_joystickGravity;
@property(retain, nonatomic) JoystickRocker *joystickRoker; // @synthesize joystickRoker=_joystickRoker;
- (void).cxx_destruct;
- (void)switchOprationMode;
- (void)updateSwitchOperatButton:(unsigned long long)arg1;
- (void)setupCountDownView;
- (void)setupCameraSettingsView;
- (void)setupSDView;
- (void)setupCameraButton;
- (void)setupFlightButton;
- (void)setupCameraSettingsButton;
- (void)setupRecordIndView;
- (void)setupNotifyView;
- (void)setupSliderView;
- (void)setupStatusBarView;
- (void)setupControlAreaView;
- (void)setupDisplayView;
- (void)setupView;
- (void)initData;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)forceLandscape;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;

@end

