//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol DDFlightHandlerDelegate <NSObject>
- (void)updateTutorshipStep:(unsigned long long)arg1;
- (void)warningHint:(NSString *)arg1;
- (void)warningCriticalBattery:(_Bool)arg1;
- (void)waitingExit:(_Bool)arg1;
- (void)warningExitMotorOn;
- (void)updateControlButtonClicked;
- (void)setCameraButtonTimeOut:(_Bool)arg1;
- (void)updateCountDown:(unsigned long long)arg1;
- (void)updateMultShot:(_Bool)arg1;
- (void)updateRecordingTime:(long long)arg1;
- (void)updateSliderStatus:(long long)arg1;
- (void)updateCameraEnabled:(_Bool)arg1;
- (void)updateCameraShotMode:(unsigned long long)arg1 isRecording:(_Bool)arg2;
- (void)updateGoHomeButton:(_Bool)arg1;
- (void)updateDroneDistance:(double)arg1;
- (void)updateDroneHeight:(double)arg1;
- (void)updateSdFreeSpace:(double)arg1;
- (void)updateGpsSignal:(unsigned long long)arg1;
- (void)updateFcSignal:(unsigned long long)arg1;
- (void)updateBatterySignal:(unsigned long long)arg1;
- (void)removeEvent:(unsigned long long)arg1;
- (void)addEvent:(unsigned long long)arg1;
@end

