//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DDBaseListenConnectionViewController.h"

#import "UIScrollViewDelegate-Protocol.h"

@class DDTopTabView, NSArray, NSString, UIScrollView, YQAssetOperator;

@interface DDGalleryMainViewController : DDBaseListenConnectionViewController <UIScrollViewDelegate>
{
    unsigned long long _currentIndex;
    YQAssetOperator *_assetOperator;
    _Bool isInited;
    UIScrollView *_galleryScrollView;
    DDTopTabView *_topView;
    NSArray *_dataList;
}

@property(retain, nonatomic) NSArray *dataList; // @synthesize dataList=_dataList;
@property(retain, nonatomic) DDTopTabView *topView; // @synthesize topView=_topView;
@property(nonatomic) __weak UIScrollView *galleryScrollView; // @synthesize galleryScrollView=_galleryScrollView;
- (void).cxx_destruct;
- (void)loadGallery:(long long)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)setupNavigationView;
- (void)setupChildViewController;
- (void)initUI;
- (void)initData;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

