//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray;

@interface DDGalleryMenu : UIView
{
    CDUnknownBlockType _block;
    NSMutableArray *_buttons;
}

@property(retain, nonatomic) NSMutableArray *buttons; // @synthesize buttons=_buttons;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void).cxx_destruct;
- (void)setButtonTitle:(id)arg1 buttonTag:(unsigned long long)arg2;
- (void)setButtonEnabled:(_Bool)arg1 buttonTag:(unsigned long long)arg2;
- (void)titleClick:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 menuItme:(id)arg2;

@end

