//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DDDevice, DDFlightStatus, NSString;

@interface DDGlobal : NSObject
{
    _Bool _isInited;
    int _flightStateMachine;
    DDDevice *_device;
    DDFlightStatus *_flightStatus;
    NSString *_connectionDroneSSID;
    unsigned long long _tutorshipStep;
}

+ (id)sharedInstance;
@property(nonatomic) unsigned long long tutorshipStep; // @synthesize tutorshipStep=_tutorshipStep;
@property(nonatomic) int flightStateMachine; // @synthesize flightStateMachine=_flightStateMachine;
@property(retain, nonatomic) NSString *connectionDroneSSID; // @synthesize connectionDroneSSID=_connectionDroneSSID;
@property(retain, nonatomic) DDFlightStatus *flightStatus; // @synthesize flightStatus=_flightStatus;
@property(retain, nonatomic) DDDevice *device; // @synthesize device=_device;
@property(nonatomic) _Bool isInited; // @synthesize isInited=_isInited;
- (void).cxx_destruct;

@end

