//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DDBaseListenConnectionViewController.h"

@class DDButton, DDGyroCalibrationHandler, DDPopupProgressView, UILabel;

@interface DDGyroCalibrationViewController : DDBaseListenConnectionViewController
{
    DDGyroCalibrationHandler *_gyroCalibrationHandler;
    DDButton *_calibrationButton;
    UILabel *_infoLabel;
    DDPopupProgressView *_progressView;
}

@property(retain, nonatomic) DDPopupProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
@property(retain, nonatomic) DDButton *calibrationButton; // @synthesize calibrationButton=_calibrationButton;
@property(retain, nonatomic) DDGyroCalibrationHandler *gyroCalibrationHandler; // @synthesize gyroCalibrationHandler=_gyroCalibrationHandler;
- (void).cxx_destruct;
- (void)hideProgess;
- (void)showProgress;
- (void)failedCalibration;
- (void)finishCalibration;
- (void)calibrationButtonClick:(id)arg1;
- (void)initUI;
- (void)initData;
- (void)executeCalibration;
- (void)deviceConnectionStatus:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

