//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DDBaseHandler.h"

@class NSObject;
@protocol OS_dispatch_source;

@interface DDGyroCalibrationHandler : DDBaseHandler
{
    long long mStatus;
    NSObject<OS_dispatch_source> *_timer;
    int _currentFlightStatus;
    CDUnknownBlockType _block;
}

@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void).cxx_destruct;
- (void)setTimeOut;
- (void)finishCalibration;
- (void)calibrationStatus:(id)arg1;
- (void)getCalibrationStatus;
- (void)stopCalibration;
- (void)startGyroCalibration;
- (void)executeCalibration;

@end

