//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MWPhotoBrowserDelegate-Protocol.h"

@class DDMedia, NSMutableArray, NSString, YQAssetOperator;

@interface DDLocalHandler : NSObject <MWPhotoBrowserDelegate>
{
    unsigned long long _selectedCount;
    YQAssetOperator *_assetOperator;
    DDMedia *_medias;
    NSMutableArray *_selections;
}

@property(retain, nonatomic) NSMutableArray *selections; // @synthesize selections=_selections;
@property(retain, nonatomic) DDMedia *medias; // @synthesize medias=_medias;
- (void).cxx_destruct;
- (void)saveFiles:(id)arg1 files:(id)arg2;
- (void)deleteFiles:(id)arg1 files:(id)arg2;
- (void)photoBrowser:(id)arg1 editPhotoAtIndex:(unsigned long long)arg2;
- (void)photoBrowser:(id)arg1 saveFileAtIndex:(unsigned long long)arg2;
- (void)photoBrowser:(id)arg1 deleteFileAtIndex:(unsigned long long)arg2;
- (void)photoBrowser:(id)arg1 hiddenNavAndTabbar:(_Bool)arg2;
- (void)photoBrowserDidDownloadSelections:(id)arg1;
- (void)photoBrowserDidDeleteSelections:(id)arg1;
- (void)photoBrowserDidFinishModalPresentation:(id)arg1;
- (void)photoBrowser:(id)arg1 photoAtIndex:(unsigned long long)arg2 selectedChanged:(_Bool)arg3;
- (void)photoBrowser:(id)arg1 isSelection:(_Bool)arg2;
- (_Bool)photoBrowser:(id)arg1 isPhotoSelectedAtIndex:(unsigned long long)arg2;
- (void)photoBrowser:(id)arg1 didDisplayPhotoAtIndex:(unsigned long long)arg2;
- (id)photoBrowser:(id)arg1 thumbPhotoAtIndex:(unsigned long long)arg2;
- (id)photoBrowser:(id)arg1 photoAtIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfPhotosInPhotoBrowser:(id)arg1;
- (void)editPhoto:(id)arg1;
- (void)showAlertMessage:(id)arg1;
- (void)showProgress:(_Bool)arg1 message:(id)arg2 progress:(float)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

