//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DDBaseListenConnectionViewController.h"

@class DDMagnetometerCalibrationHandler;

@interface DDMagnetometerCalibrationViewController : DDBaseListenConnectionViewController
{
    DDMagnetometerCalibrationHandler *_magnetometerCalibrationHandler;
}

@property(retain, nonatomic) DDMagnetometerCalibrationHandler *magnetometerCalibrationHandler; // @synthesize magnetometerCalibrationHandler=_magnetometerCalibrationHandler;
- (void).cxx_destruct;
- (void)calibrationStatus:(_Bool)arg1 status:(long long)arg2;
- (void)executeCalibration;
- (void)deviceConnectionStatus:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

