//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DDBaseListenConnectionViewController.h"

@class DDConnectionHelperView, DDOperateView, DDPopupProgressView, MPMoviePlayerViewController, UIBarButtonItem, UIImageView;

@interface DDMainConnectionViewController : DDBaseListenConnectionViewController
{
    _Bool isPlayingTutorshipVideo;
    UIBarButtonItem *_leftItem;
    UIImageView *_showDeviceImageView;
    DDOperateView *_operateView;
    DDConnectionHelperView *_helperView;
    MPMoviePlayerViewController *_moviePlayerViewController;
    DDPopupProgressView *_progressView;
}

@property(retain, nonatomic) DDPopupProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) MPMoviePlayerViewController *moviePlayerViewController; // @synthesize moviePlayerViewController=_moviePlayerViewController;
@property(retain, nonatomic) DDConnectionHelperView *helperView; // @synthesize helperView=_helperView;
@property(retain, nonatomic) DDOperateView *operateView; // @synthesize operateView=_operateView;
@property(retain, nonatomic) UIImageView *showDeviceImageView; // @synthesize showDeviceImageView=_showDeviceImageView;
@property(retain, nonatomic) UIBarButtonItem *leftItem; // @synthesize leftItem=_leftItem;
- (void).cxx_destruct;
- (void)notifyInited;
- (void)notifyMessage:(id)arg1;
- (void)receiveNotify;
- (void)removeNotify;
- (void)hideProgess;
- (void)showProgress;
- (void)updateCompleted:(_Bool)arg1;
- (void)showUpdateView;
- (void)entryUpdate;
- (void)skipVideo;
- (void)playbackDidFinish:(id)arg1;
- (void)palyVideoWithURLString:(id)arg1 allowedToControl:(_Bool)arg2;
- (void)entryLandscapeOperationView;
- (void)entryPortraitOperationView;
- (void)gotoFlight;
- (void)connectHelper;
- (void)leftButtonItemClick:(id)arg1;
- (void)showSelectDevice;
- (id)showDeviceView;
- (void)setupOperateView;
- (void)setupShowDeviceView;
- (void)setupNavigationBar;
- (void)initUI;
- (void)deviceConnectionStatus:(_Bool)arg1;
- (void)showView:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

