//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITabBarController.h>

@interface DDMainViewController : UITabBarController
{
}

- (_Bool)hidesBottomBarWhenPushed;
- (void)loadTabBarViewControllers;
- (void)initUI;
- (void)initData;
- (void)forcePortrait;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

