//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UILabel, UITableView;

@interface DDNotifyView : UIView <UITableViewDataSource, UITableViewDelegate>
{
    double _extendHeight;
    NSMutableArray *_messageList;
    UILabel *_messageLabel;
    UITableView *_extendView;
}

@property(retain, nonatomic) UITableView *extendView; // @synthesize extendView=_extendView;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) NSMutableArray *messageList; // @synthesize messageList=_messageList;
@property(nonatomic) double extendHeight; // @synthesize extendHeight=_extendHeight;
- (void).cxx_destruct;
- (id)getEventLevelColor:(unsigned long long)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)removeAllEvent;
- (_Bool)containsEvent:(id)arg1;
- (void)removeEvent:(unsigned long long)arg1;
- (void)addEvent:(unsigned long long)arg1;
- (void)sortMessage;
- (void)updateView;
- (id)getMessageText:(unsigned long long)arg1;
- (void)setupView;
- (void)viewClicked;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

