//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMPopupView.h"

@class NSString, UIActivityIndicatorView, UILabel, UIView;

@interface DDPopupProgressView : MMPopupView
{
    _Bool _isShowing;
    NSString *_message;
    UIView *_backView;
    UIActivityIndicatorView *_indicator;
    UILabel *_infoLable;
}

@property(retain, nonatomic) UILabel *infoLable; // @synthesize infoLable=_infoLable;
@property(retain, nonatomic) UIActivityIndicatorView *indicator; // @synthesize indicator=_indicator;
@property(retain, nonatomic) UIView *backView; // @synthesize backView=_backView;
@property(nonatomic) _Bool isShowing; // @synthesize isShowing=_isShowing;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
- (void).cxx_destruct;
- (void)close;
- (void)showWithBlock:(CDUnknownBlockType)arg1;
- (id)initWithMessage:(id)arg1;

@end

