//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DDBaseViewController.h"

@class DDButton, NSString, UIButton, UILabel, UIWebView;

@interface DDPrivacyPolicyViewController : DDBaseViewController
{
    UIWebView *_policyView;
    UILabel *_titleLabel;
    UILabel *_agreenLabel;
    UIButton *_selectButton;
    DDButton *_nextButton;
    NSString *_dataString;
}

@property(retain, nonatomic) NSString *dataString; // @synthesize dataString=_dataString;
@property(retain, nonatomic) DDButton *nextButton; // @synthesize nextButton=_nextButton;
@property(retain, nonatomic) UIButton *selectButton; // @synthesize selectButton=_selectButton;
@property(retain, nonatomic) UILabel *agreenLabel; // @synthesize agreenLabel=_agreenLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIWebView *policyView; // @synthesize policyView=_policyView;
- (void).cxx_destruct;
- (void)nextButtonClicked;
- (void)selectButtonClicked;
- (void)setupView;
- (void)initData;
- (void)forcePortrait;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

