//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray;

@interface DDTopTabView : UIView
{
    _Bool _operateLock;
    CDUnknownBlockType _block;
    UIView *_lineView;
    NSMutableArray *_buttons;
}

@property(retain, nonatomic) NSMutableArray *buttons; // @synthesize buttons=_buttons;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(nonatomic) _Bool operateLock; // @synthesize operateLock=_operateLock;
- (void).cxx_destruct;
- (void)hideLineView:(_Bool)arg1;
- (void)scrolling:(long long)arg1;
- (void)titleClick:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 titleNames:(id)arg2;

@end

