//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DDBaseHandler.h"

@class NSArray, NSMutableArray, NSString;
@protocol DDTutorshipHandlerDelegate;

@interface DDTutorshipHandler : DDBaseHandler
{
    NSString *_server_path;
    long long _currentType;
    NSString *_currentLanguageFlag;
    _Bool _isUpdatedLocalFile;
    id <DDTutorshipHandlerDelegate> _delegate;
    NSArray *_languageList;
    NSMutableArray *_menuList;
}

@property(retain, nonatomic) NSMutableArray *menuList; // @synthesize menuList=_menuList;
@property(retain, nonatomic) NSArray *languageList; // @synthesize languageList=_languageList;
@property(nonatomic) __weak id <DDTutorshipHandlerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)isFileExistTutorshipSubFolder:(id)arg1 fileName:(id)arg2;
- (_Bool)isFileExist:(id)arg1;
- (void)createTutorshipSubFolder:(id)arg1;
- (id)getTutorshipPath;
- (void)showMessage:(id)arg1;
- (void)showIndeterminateProgress:(_Bool)arg1;
- (void)showProgress:(_Bool)arg1 progress:(float)arg2;
- (void)openFile:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)getManifestFileInfo;
- (void)downloadManifestFile;
- (void)downloadLocalFile;
- (void)downloadFileFromServer;
- (void)parseManifest;
- (void)parseLanguage;
- (void)cancelAllOperations;
- (void)initData:(long long)arg1;

@end

