//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface DDUpdateFileInfo : NSObject
{
    NSString *_cameraFileName;
    NSString *_fcFileName;
    NSString *_ofFileName;
}

@property(retain, nonatomic) NSString *ofFileName; // @synthesize ofFileName=_ofFileName;
@property(retain, nonatomic) NSString *fcFileName; // @synthesize fcFileName=_fcFileName;
@property(retain, nonatomic) NSString *cameraFileName; // @synthesize cameraFileName=_cameraFileName;
- (void).cxx_destruct;

@end

