//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DDBaseHandler.h"

@class FTPManager, NSObject;
@protocol OS_dispatch_source;

@interface DDUpdateHandler : DDBaseHandler
{
    NSObject<OS_dispatch_source> *_timer;
    CDUnknownBlockType _updateBlock;
    FTPManager *_ftpManager;
}

@property(retain, nonatomic) FTPManager *ftpManager; // @synthesize ftpManager=_ftpManager;
@property(copy, nonatomic) CDUnknownBlockType updateBlock; // @synthesize updateBlock=_updateBlock;
- (void).cxx_destruct;
- (void)setTimeOut;
- (void)update;
- (void)executeUpdate;

@end

