//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface DDVersion : NSObject
{
    NSString *_camera;
    NSString *_fc;
    NSString *_of;
}

@property(retain, nonatomic) NSString *of; // @synthesize of=_of;
@property(retain, nonatomic) NSString *fc; // @synthesize fc=_fc;
@property(retain, nonatomic) NSString *camera; // @synthesize camera=_camera;
- (void).cxx_destruct;

@end

