//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GLKit/GLKView.h>

@class CIContext, CIImage;

@interface GLKitView : GLKView
{
    CIImage *displayImage;
    CIContext *_ciContext;
}

+ (id)sharedContext;
+ (Class)layerClass;
@property(retain, nonatomic) CIContext *ciContext; // @synthesize ciContext=_ciContext;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)renderWithCVPixelBuffer:(struct __CVBuffer *)arg1 orientation:(int)arg2 mirror:(_Bool)arg3;
- (void)renderWithTexture:(unsigned int)arg1 width:(unsigned int)arg2 height:(unsigned int)arg3;
- (void)renderWithRGBA32Data:(unsigned int)arg1 height:(unsigned int)arg2 imageData:(char *)arg3 format:(int)arg4;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

