//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "CLLocationManagerDelegate-Protocol.h"

@class CLLocationManager, CMMotionManager, NSString, UIButton, UILabel;

@interface JoystickGravity : UIView <CLLocationManagerDelegate>
{
    UIButton *joystickButton;
    struct CGPoint joystickCurrentPosition;
    CMMotionManager *motionManager;
    double lowPassFilterConstant;
    double highPassFilterConstant;
    float accelero_rotation[3][3];
    _Bool acceleroEnabled;
    _Bool running;
    _Bool screenOrientationRight;
    UIView *_viewLeftContent;
    UIView *_viewLeft;
    UIView *_viewRight;
    UIButton *_buttonRight;
    CLLocationManager *_locationManager;
    UILabel *_labelInfo;
}

@property(nonatomic) __weak UILabel *labelInfo; // @synthesize labelInfo=_labelInfo;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(nonatomic) __weak UIButton *buttonRight; // @synthesize buttonRight=_buttonRight;
@property(nonatomic) __weak UIView *viewRight; // @synthesize viewRight=_viewRight;
@property(nonatomic) __weak UIView *viewLeft; // @synthesize viewLeft=_viewLeft;
@property(nonatomic) __weak UIView *viewLeftContent; // @synthesize viewLeftContent=_viewLeftContent;
- (void).cxx_destruct;
- (void)buttonPress:(id)arg1 forEvent:(id)arg2;
- (void)refreshJoystick;
- (_Bool)joyStickOutsideAt:(struct CGPoint)arg1;
- (void)updateControlData:(double)arg1 theta:(double)arg2;
- (void)motionDataHandler;
- (void)locationManager:(id)arg1 didUpdateHeading:(id)arg2;
- (_Bool)locationManagerShouldDisplayHeadingCalibration:(id)arg1;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)setAcceleroRotationWithPhi:(float)arg1 withTheta:(float)arg2 withPsi:(float)arg3;
- (void)initSendData;
- (void)rightButtonTouchUp:(id)arg1;
- (void)rightButtonTouchDown:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

