//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView;

@interface Joystick : UIView
{
    UIButton *joystickButton;
    struct CGPoint joystickCurrentPosition;
    struct CGPoint joystickInitialPosition;
    _Bool buttonPressed;
    struct CGPoint currentCenter;
    float lastGazValue;
    float _alpha;
    UIImageView *_joystickBackgroundImageView;
    UIImageView *_thumbImageView;
    CDUnknownBlockType _postionLRUpdated;
    CDUnknownBlockType _postionUDUpdated;
}

@property(copy, nonatomic) CDUnknownBlockType postionUDUpdated; // @synthesize postionUDUpdated=_postionUDUpdated;
@property(copy, nonatomic) CDUnknownBlockType postionLRUpdated; // @synthesize postionLRUpdated=_postionLRUpdated;
@property(nonatomic) __weak UIImageView *thumbImageView; // @synthesize thumbImageView=_thumbImageView;
@property(nonatomic) __weak UIImageView *joystickBackgroundImageView; // @synthesize joystickBackgroundImageView=_joystickBackgroundImageView;
- (void).cxx_destruct;
- (void)buttonDrag:(id)arg1 forEvent:(id)arg2;
- (void)buttonRelease:(id)arg1 forEvent:(id)arg2;
- (void)buttonPress:(id)arg1 forEvent:(id)arg2;
- (void)updateUDPostion:(double)arg1;
- (void)updateLRPostion:(double)arg1;
- (void)refreshJoystick;
- (struct CGPoint)updateVelocity:(struct CGPoint)arg1;
- (_Bool)joyStickOutsideAt:(struct CGPoint)arg1;
- (float)controlRadius;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

