//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface JUNFTPGetRequest : NSObject
{
    NSURL *resourceUrl;
    NSString *directoryStr;
    struct __CFReadStream *readStream;
    CDUnknownBlockType _finishedBlock;
    CDUnknownBlockType _failBlock;
    CDUnknownBlockType _progressBlock;
    unsigned long long _bytesTotal;
    unsigned long long _bytesDownloaded;
    struct __CFWriteStream *_fileStream;
}

+ (id)requestWithResource:(id)arg1 toDirectory:(id)arg2 finishedBlock:(CDUnknownBlockType)arg3 failBlock:(CDUnknownBlockType)arg4 progressBlock:(CDUnknownBlockType)arg5;
+ (id)requestWithResource:(id)arg1 toDirectory:(id)arg2;
@property(nonatomic) struct __CFWriteStream *fileStream; // @synthesize fileStream=_fileStream;
@property(nonatomic) unsigned long long bytesDownloaded; // @synthesize bytesDownloaded=_bytesDownloaded;
@property(nonatomic) unsigned long long bytesTotal; // @synthesize bytesTotal=_bytesTotal;
@property(copy, nonatomic) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
@property(copy, nonatomic) CDUnknownBlockType failBlock; // @synthesize failBlock=_failBlock;
@property(copy, nonatomic) CDUnknownBlockType finishedBlock; // @synthesize finishedBlock=_finishedBlock;
- (void).cxx_destruct;
- (void)stop;
- (void)start;
- (id)initWithResource:(id)arg1 toDirectory:(id)arg2 finishedBlock:(CDUnknownBlockType)arg3 failBlock:(CDUnknownBlockType)arg4 progressBlock:(CDUnknownBlockType)arg5;

@end

