//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (TuSDKTSNSDataExtend)
+ (id)lsqDataFromBase64String:(id)arg1;
- (id)lsqBase64encode;
- (id)lsqAes256CBCPKCS7PaddingWithOption:(unsigned int)arg1 password:(id)arg2;
- (id)lsqDecryptAES256CBCPKCS7PaddingWithKey:(id)arg1;
- (id)lsqEncryptAES256CBCPKCS7PaddingWithKey:(id)arg1;
- (unsigned char)lsqGetByteWithPostion:(unsigned long long)arg1;
- (id)lsqMd5;
@end

