//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableDictionary.h>

@class CLLocation;

@interface NSMutableDictionary (TuSDKTSImageMetadataCategory)
- (void)lsqSetImageOrientation:(long long)arg1;
- (void)lsqSetDigitalZoom:(double)arg1;
- (void)lsqSetKeywords:(id)arg1;
- (void)lsqSetDescription:(id)arg1;
- (void)lsqSetMake:(id)arg1 model:(id)arg2 software:(id)arg3;
- (void)lsqSetDateDigitized:(id)arg1;
- (void)lsqSetDateOriginal:(id)arg1;
- (void)lsqSetUserComment:(id)arg1;
- (id)lsqDictionaryForKey:(struct __CFString *)arg1;
@property(nonatomic) double trueHeading;
@property(retain, nonatomic) CLLocation *location; // @dynamic location;
- (void)lsqSetHeading:(id)arg1;
- (id)initFromAssetURL:(id)arg1;
- (id)initWithInfoFromImagePicker:(id)arg1;
- (id)initWithImageSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (id)lsqGetUTCFormattedDate:(id)arg1;
@end

