//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (TuSDKTSStringExtend)
+ (id)lsqStringFromOSType:(unsigned int)arg1;
+ (id)lsqStringForByte:(unsigned long long)arg1;
+ (id)lsqUUID;
+ (unsigned char)lsqIsEmptyOrNull:(id)arg1;
+ (id)lsqLocalizedString:(id)arg1;
+ (id)lsqBase64encode:(id)arg1;
- (struct CGSize)lsqColculateTextSizeWithAttributs:(id)arg1 maxWidth:(double)arg2 maxHeihgt:(double)arg3;
- (struct CGSize)lsqColculateTextSizeWithFont:(id)arg1 maxWidth:(double)arg2 maxHeihgt:(double)arg3;
- (unsigned long long)lsqUnsignedIntegerValue;
- (unsigned long long)lsqUnsignedLongLongValue;
- (unsigned int)lsqDigitValue:(unsigned short)arg1;
- (id)lsqToJson;
- (unsigned long long)lsqHexToDecimal;
- (id)lsqHexString;
- (id)lsqReverse;
- (id)lsqSubstringByRegular:(id)arg1;
- (id)lsqTrim;
- (id)lsqSubstringLinefeed:(unsigned long long)arg1;
- (id)lsqMd5;
- (id)lsqUnescapeHTML;
- (id)lsqEscapeHTML;
- (id)lsqEncodeAsURIComponent;
- (id)lsqBase64encode;
@end

