//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "ReaderContentViewDelegate-Protocol.h"
#import "ReaderMainPagebarDelegate-Protocol.h"
#import "ReaderMainToolbarDelegate-Protocol.h"
#import "ThumbsViewControllerDelegate-Protocol.h"
#import "UIDocumentInteractionControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSDate, NSMutableDictionary, NSString, ReaderDocument, ReaderMainPagebar, ReaderMainToolbar, UIDocumentInteractionController, UIPrintInteractionController, UIScrollView;
@protocol ReaderViewControllerDelegate;

@interface ReaderViewController : UIViewController <UIScrollViewDelegate, UIGestureRecognizerDelegate, MFMailComposeViewControllerDelegate, UIDocumentInteractionControllerDelegate, ReaderMainToolbarDelegate, ReaderMainPagebarDelegate, ReaderContentViewDelegate, ThumbsViewControllerDelegate>
{
    ReaderDocument *document;
    UIScrollView *theScrollView;
    ReaderMainToolbar *mainToolbar;
    ReaderMainPagebar *mainPagebar;
    NSMutableDictionary *contentViews;
    long long userInterfaceIdiom;
    long long currentPage;
    long long minimumPage;
    long long maximumPage;
    UIDocumentInteractionController *documentInteraction;
    UIPrintInteractionController *printInteraction;
    double scrollViewOutset;
    struct CGSize lastAppearSize;
    NSDate *lastHideTime;
    _Bool ignoreDidScroll;
    id <ReaderViewControllerDelegate> delegate;
}

@property(nonatomic) __weak id <ReaderViewControllerDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)applicationWillResign:(id)arg1;
- (void)pagebar:(id)arg1 gotoPage:(long long)arg2;
- (void)dismissThumbsViewController:(id)arg1;
- (void)thumbsViewController:(id)arg1 gotoPage:(long long)arg2;
- (void)documentInteractionControllerDidDismissOpenInMenu:(id)arg1;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;
- (void)tappedInToolbar:(id)arg1 markButton:(id)arg2;
- (void)tappedInToolbar:(id)arg1 emailButton:(id)arg2;
- (void)tappedInToolbar:(id)arg1 printButton:(id)arg2;
- (void)tappedInToolbar:(id)arg1 exportButton:(id)arg2;
- (void)tappedInToolbar:(id)arg1 thumbsButton:(id)arg2;
- (void)tappedInToolbar:(id)arg1 doneButton:(id)arg2;
- (void)contentView:(id)arg1 touchesBegan:(id)arg2;
- (void)handleDoubleTap:(id)arg1;
- (void)handleSingleTap:(id)arg1;
- (void)incrementPageNumber;
- (void)decrementPageNumber;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidUnload;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithReaderDocument:(id)arg1;
- (void)closeDocument;
- (void)showDocument;
- (void)showDocumentPage:(long long)arg1;
- (void)handleScrollViewDidEnd:(id)arg1;
- (void)layoutContentViews:(id)arg1;
- (void)addContentView:(id)arg1 page:(long long)arg2;
- (void)updateContentViews:(id)arg1;
- (void)updateContentSize:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

