//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "CLLocationManagerDelegate-Protocol.h"

@class CLLocationManager, CMMotionManager, NSString, UIButton, UIImageView, UILabel;

@interface SelfieControl : UIView <CLLocationManagerDelegate>
{
    UIButton *joystickButton;
    struct CGPoint joystickCurrentPosition;
    struct CGPoint joystickInitialPosition;
    _Bool buttonPressed;
    struct CGPoint currentCenter;
    float lastGazValue;
    float _alpha;
    CMMotionManager *motionManager;
    double lowPassFilterConstant;
    double highPassFilterConstant;
    float accelero_rotation[3][3];
    _Bool acceleroEnabled;
    _Bool running;
    _Bool screenOrientationRight;
    UIImageView *_joystickBackgroundImageView;
    UIImageView *_thumbImageView;
    UILabel *_flightHint;
    CDUnknownBlockType _postionLRUpdated;
    CDUnknownBlockType _postionUDUpdated;
    CLLocationManager *_locationManager;
}

@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(copy, nonatomic) CDUnknownBlockType postionUDUpdated; // @synthesize postionUDUpdated=_postionUDUpdated;
@property(copy, nonatomic) CDUnknownBlockType postionLRUpdated; // @synthesize postionLRUpdated=_postionLRUpdated;
@property(nonatomic) __weak UILabel *flightHint; // @synthesize flightHint=_flightHint;
@property(nonatomic) __weak UIImageView *thumbImageView; // @synthesize thumbImageView=_thumbImageView;
@property(nonatomic) __weak UIImageView *joystickBackgroundImageView; // @synthesize joystickBackgroundImageView=_joystickBackgroundImageView;
- (void).cxx_destruct;
- (void)updateControlData:(double)arg1 theta:(double)arg2;
- (void)motionDataHandler;
- (void)locationManager:(id)arg1 didUpdateHeading:(id)arg2;
- (_Bool)locationManagerShouldDisplayHeadingCalibration:(id)arg1;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)setAcceleroRotationWithPhi:(float)arg1 withTheta:(float)arg2 withPsi:(float)arg3;
- (void)initSendData;
- (void)setAccelerometer:(_Bool)arg1;
- (void)awakeFromNib;
- (void)dealloc;
- (void)buttonDrag:(id)arg1 forEvent:(id)arg2;
- (void)buttonRelease:(id)arg1 forEvent:(id)arg2;
- (void)buttonPress:(id)arg1 forEvent:(id)arg2;
- (void)updateUDPostion:(double)arg1;
- (void)updateLRPostion:(double)arg1;
- (void)refreshJoystick;
- (struct CGPoint)updateVelocity:(struct CGPoint)arg1;
- (_Bool)joyStickOutsideAt:(struct CGPoint)arg1;
- (float)controlRadius;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

