//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface StatisticData : NSObject
{
    unsigned long long _type;
    unsigned long long _idt;
    unsigned long long _time;
    double _longitude;
    double _latitude;
}

+ (id)initWithType:(unsigned long long)arg1 idt:(unsigned long long)arg2;
@property(nonatomic) double latitude; // @synthesize latitude=_latitude;
@property(nonatomic) double longitude; // @synthesize longitude=_longitude;
@property(nonatomic) unsigned long long time; // @synthesize time=_time;
@property(nonatomic) unsigned long long idt; // @synthesize idt=_idt;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (id)getData;

@end

