//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GCDAsyncSocketDelegate-Protocol.h"

@class GCDAsyncSocket, NSMutableArray, NSMutableData, NSString;

@interface TcpManager : NSObject <GCDAsyncSocketDelegate>
{
    GCDAsyncSocket *asyncTcp;
    NSMutableArray *blockArr;
    NSMutableData *_mData;
    long long _resendCount;
    long long _timeOut;
    id _delegate;
}

+ (id)sharedInstance;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)cleanStr:(id)arg1;
- (void)sendData:(id)arg1 Response:(CDUnknownBlockType)arg2 Tag:(int)arg3;
- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)socket:(id)arg1 didConnectToHost:(id)arg2 port:(unsigned short)arg3;
- (void)socket:(id)arg1 didWriteDataWithTag:(long long)arg2;
- (void)socket:(id)arg1 didReadData:(id)arg2 withTag:(long long)arg3;
- (void)disConnectTcp;
- (void)reConnect;
- (void)tcpConnect;
- (_Bool)tcpConnected;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

