//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKPFEditCuterControllerBase.h"

@class TuSDKPFEditCuterView;
@protocol TuSDKPFEditCuterControllerDelegate;

@interface TuSDKPFEditCuterController : TuSDKPFEditCuterControllerBase
{
    TuSDKPFEditCuterView *_defaultStyleView;
    _Bool _enableTrun;
    _Bool _enableMirror;
    id <TuSDKPFEditCuterControllerDelegate> _delegate;
    Class _viewClazz;
}

@property(nonatomic) _Bool enableMirror; // @synthesize enableMirror=_enableMirror;
@property(nonatomic) _Bool enableTrun; // @synthesize enableTrun=_enableTrun;
@property(retain, nonatomic) Class viewClazz; // @synthesize viewClazz=_viewClazz;
@property(nonatomic) __weak id <TuSDKPFEditCuterControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) TuSDKPFEditCuterView *defaultStyleView; // @synthesize defaultStyleView=_defaultStyleView;
- (void).cxx_destruct;
- (void)onImageRatioAction:(id)arg1;
- (void)onImageMirrorAction;
- (void)onImageTurnAction;
- (void)configDefaultStyleView:(id)arg1;
- (void)buildDefaultStyleView;
- (void)viewDidLoad;
- (void)loadView;
- (_Bool)prefersStatusBarHidden;
- (id)imageView;
- (_Bool)asyncNotifyProcessingWithResult:(id)arg1;
- (void)notifyProcessingWithResult:(id)arg1;

@end

