//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TuSDKPFStickerItemViewDelegate-Protocol.h"

@class NSMutableArray, NSString;
@protocol TuSDKPFStickerViewDelegate;

@interface TuSDKPFStickerView : UIView <TuSDKPFStickerItemViewDelegate>
{
    NSMutableArray *_stickers;
    id <TuSDKPFStickerViewDelegate> _delegate;
    Class _stickerItemViewClazz;
}

@property(retain, nonatomic) Class stickerItemViewClazz; // @synthesize stickerItemViewClazz=_stickerItemViewClazz;
@property(nonatomic) __weak id <TuSDKPFStickerViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onSelectedStickerItemView:(id)arg1;
- (void)onClosedStickerItemView:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)cancelAllSelected;
- (id)resultsWithRegionRect:(struct CGRect)arg1;
- (id)buildStickerView:(id)arg1;
- (void)loadedsticker:(id)arg1;
- (void)appendStickerImage:(id)arg1;
- (void)appenSticker:(id)arg1;
- (_Bool)canAppendSticker:(id)arg1;
@property(readonly, nonatomic) unsigned long long stickerCount;
- (void)lsqInitView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

