//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPFocusTouchViewBase.h"

#import "TuSDKVideoCameraExtendViewInterface-Protocol.h"

@class NSString, TuSDKPFFilterConfigView, UIView;
@protocol TuSDKICFocusRangeViewProtocol, TuSDKVideoCameraInterface;

@interface TuSDKCPFocusTouchView : TuSDKCPFocusTouchViewBase <TuSDKVideoCameraExtendViewInterface>
{
    UIView<TuSDKICFocusRangeViewProtocol> *_rangeView;
    TuSDKPFFilterConfigView *_filterConfigView;
    _Bool _displayGuideLine;
    long long _topSpace;
}

@property(nonatomic) _Bool displayGuideLine; // @synthesize displayGuideLine=_displayGuideLine;
@property(nonatomic) long long topSpace; // @synthesize topSpace=_topSpace;
- (void).cxx_destruct;
- (id)buildFaceDetectionView;
- (void)notifyFilterConfigView:(id)arg1;
- (void)notifyRangeViewWithPoint:(struct CGPoint)arg1;
- (_Bool)onFocusWithPoint:(struct CGPoint)arg1;
- (void)setFrame:(struct CGRect)arg1;
@property(readonly, nonatomic) TuSDKPFFilterConfigView *filterConfigView; // @synthesize filterConfigView=_filterConfigView;
- (void)setFilterConfigView:(id)arg1;
@property(readonly, nonatomic) UIView<TuSDKICFocusRangeViewProtocol> *rangeView; // @synthesize rangeView=_rangeView;
- (void)setRangeView:(id)arg1;
- (void)lsqInitView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic) double autoFoucsDelay;
@property(nonatomic) id <TuSDKVideoCameraInterface> camera;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) _Bool disableContinueFoucs;
@property(nonatomic) _Bool disableTapFocus;
@property(nonatomic) _Bool enableLongTouchCapture;
@property(readonly) unsigned long long hash;
@property(nonatomic) double longTouchDelay;
@property(nonatomic) struct CGRect regionPercent;
@property(readonly) Class superclass;

@end

