//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPImage.h"

#import "TuSDKCPAnimationImage-Protocol.h"

@class NSArray, NSString, TuSDKCPGifDecoder;

@interface TuSDKCPGifImage : TuSDKCPImage <TuSDKCPAnimationImage>
{
    TuSDKCPGifDecoder *_decoder;
    _Bool _preloadAllFrame;
    unsigned long long _bytesPerFrame;
    NSArray *_preloadedFrames;
    int _preloadedLock;
    unsigned long long _currentFrameIndex;
}

+ (id)imageWithData:(id)arg1;
+ (id)imageWithContentsOfFile:(id)arg1;
+ (id)imageNamed:(id)arg1;
@property(readonly, nonatomic) unsigned long long currentFrameIndex; // @synthesize currentFrameIndex=_currentFrameIndex;
- (void).cxx_destruct;
- (double)duration;
- (double)durationAtIndex:(unsigned long long)arg1;
- (id)imageFrameAtIndex:(unsigned long long)arg1;
- (unsigned long long)loopCount;
@property(readonly, nonatomic) unsigned long long frameCount;
- (id)initWithData:(id)arg1 scale:(double)arg2;
- (id)initWithData:(id)arg1;
- (id)initWithContentsOfFile:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

