//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIImageView;

@interface TuSDKTKFilterImageWare : NSObject
{
    UIImageView *_imageView;
    NSString *_filterName;
}

+ (id)initWithImageView:(id)arg1 filterName:(id)arg2;
@property(copy, nonatomic) NSString *filterName; // @synthesize filterName=_filterName;
@property(nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (_Bool)setImageResult:(id)arg1;
- (_Bool)isEqualView:(id)arg1;

@end

