//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPResultViewController.h"

@class NSString, UIButton, UIImage;
@protocol TuSDKTSAssetInterface;

@interface TuSDKCPImageResultController : TuSDKCPResultViewController
{
    _Bool _downloading;
    _Bool _downloadedFromServer;
    UIButton *_preview;
    _Bool _showResultPreview;
    _Bool _isAutoRemoveTemp;
    NSString *_inputTempFilePath;
    id <TuSDKTSAssetInterface> _inputAsset;
    UIImage *_inputImage;
}

@property(nonatomic) _Bool isAutoRemoveTemp; // @synthesize isAutoRemoveTemp=_isAutoRemoveTemp;
@property(nonatomic) _Bool showResultPreview; // @synthesize showResultPreview=_showResultPreview;
@property(retain, nonatomic) UIImage *inputImage; // @synthesize inputImage=_inputImage;
@property(retain, nonatomic) id <TuSDKTSAssetInterface> inputAsset; // @synthesize inputAsset=_inputAsset;
@property(copy, nonatomic) NSString *inputTempFilePath; // @synthesize inputTempFilePath=_inputTempFilePath;
- (void).cxx_destruct;
- (void)showPreviewWithState:(_Bool)arg1;
- (void)onPreviewClose;
@property(readonly, nonatomic) UIButton *preview;
- (_Bool)showResultPreview:(id)arg1;
- (void)postProcessWithImage:(id)arg1;
- (_Bool)preProcessWithImage:(id)arg1;
- (void)loadedInputImage:(id)arg1;
- (void)imageWillDisplay:(id)arg1;
- (void)updateImageWithDownloadedData:(id)arg1;
- (_Bool)checkImageValid:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)onAsyncImageLoaded:(id)arg1;
- (void)asyncLoadInputImageWithBlock:(CDUnknownBlockType)arg1;
- (id)cuterImage:(id)arg1 cutRect:(struct CGRect)arg2 imageOrientation:(long long)arg3 cutRatio:(double)arg4;
- (id)cuterImage:(id)arg1 cutRect:(struct CGRect)arg2 imageOrientation:(long long)arg3;
- (id)loadOrginImage;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)controllerWillDestory;

@end

