//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TuSDKCPStackFilterTableViewInterface-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSString, TuSDKFilterOption, TuSDKICTableView;
@protocol TuSDKCPGroupFilterGroupCellDelegate, TuSDKCPStackFilterTableViewDelegate, TuSDKTKFiltersTaskInterface;

@interface TuSDKCPStackFilterTableView : UIView <UITableViewDataSource, UITableViewDelegate, TuSDKCPStackFilterTableViewInterface>
{
    double _mainRotat;
    NSArray *_cellItemDatas;
    _Bool _displaySelectionIcon;
    double _cellWidth;
    double _stackViewWidth;
    long long _action;
    Class _cellViewClazz;
    Class _stackViewClazz;
    id <TuSDKCPStackFilterTableViewDelegate> _delegate;
    long long _selectedSection;
    NSArray *_modeList;
    TuSDKFilterOption *_lasOpt;
    TuSDKICTableView *_tableView;
    id <TuSDKCPGroupFilterGroupCellDelegate> _groupDelegate;
    id <TuSDKTKFiltersTaskInterface> _filterTask;
}

@property(nonatomic) id <TuSDKTKFiltersTaskInterface> filterTask; // @synthesize filterTask=_filterTask;
@property(nonatomic) __weak id <TuSDKCPGroupFilterGroupCellDelegate> groupDelegate; // @synthesize groupDelegate=_groupDelegate;
@property(nonatomic) _Bool displaySelectionIcon; // @synthesize displaySelectionIcon=_displaySelectionIcon;
@property(readonly, nonatomic) TuSDKICTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSArray *cellItemDatas; // @synthesize cellItemDatas=_cellItemDatas;
@property(retain, nonatomic) TuSDKFilterOption *lasOpt; // @synthesize lasOpt=_lasOpt;
@property(retain, nonatomic) NSArray *modeList; // @synthesize modeList=_modeList;
@property(nonatomic) long long selectedSection; // @synthesize selectedSection=_selectedSection;
@property(nonatomic) __weak id <TuSDKCPStackFilterTableViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) Class stackViewClazz; // @synthesize stackViewClazz=_stackViewClazz;
@property(retain, nonatomic) Class cellViewClazz; // @synthesize cellViewClazz=_cellViewClazz;
@property(nonatomic) long long action; // @synthesize action=_action;
- (void).cxx_destruct;
- (void)scrollToRowAtIndexPath:(id)arg1 atScrollPosition:(long long)arg2 animated:(_Bool)arg3;
- (void)deleteRowsAtIndexPaths:(id)arg1 withRowAnimation:(long long)arg2;
- (void)insertRowsAtIndexPaths:(id)arg1 withRowAnimation:(long long)arg2;
- (id)indexPathForSelectedRow;
- (void)reloadData;
- (void)changeSelectPostion:(unsigned long long)arg1 scrollToCenter:(_Bool)arg2 anim:(_Bool)arg3;
- (void)selectPostion:(unsigned long long)arg1 scrollToCenter:(_Bool)arg2 reload:(_Bool)arg3;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)loadHistoryFilters;
- (id)optionsWithGroup:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (_Bool)onCellWillSelectRowAtIndexPath:(id)arg1;
@property(nonatomic) _Bool allowsSelection;
@property(nonatomic) double stackViewWidth; // @synthesize stackViewWidth=_stackViewWidth;
@property(nonatomic) double cellWidth; // @synthesize cellWidth=_cellWidth;
- (id)lsqSetSizeHeight:(double)arg1;
- (void)lsqInitView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

