//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKICSmudgeImageViewWrap.h"

@class TuSDKFilterWrap;

@interface TuSDKICFilterSmudgeImageViewWrap : TuSDKICSmudgeImageViewWrap
{
    TuSDKFilterWrap *_filterWrap;
}

@property(retain, nonatomic) TuSDKFilterWrap *filterWrap; // @synthesize filterWrap=_filterWrap;
- (void).cxx_destruct;
- (double)getMaxTemplateDistance:(double)arg1;
- (void)setImage:(id)arg1;
- (id)getSmudgeProcessor;

@end

