//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TuSDKICSmudgeImageViewInterface-Protocol.h"

@class NSString, TuSDKPFBrush, TuSDKPFSimpleProcessor, UIImage, UIImageView;
@protocol TuSDKICSmudgeImageViewDelegate;

@interface TuSDKICSmudgeImageViewWrap : UIView <TuSDKICSmudgeImageViewInterface>
{
    long long _mBrushSize;
    double _mBrushCustomSize;
    double _mBrushAlpha;
    TuSDKPFBrush *_mBrush;
    unsigned long long _mMaxUndoCount;
    TuSDKPFSimpleProcessor *_smudgeProcessor;
    UIImage *_originalImage;
    UIImageView *_smudgeImageView;
    UIImageView *_backgroundImageView;
    id <TuSDKICSmudgeImageViewDelegate> _delegate;
}

@property(nonatomic) __weak id <TuSDKICSmudgeImageViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)destroyHistory;
- (void)destroy;
- (void)notifySmudgeActionChange;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)updateBrushSettings;
- (id)getSmudgeProcessor;
- (void)prepareForSmudge;
- (id)getOriginalImage;
- (id)getSmudgeImage;
- (id)mergeImage:(id)arg1 withMask:(id)arg2;
- (id)getCanvasImage:(id)arg1;
- (void)needUpdateLayout;
- (void)showOriginal:(_Bool)arg1;
- (unsigned long long)getUndoCount;
- (unsigned long long)getRedoCount;
- (void)redo;
- (void)undo;
- (double)getBrushSizeValue:(long long)arg1;
- (void)setMaxUndoCount:(unsigned long long)arg1;
- (void)setBrushCustomSize:(double)arg1;
- (void)setBrushSize:(long long)arg1;
- (void)setBrush:(id)arg1;
- (struct CGRect)getPreferImageRect:(struct CGSize)arg1 maxSize:(struct CGSize)arg2;
- (void)setImage:(id)arg1;
- (void)lsqInitView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

