//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPGroupFilterBarBase.h"

#import "TuSDKCPFilterOnlineControllerDelegate-Protocol.h"
#import "TuSDKCPGroupFilterBarInterface-Protocol.h"
#import "TuSDKCPGroupFilterGroupCellDelegate-Protocol.h"
#import "TuSDKCPGroupFilterTableViewDelegate-Protocol.h"

@class NSArray, NSString, UIButton, UIView, UIViewController;
@protocol TuSDKCPGroupFilterBarDelegate, TuSDKCPGroupFilterTableViewInterface;

@interface TuSDKCPGroupFilterBar : TuSDKCPGroupFilterBarBase <TuSDKCPGroupFilterTableViewDelegate, TuSDKCPGroupFilterGroupCellDelegate, TuSDKCPFilterOnlineControllerDelegate, TuSDKCPGroupFilterBarInterface>
{
    UIView<TuSDKCPGroupFilterTableViewInterface> *_groupTable;
    UIView<TuSDKCPGroupFilterTableViewInterface> *_filterTable;
    UIButton *_backButton;
    Class _groupTableCellClazz;
    Class _filterTableCellClazz;
}

@property(readonly, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
- (void).cxx_destruct;
- (void)onFilterGroupCellRemove:(id)arg1;
- (void)showFilterTableWithCenterX:(double)arg1 showed:(_Bool)arg2;
- (id)lsqSetSizeHeight:(double)arg1;
@property(nonatomic) double cellWidth;
@property(retain, nonatomic) Class filterTableCellClazz; // @synthesize filterTableCellClazz=_filterTableCellClazz;
@property(retain, nonatomic) Class groupTableCellClazz; // @synthesize groupTableCellClazz=_groupTableCellClazz;
- (id)filterTable;
- (id)groupTable;
- (void)lsqInitView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic) long long action;
@property(nonatomic) _Bool allowsSelection;
@property(nonatomic) _Bool autoSelectGroupDefaultFilter;
@property(nonatomic) UIViewController *controller;
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <TuSDKCPGroupFilterBarDelegate> delegate;
@property(readonly, copy) NSString *description;
@property(nonatomic) _Bool enableFilterConfig;
@property(nonatomic) _Bool enableHistory;
@property(nonatomic) _Bool enableNormalFilter;
@property(nonatomic) _Bool enableOnlineFilter;
@property(retain, nonatomic) NSArray *filterGroup;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool isRenderFilterThumb;
@property(retain, nonatomic) Class onlineControllerClazz;
@property(nonatomic) _Bool saveLastFilter;
@property(nonatomic) double stackViewWidth;
@property(readonly) Class superclass;

@end

