//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKNKDownloadAdapter.h"

@class NSArray, NSMutableArray, TuSDKConfig;

@interface TuSDKBrushAdapter : TuSDKNKDownloadAdapter
{
    NSMutableArray *_brushDatas;
    NSMutableArray *_groups;
    TuSDKConfig *_config;
    unsigned long long _total;
    _Bool _isInited;
}

+ (id)initWithConfig:(id)arg1;
@property(readonly, nonatomic) _Bool isInited; // @synthesize isInited=_isInited;
- (void).cxx_destruct;
- (id)allGroupID;
- (_Bool)appenDownloaded:(id)arg1;
- (void)removeDownloadDataWithIdt:(unsigned long long)arg1;
- (_Bool)containsWithGroupId:(unsigned long long)arg1;
- (id)findGroupByID:(unsigned long long)arg1;
- (_Bool)loadBrushData:(id)arg1;
- (id)asyncTaskLoadImageWithWare:(id)arg1;
- (_Bool)loadResImageWithImageView:(id)arg1 resName:(id)arg2;
- (void)loadThumbWithBrush:(id)arg1 imageView:(id)arg2;
- (id)brushWithCodes:(id)arg1;
- (id)verifyCodes:(id)arg1;
- (id)brushWithCode:(id)arg1;
- (id)eraserBrush;
- (void)mergerBrush:(id)arg1 toData:(id)arg2;
- (void)mergerGroup:(id)arg1 toGroup:(id)arg2;
- (void)asyncLoadLocalBrush:(id)arg1;
- (void)asyncLoadLocalBrushes;
- (void)loadBrushes;
@property(readonly, nonatomic) NSArray *codes;
- (id)initWithConfig:(id)arg1;

@end

