//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIImageView;
@protocol TuSDKTSAssetInterface;

@interface TuSDKPFPhotosGrid : UIButton
{
    UIImageView *_thumbView;
    id <TuSDKTSAssetInterface> _data;
}

@property(retain, nonatomic) id <TuSDKTSAssetInterface> data; // @synthesize data=_data;
@property(readonly, nonatomic) UIImageView *thumbView; // @synthesize thumbView=_thumbView;
- (void).cxx_destruct;
- (void)viewNeedRest;
- (id)initWithFrame:(struct CGRect)arg1;

@end

