//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIColor, UIImage;

@interface TuSDKWaterMarkOption : NSObject
{
    long long _markPosition;
    NSString *_markText;
    UIImage *_markImage;
    double _markMargin;
    long long _markTextPosition;
    double _markTextPadding;
    double _markTextSize;
    UIColor *_markTextColor;
    UIColor *_markTextShadowColor;
}

@property(retain, nonatomic) UIColor *markTextShadowColor; // @synthesize markTextShadowColor=_markTextShadowColor;
@property(retain, nonatomic) UIColor *markTextColor; // @synthesize markTextColor=_markTextColor;
@property(nonatomic) double markTextSize; // @synthesize markTextSize=_markTextSize;
@property(nonatomic) double markTextPadding; // @synthesize markTextPadding=_markTextPadding;
@property(nonatomic) long long markTextPosition; // @synthesize markTextPosition=_markTextPosition;
@property(nonatomic) double markMargin; // @synthesize markMargin=_markMargin;
@property(retain, nonatomic) UIImage *markImage; // @synthesize markImage=_markImage;
@property(retain, nonatomic) NSString *markText; // @synthesize markText=_markText;
@property(nonatomic) long long markPosition; // @synthesize markPosition=_markPosition;
- (void).cxx_destruct;
- (_Bool)isValid;
- (id)init;

@end

