//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIScrollView;

@interface TuSDKPFEditCuterOptionBar : UIView
{
    UIScrollView *_wrapView;
    NSArray *_buttons;
    NSArray *_ratioTypeList;
    long long _currentRatioType;
}

@property(nonatomic) long long currentRatioType; // @synthesize currentRatioType=_currentRatioType;
@property(retain, nonatomic) NSArray *ratioTypeList; // @synthesize ratioTypeList=_ratioTypeList;
@property(readonly, nonatomic) NSArray *buttons; // @synthesize buttons=_buttons;
@property(readonly, nonatomic) UIScrollView *wrapView; // @synthesize wrapView=_wrapView;
- (void).cxx_destruct;
- (id)buildButtonWithWidth:(double)arg1 left:(double)arg2 ratioType:(long long)arg3;
- (void)needUpdateLayout;
- (void)lsqInitView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

