//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TuSDKICTouchImageViewDelegate-Protocol.h"

@class NSString, TuSDKPFEditTurnAndCutBottomView, TuSDKPFNormalFilterGroupView;
@protocol TuSDKICTouchImageViewInterface;

@interface TuSDKPFEditTurnAndCutView : UIView <TuSDKICTouchImageViewDelegate>
{
    TuSDKPFEditTurnAndCutBottomView *_bottomBar;
    UIView<TuSDKICTouchImageViewInterface> *_editImageView;
    TuSDKPFNormalFilterGroupView *_filterView;
    _Bool _enableFilters;
    Class _bottomBarViewClazz;
    Class _editImageViewClazz;
    Class _filterViewClazz;
    struct CGSize _cutSize;
}

@property(nonatomic, setter=setCutSize:) struct CGSize cutSize; // @synthesize cutSize=_cutSize;
@property(nonatomic) _Bool enableFilters; // @synthesize enableFilters=_enableFilters;
@property(readonly, nonatomic) TuSDKPFNormalFilterGroupView *filterView; // @synthesize filterView=_filterView;
@property(readonly, nonatomic) UIView<TuSDKICTouchImageViewInterface> *editImageView; // @synthesize editImageView=_editImageView;
@property(readonly, nonatomic) TuSDKPFEditTurnAndCutBottomView *bottomBar; // @synthesize bottomBar=_bottomBar;
@property(retain, nonatomic) Class filterViewClazz; // @synthesize filterViewClazz=_filterViewClazz;
@property(retain, nonatomic) Class editImageViewClazz; // @synthesize editImageViewClazz=_editImageViewClazz;
@property(retain, nonatomic) Class bottomBarViewClazz; // @synthesize bottomBarViewClazz=_bottomBarViewClazz;
- (void).cxx_destruct;
- (void)onTuSDKICTouchImageView:(id)arg1 inAniming:(_Bool)arg2;
- (void)setImage:(id)arg1;
- (void)onFilterViewToggle;
- (void)needUpdateLayout;
- (void)lsqInitView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

