//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class TuSDKTSAnimation;
@protocol TuSDKICSmudgeImageViewInterface;

@interface TuSDKPFSmudgeViewBase : UIView
{
    TuSDKTSAnimation *_anim;
    struct CGSize _toSize;
    struct CGSize _diffSize;
    UIView<TuSDKICSmudgeImageViewInterface> *_smudgeWrap;
    UIView *_sizeAnimView;
}

@property(readonly, nonatomic) UIView *sizeAnimView; // @synthesize sizeAnimView=_sizeAnimView;
@property(readonly, nonatomic) UIView<TuSDKICSmudgeImageViewInterface> *smudgeWrap; // @synthesize smudgeWrap=_smudgeWrap;
- (void).cxx_destruct;
- (void)viewWillDestory;
- (void)hideBrushSizeCursor;
- (void)showBrushSizeCursor:(struct CGPoint)arg1;
- (void)setBrushSizeViewHidden;
- (void)applyAnimationWithStep:(double)arg1;
- (id)anim;
- (void)showBrushSizeAnim:(double)arg1 to:(double)arg2;
- (void)lsqInitView;

@end

