//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImageFilterGroup.h"

#import "TuSDKFilterParameterProtocol-Protocol.h"

@class NSString, TuSDKFilterParameter, TuSDKGPUSurfaceBlurFilter, _TuSDKGPUSkin3rdFilter;

@interface TuSDKGPUSkin3rdFilter : GPUImageFilterGroup <TuSDKFilterParameterProtocol>
{
    TuSDKGPUSurfaceBlurFilter *_blurFilter;
    _TuSDKGPUSkin3rdFilter *_skinFilter;
    TuSDKFilterParameter *_parameter;
    double _blurSize;
    double _thresholdLevel;
    double _lightLevel;
    double _detailLevel;
    double _intensity;
}

@property(nonatomic) double intensity; // @synthesize intensity=_intensity;
@property(nonatomic) double detailLevel; // @synthesize detailLevel=_detailLevel;
@property(nonatomic) double lightLevel; // @synthesize lightLevel=_lightLevel;
@property(nonatomic) double thresholdLevel; // @synthesize thresholdLevel=_thresholdLevel;
@property(nonatomic) double blurSize; // @synthesize blurSize=_blurSize;
- (void).cxx_destruct;
- (void)submitParameter:(id)arg1;
- (void)submitParameter;
@property(retain, nonatomic) TuSDKFilterParameter *parameter; // @synthesize parameter=_parameter;
- (void)submitFilterArg:(id)arg1;
- (id)configParams:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

