//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPAlbumComponentBase.h"

#import "TuSDKPFAlbumDelegate-Protocol.h"
#import "TuSDKPFPhotosDelegate-Protocol.h"

@class NSString, TuSDKCPAlbumOptions;

@interface TuSDKCPAlbumComponent : TuSDKCPAlbumComponentBase <TuSDKPFAlbumDelegate, TuSDKPFPhotosDelegate>
{
    TuSDKCPAlbumOptions *_options;
}

@property(retain, nonatomic) TuSDKCPAlbumOptions *options; // @synthesize options=_options;
- (void).cxx_destruct;
- (void)onTuSDKPFPhotos:(id)arg1 selectedAsset:(id)arg2;
- (void)onTuSDKPFPhotos:(id)arg1 error:(id)arg2;
- (void)onTuSDKPFAlbum:(id)arg1 selectedGroup:(id)arg2;
- (void)showAlbum;
- (void)handleShowAlbum;
- (void)showComponent;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

