//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TuSDKFilterWrap, TuSDKNKFaceMark;

@interface TuSDKSkinFilterManager : NSObject
{
    TuSDKNKFaceMark *_imageAnalysis;
    TuSDKFilterWrap *_filterWrap;
}

+ (id)initSkinFilterWrap;
@property(retain, nonatomic) TuSDKFilterWrap *filterWrap; // @synthesize filterWrap=_filterWrap;
- (void).cxx_destruct;
- (void)dealloc;
- (void)destroy;
- (id)processWithImage:(id)arg1 orientation:(long long)arg2;
- (id)processWithImage:(id)arg1;
- (void)submitSkinFilterParameterWithImage:(id)arg1 smoothing:(double)arg2 whitening:(double)arg3 skinColor:(double)arg4 eyeSize:(double)arg5 chinSize:(double)arg6 completeHandler:(CDUnknownBlockType)arg7;
- (void)submitSkinFilterParameterWithSmoothing:(double)arg1 whitening:(double)arg2 skinColor:(double)arg3;
- (id)init;

@end

