//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITabBarController.h>

@class NSArray, NSString, TuSDKTSCControllerTrans, UIImage;
@protocol TuSDKTSAssetInterface;

@interface TuSDKPFEditTabBarControllerBase : UITabBarController
{
    _Bool _saveToTemp;
    _Bool _saveToAlbum;
    NSString *_saveToAlbumName;
    double _outputCompress;
    NSString *_inputTempFilePath;
    id <TuSDKTSAssetInterface> _inputAsset;
    UIImage *_inputImage;
    NSArray *_modules;
    TuSDKTSCControllerTrans *_transAnim;
}

@property(retain, nonatomic) TuSDKTSCControllerTrans *transAnim; // @synthesize transAnim=_transAnim;
@property(retain, nonatomic) NSArray *modules; // @synthesize modules=_modules;
@property(retain, nonatomic) UIImage *inputImage; // @synthesize inputImage=_inputImage;
@property(retain, nonatomic) id <TuSDKTSAssetInterface> inputAsset; // @synthesize inputAsset=_inputAsset;
@property(copy, nonatomic) NSString *inputTempFilePath; // @synthesize inputTempFilePath=_inputTempFilePath;
@property(nonatomic) double outputCompress; // @synthesize outputCompress=_outputCompress;
@property(copy, nonatomic) NSString *saveToAlbumName; // @synthesize saveToAlbumName=_saveToAlbumName;
@property(nonatomic) _Bool saveToAlbum; // @synthesize saveToAlbum=_saveToAlbum;
@property(nonatomic) _Bool saveToTemp; // @synthesize saveToTemp=_saveToTemp;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)backActionHadAnimated;
- (void)dismissHub;
- (void)viewDidLoad;

@end

