//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TuSDKTSAssetInterface-Protocol.h"

@class ALAsset, NSDate, NSDictionary, NSString, UIImage;

@interface TuSDKTSALAsset : NSObject <TuSDKTSAssetInterface>
{
    ALAsset *_asset;
}

+ (id)initWithALAsset:(id)arg1;
@property(readonly, nonatomic) ALAsset *asset; // @synthesize asset=_asset;
- (void).cxx_destruct;
- (void)cancelLoadImageWithPixelSize:(struct CGSize)arg1;
- (void)loadImageWithPixelSize:(struct CGSize)arg1 completed:(CDUnknownBlockType)arg2;
- (void)cancelLoadFullResolutionImage;
- (void)asyncFullResolutionImage:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) NSDictionary *metadata;
@property(readonly, nonatomic) struct CGSize fullResolutionImageSize;
@property(readonly, nonatomic) UIImage *fullScreenImage;
@property(readonly, nonatomic) UIImage *fullResolutionImage;
@property(readonly, nonatomic) UIImage *thumbnailImage;
@property(readonly, nonatomic) long long imageOrientation;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) NSString *localIdentifier;
@property(readonly, nonatomic) NSDate *creationDate;
- (id)initWithALAsset:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

