//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKICTableViewCell.h"

@class NSArray, NSMutableArray;
@protocol TuSDKPFStickerLocalViewProtocol;

@interface TuSDKPFStickerLocalCellView : TuSDKICTableViewCell
{
    NSMutableArray *_gridViews;
    Class _gridViewClazz;
    id <TuSDKPFStickerLocalViewProtocol> _gridProtocol;
}

@property(nonatomic) id <TuSDKPFStickerLocalViewProtocol> gridProtocol; // @synthesize gridProtocol=_gridProtocol;
@property(readonly, nonatomic) NSArray *gridViews; // @synthesize gridViews=_gridViews;
@property(retain, nonatomic) Class gridViewClazz; // @synthesize gridViewClazz=_gridViewClazz;
- (void).cxx_destruct;
- (void)onSelectedGrid:(id)arg1;
- (void)viewNeedRest;
- (void)setData:(id)arg1;
- (void)setAlgorithmic;
- (id)lsqSetSize:(struct CGSize)arg1;
- (void)lsqInitView;

@end

