//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImageFilterGroup.h"

@class GPUImageFilter, TuSDKGPUSurfaceBlurFilter;

@interface TuSDKGPUSkinFilter : GPUImageFilterGroup
{
    TuSDKGPUSurfaceBlurFilter *_blurFilter;
    GPUImageFilter *_unsharpMaskFilter;
    double _blurSize;
    double _intensity;
    double _thresholdLevel;
    double _lightLevel;
    double _detailLevel;
}

@property(nonatomic) double detailLevel; // @synthesize detailLevel=_detailLevel;
@property(nonatomic) double lightLevel; // @synthesize lightLevel=_lightLevel;
@property(nonatomic) double thresholdLevel; // @synthesize thresholdLevel=_thresholdLevel;
@property(nonatomic) double intensity; // @synthesize intensity=_intensity;
@property(nonatomic) double blurSize; // @synthesize blurSize=_blurSize;
- (void).cxx_destruct;
@property(readonly, nonatomic) double maxThresholdLevel;
@property(readonly, nonatomic) double maxBlursize;
- (id)init;

@end

