//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class TuSDKPFEditFilterBottomBar, TuSDKPFEditFilterGroupView;
@protocol TuSDKICFilterImageViewInterface;

@interface TuSDKPFEditFilterView : UIView
{
    UIView<TuSDKICFilterImageViewInterface> *_imageView;
    TuSDKPFEditFilterBottomBar *_bottomBar;
    TuSDKPFEditFilterGroupView *_filterBar;
}

@property(readonly, nonatomic) TuSDKPFEditFilterGroupView *filterBar; // @synthesize filterBar=_filterBar;
@property(readonly, nonatomic) TuSDKPFEditFilterBottomBar *bottomBar; // @synthesize bottomBar=_bottomBar;
@property(readonly, nonatomic) UIView<TuSDKICFilterImageViewInterface> *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)lsqInitView;

@end

