//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPGroupFilterItemCellBase.h"

#import "TuSDKCPGroupFilterItemCellInterface-Protocol.h"

@class NSString, TuSDKCPGroupFilterItem, UIImageView, UILabel, UIView;
@protocol TuSDKTKFiltersTaskInterface;

@interface TuSDKCPGroupFilterItemCell : TuSDKCPGroupFilterItemCellBase <TuSDKCPGroupFilterItemCellInterface>
{
    UIView *_wrapView;
    UIImageView *_thumbView;
    UILabel *_titleView;
    UIView *_selectedView;
    UIImageView *_iconView;
    UIView *_flagView;
}

@property(readonly, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(readonly, nonatomic) UIView *selectedView; // @synthesize selectedView=_selectedView;
@property(readonly, nonatomic) UIView *flagView; // @synthesize flagView=_flagView;
@property(readonly, nonatomic) UILabel *titleView; // @synthesize titleView=_titleView;
@property(readonly, nonatomic) UIView *wrapView; // @synthesize wrapView=_wrapView;
- (void).cxx_destruct;
- (void)stopActivating;
- (void)waitInActivate:(double)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)viewNeedRest;
- (void)setImageColor:(id)arg1;
- (void)setFlagColor:(id)arg1;
- (void)handleBlockView:(id)arg1 icon:(id)arg2;
- (void)handleTypeOnlie:(id)arg1;
- (void)handleTypeHistory:(id)arg1;
- (void)handleTypeFilter:(id)arg1;
- (void)handleTypeGroup:(id)arg1;
- (void)handleTypeOrgin:(id)arg1;
- (void)setSelectedIcon:(id)arg1 needIcon:(_Bool)arg2;
@property(retain, nonatomic) TuSDKCPGroupFilterItem *mode;
- (id)thumbView;
- (id)lsqSetSize:(struct CGSize)arg1;
- (void)lsqInitView;

// Remaining properties
@property(nonatomic) long long action;
@property(readonly, nonatomic) _Bool activating;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) _Bool displaySelectionIcon;
@property(nonatomic) id <TuSDKTKFiltersTaskInterface> filterTask;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

