//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPImageResultOptions.h"

@class NSArray;

@interface TuSDKPFEditSmudgeOptions : TuSDKCPImageResultOptions
{
    _Bool _saveLastBrush;
    Class _viewClazz;
    unsigned long long _brushBarCellWidth;
    unsigned long long _brushBarHeight;
    Class _brushBarCellClazz;
    NSArray *_brushGroup;
    long long _defaultBrushSize;
    unsigned long long _maxUndoCount;
}

@property(nonatomic) unsigned long long maxUndoCount; // @synthesize maxUndoCount=_maxUndoCount;
@property(nonatomic) _Bool saveLastBrush; // @synthesize saveLastBrush=_saveLastBrush;
@property(nonatomic) long long defaultBrushSize; // @synthesize defaultBrushSize=_defaultBrushSize;
@property(retain, nonatomic) NSArray *brushGroup; // @synthesize brushGroup=_brushGroup;
@property(retain, nonatomic) Class brushBarCellClazz; // @synthesize brushBarCellClazz=_brushBarCellClazz;
@property(nonatomic) unsigned long long brushBarHeight; // @synthesize brushBarHeight=_brushBarHeight;
@property(nonatomic) unsigned long long brushBarCellWidth; // @synthesize brushBarCellWidth=_brushBarCellWidth;
@property(retain, nonatomic) Class viewClazz; // @synthesize viewClazz=_viewClazz;
- (void).cxx_destruct;
- (id)viewController;
- (Class)defaultComponentClazz;
- (void)initOptions;

@end

