//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TuSDKPFBrushTableViewInterface-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSString, TuSDKICTableView;
@protocol TuSDKPFBrushTableViewDelegate;

@interface TuSDKPFBrushTableView : UIView <UITableViewDataSource, UITableViewDelegate, TuSDKPFBrushTableViewInterface>
{
    double _mainRotat;
    double _cellWidth;
    Class _cellViewClazz;
    long long _action;
    id <TuSDKPFBrushTableViewDelegate> _delegate;
    NSArray *_modeList;
    TuSDKICTableView *_tableView;
}

@property(readonly, nonatomic) TuSDKICTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSArray *modeList; // @synthesize modeList=_modeList;
@property(nonatomic) __weak id <TuSDKPFBrushTableViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long action; // @synthesize action=_action;
@property(retain, nonatomic) Class cellViewClazz; // @synthesize cellViewClazz=_cellViewClazz;
- (void).cxx_destruct;
- (void)scrollToRowAtIndexPath:(id)arg1 atScrollPosition:(long long)arg2 animated:(_Bool)arg3;
- (void)deleteRowsAtIndexPaths:(id)arg1 withRowAnimation:(long long)arg2;
- (void)insertRowsAtIndexPaths:(id)arg1 withRowAnimation:(long long)arg2;
- (id)indexPathForSelectedRow;
- (void)reloadData;
- (void)changeSelectPostion:(unsigned long long)arg1 scrollToCenter:(_Bool)arg2 anim:(_Bool)arg3;
- (void)selectPostion:(unsigned long long)arg1 scrollToCenter:(_Bool)arg2 reload:(_Bool)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)onCellWillSelectRowAtIndexPath:(id)arg1;
- (id)modeAtIndexPath:(id)arg1;
@property(nonatomic) double cellWidth; // @synthesize cellWidth=_cellWidth;
- (void)lsqInitView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

