//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKPFEditSmudgeControllerBase.h"

#import "TuSDKPFBrushBarViewDelegate-Protocol.h"

@class NSArray, NSString, TuSDKPFEditSmudgeView;
@protocol TuSDKPFEditSmudgeControllerDelegate;

@interface TuSDKPFEditSmudgeController : TuSDKPFEditSmudgeControllerBase <TuSDKPFBrushBarViewDelegate>
{
    TuSDKPFEditSmudgeView *_defaultStyleView;
    _Bool _saveLastBrush;
    id <TuSDKPFEditSmudgeControllerDelegate> _delegate;
    Class _viewClazz;
    unsigned long long _brushBarCellWidth;
    unsigned long long _brushBarHeight;
    Class _brushBarCellClazz;
    NSArray *_brushGroup;
    long long _defaultBrushSize;
    unsigned long long _maxUndoCount;
}

@property(nonatomic) unsigned long long maxUndoCount; // @synthesize maxUndoCount=_maxUndoCount;
@property(nonatomic) _Bool saveLastBrush; // @synthesize saveLastBrush=_saveLastBrush;
@property(nonatomic) long long defaultBrushSize; // @synthesize defaultBrushSize=_defaultBrushSize;
@property(retain, nonatomic) NSArray *brushGroup; // @synthesize brushGroup=_brushGroup;
@property(retain, nonatomic) Class brushBarCellClazz; // @synthesize brushBarCellClazz=_brushBarCellClazz;
@property(nonatomic) unsigned long long brushBarHeight; // @synthesize brushBarHeight=_brushBarHeight;
@property(nonatomic) unsigned long long brushBarCellWidth; // @synthesize brushBarCellWidth=_brushBarCellWidth;
@property(retain, nonatomic) Class viewClazz; // @synthesize viewClazz=_viewClazz;
@property(nonatomic) __weak id <TuSDKPFEditSmudgeControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) TuSDKPFEditSmudgeView *defaultStyleView; // @synthesize defaultStyleView=_defaultStyleView;
- (void).cxx_destruct;
- (void)onBrushSizeButtonClick;
- (void)brushBarView:(id)arg1 selectBrush:(id)arg2;
- (void)onSmudgeActionEnd;
- (void)onSmudgeActionChanged:(struct CGPoint)arg1 viewLocation:(struct CGPoint)arg2 canvasWidth:(double)arg3 canvasHeight:(double)arg4;
- (void)onRefreshStepStatesWithHistories:(unsigned long long)arg1 redoCount:(unsigned long long)arg2;
- (void)onImageCompleteAction;
- (void)loadedInputImage:(id)arg1;
- (void)configWithBottomBar:(id)arg1;
- (void)configWithBrushBarView:(id)arg1;
- (void)configDefaultBrushSettings;
- (void)configDefaultStyleView:(id)arg1;
- (void)buildDefaultStyleView;
- (id)smudgeView;
- (void)viewDidLoad;
- (_Bool)prefersStatusBarHidden;
- (void)loadView;
- (_Bool)asyncNotifyProcessingWithResult:(id)arg1;
- (void)notifyProcessingWithResult:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

