//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKPFEditSkinControllerBase.h"

@interface TuSDKPFEditSkinController : TuSDKPFEditSkinControllerBase
{
    Class _viewClazz;
}

@property(retain, nonatomic) Class viewClazz; // @synthesize viewClazz=_viewClazz;
- (void).cxx_destruct;
- (void)onConfigCancalAction;
- (void)onConfigCompleteAction;
- (void)onFaceDetectionResult:(_Bool)arg1;
- (void)setConfigViewHiddenState:(_Bool)arg1;
- (void)configDefaultStyleView:(id)arg1;
- (void)viewDidLoad;
- (_Bool)prefersStatusBarHidden;
- (void)loadView;

@end

