//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPComponentErrorDelegate-Protocol.h"

@class NSError, TuSDKPFAlbumViewController;
@protocol TuSDKTSAssetsGroupInterface;

@protocol TuSDKPFAlbumDelegate <TuSDKCPComponentErrorDelegate>
- (void)onTuSDKPFPhotos:(TuSDKPFAlbumViewController *)arg1 error:(NSError *)arg2;
- (void)onTuSDKPFAlbum:(TuSDKPFAlbumViewController *)arg1 selectedGroup:(id <TuSDKTSAssetsGroupInterface>)arg2;
@end

