//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, TuSDKFilterWrap;
@protocol TuSDKVideoCameraInterface;

@protocol TuSDKVideoCameraExtendViewInterface <NSObject>
@property(nonatomic) _Bool displayGuideLine;
@property(nonatomic) struct CGRect regionPercent;
@property(nonatomic) double longTouchDelay;
@property(nonatomic) double autoFoucsDelay;
@property(nonatomic) _Bool disableTapFocus;
@property(nonatomic) _Bool disableContinueFoucs;
@property(nonatomic) _Bool enableLongTouchCapture;
@property(nonatomic) id <TuSDKVideoCameraInterface> camera;
- (void)notifyFaceDetection:(NSArray *)arg1 size:(struct CGSize)arg2;
- (void)notifyFilterConfigView:(TuSDKFilterWrap *)arg1;
- (void)onAdjustingFocus:(_Bool)arg1;
- (void)cameraStateChanged:(long long)arg1;
@end

