//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TuSDKPFBrushLocalPackageDelegate-Protocol.h"

@class NSString;
@protocol TuSDKPFBrushLocalPackageDelegate;

@interface TuSDKPFBrushLocalPackageDelegateBridge : NSObject <TuSDKPFBrushLocalPackageDelegate>
{
    id <TuSDKPFBrushLocalPackageDelegate> _delegate;
}

+ (id)initWithDelegate:(id)arg1;
@property(nonatomic) __weak id <TuSDKPFBrushLocalPackageDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onDestory;
- (_Bool)isEqualDelegate:(id)arg1;
- (void)brushManager:(id)arg1 item:(id)arg2 changedStatus:(long long)arg3;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

