//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPImageResultOptions.h"

@interface TuSDKPFEditWipeAndFilterOptions : TuSDKCPImageResultOptions
{
    _Bool _displayMagnifier;
    Class _viewClazz;
    long long _defaultBrushSize;
    unsigned long long _maxUndoCount;
    double _brushStrength;
}

@property(nonatomic) double brushStrength; // @synthesize brushStrength=_brushStrength;
@property(nonatomic) _Bool displayMagnifier; // @synthesize displayMagnifier=_displayMagnifier;
@property(nonatomic) unsigned long long maxUndoCount; // @synthesize maxUndoCount=_maxUndoCount;
@property(nonatomic) long long defaultBrushSize; // @synthesize defaultBrushSize=_defaultBrushSize;
@property(retain, nonatomic) Class viewClazz; // @synthesize viewClazz=_viewClazz;
- (void).cxx_destruct;
- (id)viewController;
- (Class)defaultComponentClazz;
- (void)initOptions;

@end

