//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableParagraphStyle, NSString, UIColor, UIFont;

@interface TuSDKPFEditTextViewOptions : NSObject
{
    _Bool _enableUnderline;
    UIColor *_textColor;
    UIFont *_textFont;
    NSString *_textString;
    NSMutableParagraphStyle *_textParaStyle;
    NSArray *_writingDirection;
    long long _textAlignment;
    UIColor *_textBackgroudColor;
    UIColor *_textStrokeColor;
    double _textBorderWidth;
    UIColor *_textBorderColor;
    double _textMaxScale;
    struct UIEdgeInsets _textEdgeInsets;
}

+ (id)defaultOptions;
@property(nonatomic) double textMaxScale; // @synthesize textMaxScale=_textMaxScale;
@property(nonatomic) struct UIEdgeInsets textEdgeInsets; // @synthesize textEdgeInsets=_textEdgeInsets;
@property(retain, nonatomic) UIColor *textBorderColor; // @synthesize textBorderColor=_textBorderColor;
@property(nonatomic) double textBorderWidth; // @synthesize textBorderWidth=_textBorderWidth;
@property(retain, nonatomic) UIColor *textStrokeColor; // @synthesize textStrokeColor=_textStrokeColor;
@property(retain, nonatomic) UIColor *textBackgroudColor; // @synthesize textBackgroudColor=_textBackgroudColor;
@property(nonatomic) long long textAlignment; // @synthesize textAlignment=_textAlignment;
@property(retain, nonatomic) NSArray *writingDirection; // @synthesize writingDirection=_writingDirection;
@property(nonatomic) _Bool enableUnderline; // @synthesize enableUnderline=_enableUnderline;
@property(retain, nonatomic) NSMutableParagraphStyle *textParaStyle; // @synthesize textParaStyle=_textParaStyle;
@property(retain, nonatomic) NSString *textString; // @synthesize textString=_textString;
@property(retain, nonatomic) UIFont *textFont; // @synthesize textFont=_textFont;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
- (void).cxx_destruct;

@end

