//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TuSDKTSAssetsGroupInterface-Protocol.h"

@class ALAssetsGroup, NSString, UIImage;

@interface TuSDKTSALAssetsGroup : NSObject <TuSDKTSAssetsGroupInterface>
{
    ALAssetsGroup *_group;
}

+ (id)initWithALAssetsGroup:(id)arg1;
@property(readonly, nonatomic) ALAssetsGroup *group; // @synthesize group=_group;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long count;
@property(readonly, nonatomic) UIImage *posterImage;
- (id)allPhotos;
- (id)allPhotosWithSortKeyType:(long long)arg1 ascending:(_Bool)arg2;
@property(readonly, nonatomic) NSString *title;
@property(readonly, nonatomic) _Bool userLibrary;
- (id)initWithALAssetsGroup:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

