//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKPFStickerLocalControllerBase.h"

#import "TuSDKICPagerViewDataSource-Protocol.h"
#import "TuSDKPFStickerLocalViewProtocol-Protocol.h"
#import "TuSDKPFStickerOnlineControllerDelegate-Protocol.h"

@class NSString, TuSDKPFStickerLocalView;
@protocol TuSDKPFStickerLocalControllerDelegate;

@interface TuSDKPFStickerLocalController : TuSDKPFStickerLocalControllerBase <TuSDKICPagerViewDataSource, TuSDKPFStickerLocalViewProtocol, TuSDKPFStickerOnlineControllerDelegate>
{
    TuSDKPFStickerLocalView *_defaultStyleView;
    Class _cellViewClazz;
    Class _gridViewClazz;
    Class _cellHeaderViewClazz;
    Class _emptyViewClazz;
    id <TuSDKPFStickerLocalControllerDelegate> _delegate;
    Class _viewClazz;
}

@property(retain, nonatomic) Class viewClazz; // @synthesize viewClazz=_viewClazz;
@property(nonatomic) __weak id <TuSDKPFStickerLocalControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) TuSDKPFStickerLocalView *defaultStyleView; // @synthesize defaultStyleView=_defaultStyleView;
@property(retain, nonatomic) Class emptyViewClazz; // @synthesize emptyViewClazz=_emptyViewClazz;
@property(retain, nonatomic) Class cellHeaderViewClazz; // @synthesize cellHeaderViewClazz=_cellHeaderViewClazz;
@property(retain, nonatomic) Class gridViewClazz; // @synthesize gridViewClazz=_gridViewClazz;
@property(retain, nonatomic) Class cellViewClazz; // @synthesize cellViewClazz=_cellViewClazz;
- (void).cxx_destruct;
- (void)reloadStickers;
- (void)pagerView:(id)arg1 didShowPageIndex:(unsigned long long)arg2;
- (void)pagerView:(id)arg1 holder:(id)arg2 pageIndex:(unsigned long long)arg3;
- (unsigned long long)numberOfPagesInPagerView:(id)arg1;
- (void)onTuSDKPFStickerLocalViewAction:(long long)arg1 group:(id)arg2;
- (void)onTuSDKPFStickerLocalViewEmptyAction;
- (void)onTuSDKPFStickerLocalViewSelected:(id)arg1;
- (void)onTuSDKPFStickerOnline:(id)arg1 selectedSticker:(id)arg2;
- (void)onCategorySelectedAction:(id)arg1;
- (void)configDefaultStyleView:(id)arg1;
- (void)buildDefaultStyleView;
- (_Bool)prefersStatusBarHidden;
- (void)onMoreAction;
- (void)viewDidLoad;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

