//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKPFEditEntryControllerBase.h"

@class TuSDKPFEditEntryView;
@protocol TuSDKPFEditEntryControllerDelegate, TuSDKPFStickerViewDelegate;

@interface TuSDKPFEditEntryController : TuSDKPFEditEntryControllerBase
{
    TuSDKPFEditEntryView *_defaultStyleView;
    _Bool _enableCuter;
    _Bool _enableFilter;
    _Bool _enableSticker;
    id <TuSDKPFEditEntryControllerDelegate> _delegate;
    id <TuSDKPFStickerViewDelegate> _stickerViewDelegate;
    Class _viewClazz;
}

@property(nonatomic) _Bool enableSticker; // @synthesize enableSticker=_enableSticker;
@property(nonatomic) _Bool enableFilter; // @synthesize enableFilter=_enableFilter;
@property(nonatomic) _Bool enableCuter; // @synthesize enableCuter=_enableCuter;
@property(retain, nonatomic) Class viewClazz; // @synthesize viewClazz=_viewClazz;
@property(nonatomic) __weak id <TuSDKPFStickerViewDelegate> stickerViewDelegate; // @synthesize stickerViewDelegate=_stickerViewDelegate;
@property(nonatomic) __weak id <TuSDKPFEditEntryControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) TuSDKPFEditEntryView *defaultStyleView; // @synthesize defaultStyleView=_defaultStyleView;
- (void).cxx_destruct;
- (void)onEntryAction:(id)arg1;
- (void)loadedInputImage:(id)arg1;
- (void)configDefaultStyleView:(id)arg1;
- (void)buildDefaultStyleView;
- (void)viewDidLoad;
- (void)loadView;
- (_Bool)prefersStatusBarHidden;
- (id)imageView;
- (_Bool)asyncNotifyProcessingWithResult:(id)arg1;
- (void)notifyProcessingWithResult:(id)arg1;

@end

