//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TuSDKTSMath : NSObject
{
}

+ (struct UIEdgeInsets)mergeEnclosingRectangle:(struct UIEdgeInsets)arg1 point:(struct CGPoint)arg2 degree:(double)arg3;
+ (struct CGRect)minEnclosingRectangle:(struct CGPoint)arg1 size:(struct CGSize)arg2 degree:(double)arg3;
+ (struct CGPoint)rotationPoint:(struct CGPoint)arg1 toDegree:(double)arg2;
+ (double)degreesWithPoint:(struct CGPoint)arg1 center:(struct CGPoint)arg2;
+ (double)distanceOfPointX1:(double)arg1 y1:(double)arg2 pointX2:(double)arg3 y2:(double)arg4;
+ (double)distanceOfEndPoint:(struct CGPoint)arg1 startPoint:(struct CGPoint)arg2;
+ (double)numberFloat:(double)arg1 modulus:(long long)arg2;
+ (double)degreesOfAngle:(double)arg1;
+ (double)angleOfDegrees:(double)arg1;

@end

