//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol TuSDKICSmudgeImageViewDelegate <NSObject>
- (void)onRefreshStepStatesWithHistories:(unsigned long long)arg1 redoCount:(unsigned long long)arg2;

@optional
- (void)onSmudgeActionEnd;
- (void)onSmudgeActionChanged:(struct CGPoint)arg1 viewLocation:(struct CGPoint)arg2 canvasWidth:(double)arg3 canvasHeight:(double)arg4;
@end

