//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSMutableParagraphStyle, NSString, TuSDKPFSticker, TuSDKPFStickerResult, UIColor, UIFont;
@protocol TuSDKPFTextItemViewDelegate;

@protocol TuSDKPFTextItemViewInterface <NSObject>
@property(nonatomic) double textMaxScale;
@property(nonatomic) struct UIEdgeInsets textEdgeInsets;
@property(retain, nonatomic) UIColor *textStrokeColor;
@property(retain, nonatomic) UIColor *textBackgroudColor;
@property(nonatomic) long long textAlignment;
@property(retain, nonatomic) NSArray *writingDirection;
@property(nonatomic) _Bool enableUnderline;
@property(retain, nonatomic) NSMutableParagraphStyle *textParaStyle;
@property(retain, nonatomic) NSString *textString;
@property(nonatomic) _Bool selected;
@property(retain, nonatomic) UIColor *textColor;
@property(retain, nonatomic) UIColor *textBorderColor;
@property(nonatomic) double textBorderWidth;
@property(retain, nonatomic) TuSDKPFSticker *textSticker;
@property(nonatomic) __weak id <TuSDKPFTextItemViewDelegate> delegate;
- (TuSDKPFStickerResult *)resultWithRegionRect:(struct CGRect)arg1;
- (void)initWithTextFont:(UIFont *)arg1;
@end

