//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIColor;

@interface TuSDKCPGroupFilterItemColor : NSObject
{
    UIColor *_history;
    UIColor *_online;
    UIColor *_orgin;
}

+ (id)shared;
@property(retain, nonatomic) UIColor *orgin; // @synthesize orgin=_orgin;
@property(retain, nonatomic) UIColor *online; // @synthesize online=_online;
@property(retain, nonatomic) UIColor *history; // @synthesize history=_history;
- (void).cxx_destruct;

@end

