//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKTKImageViewTaskWare.h"

@class TuSDKFilterGroup, TuSDKFilterOption;

@interface TuSDKFilterThumbTaskImageWare : TuSDKTKImageViewTaskWare
{
    TuSDKFilterGroup *_group;
    TuSDKFilterOption *_option;
    long long _taskType;
}

+ (id)initWithImageView:(id)arg1 taskType:(long long)arg2 option:(id)arg3 group:(id)arg4;
@property(nonatomic) long long taskType; // @synthesize taskType=_taskType;
@property(retain, nonatomic) TuSDKFilterOption *option; // @synthesize option=_option;
@property(retain, nonatomic) TuSDKFilterGroup *group; // @synthesize group=_group;
- (void).cxx_destruct;
- (id)cacheKey;

@end

