//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPFilterResultController.h"

@class TuSDKFilterWrap, TuSDKNKFaceMark;

@interface TuSDKPFEditSkinControllerBase : TuSDKCPFilterResultController
{
    unsigned long long _mCurrentIndex;
    double _mInitialValue;
    TuSDKNKFaceMark *_imageAnalysis;
    TuSDKFilterWrap *_filterWrap;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)onTuSDKCPParameterConfig:(id)arg1 resetWithIndex:(unsigned long long)arg2;
- (double)onTuSDKCPParameterConfig:(id)arg1 valueWithIndex:(unsigned long long)arg2;
- (void)onTuSDKCPParameterConfig:(id)arg1 changeWithIndex:(unsigned long long)arg2 progress:(double)arg3;
- (void)onTuSDKCPParameterConfigBackNotSave:(id)arg1;
- (unsigned long long)getCurrentAction;
- (void)onArgSelectedAction:(id)arg1;
- (void)onFaceDetectionResult:(_Bool)arg1;
- (void)setConfigViewHiddenState:(_Bool)arg1;
- (void)autoAnalysisPic;
- (void)loadedInputImage:(id)arg1;
- (void)viewDidLoad;
- (id)_buildfilterWrap;

@end

