//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSString, TuSDKICTableView;
@protocol TuSDKPFStickerTableViewDelegate;

@interface TuSDKPFStickerTableView : UIView <UITableViewDataSource, UITableViewDelegate>
{
    double _mainRotat;
    double _cellWidth;
    Class _cellViewClazz;
    id <TuSDKPFStickerTableViewDelegate> _delegate;
    NSArray *_modeList;
    long long _gridPadding;
    TuSDKICTableView *_tableView;
}

@property(readonly, nonatomic) TuSDKICTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) long long gridPadding; // @synthesize gridPadding=_gridPadding;
@property(retain, nonatomic) NSArray *modeList; // @synthesize modeList=_modeList;
@property(nonatomic) __weak id <TuSDKPFStickerTableViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) Class cellViewClazz; // @synthesize cellViewClazz=_cellViewClazz;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)onCellWillSelectRowAtIndexPath:(id)arg1;
- (id)modeAtIndexPath:(id)arg1;
- (void)reloadData:(_Bool)arg1;
@property(nonatomic) double cellWidth; // @synthesize cellWidth=_cellWidth;
- (id)lsqSetSizeHeight:(double)arg1;
- (void)lsqInitView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

