//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TuSDKICSeekBarDelegate-Protocol.h"

@class NSString, TuSDKFilterArg, TuSDKICSeekBar, UILabel;
@protocol TuSDKPFFilterSeekbarDelegate;

@interface TuSDKPFFilterSeekbar : UIView <TuSDKICSeekBarDelegate>
{
    id <TuSDKPFFilterSeekbarDelegate> _delegate;
    TuSDKICSeekBar *_seekBar;
    UILabel *_titleView;
    UILabel *_numberView;
    TuSDKFilterArg *_filterArg;
}

@property(retain, nonatomic) TuSDKFilterArg *filterArg; // @synthesize filterArg=_filterArg;
@property(readonly, nonatomic) UILabel *numberView; // @synthesize numberView=_numberView;
@property(readonly, nonatomic) UILabel *titleView; // @synthesize titleView=_titleView;
@property(readonly, nonatomic) TuSDKICSeekBar *seekBar; // @synthesize seekBar=_seekBar;
@property(nonatomic) __weak id <TuSDKPFFilterSeekbarDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onTuSDKICSeekBar:(id)arg1 changedProgress:(double)arg2;
- (void)reset;
- (void)setProgress:(double)arg1;
- (void)lsqInitView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

