//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

@class CADisplayLink, NSMutableDictionary, NSOperationQueue, NSString, UIImage;
@protocol TuSDKCPAnimationImage, TuSDKPFGifViewDelegate;

@interface TuSDKICGifView : UIImageView
{
    UIImage<TuSDKCPAnimationImage> *_curAnimatedImage;
    long long _onceToken;
    int _lock;
    NSOperationQueue *_requestQueue;
    CADisplayLink *_caDisplayLink;
    double _time;
    UIImage *_curFrame;
    unsigned long long _curIndex;
    unsigned long long _totalFrameCount;
    _Bool _loopEnd;
    unsigned long long _curLoop;
    unsigned long long _totalLoop;
    NSMutableDictionary *_buffer;
    _Bool _bufferMiss;
    unsigned long long _maxBufferCount;
    long long _incrBufferCount;
    struct CGRect _curContentsRect;
    _Bool _curImageHasContentsRect;
    _Bool _isRunning;
    _Bool _autoPlay;
    id <TuSDKPFGifViewDelegate> _delegate;
    NSString *_runloopMode;
}

+ (_Bool)automaticallyNotifiesObserversForKey:(id)arg1;
@property(copy, nonatomic) NSString *runloopMode; // @synthesize runloopMode=_runloopMode;
@property(nonatomic) _Bool autoPlay; // @synthesize autoPlay=_autoPlay;
@property(nonatomic) __weak id <TuSDKPFGifViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)calcMaxBufferCount;
- (void)notifyAnimationEvent:(unsigned long long)arg1;
- (void)didMoveToSuperview;
- (void)didMoveToWindow;
- (void)didMoved;
- (void)setContentsRect:(struct CGRect)arg1 forImage:(id)arg2;
- (void)displayLayer:(id)arg1;
- (void)step:(id)arg1;
- (void)didEnterBackground:(id)arg1;
- (void)didReceiveMemoryWarning:(id)arg1;
- (void)imageChanged;
@property(nonatomic) unsigned long long currentFrameIndex;
- (void)resetAnimation;
- (void)stopAnimating;
- (void)startAnimating;
@property(readonly, nonatomic) unsigned long long frameCount;
- (_Bool)isAnimating;
- (void)initConfig;
- (unsigned long long)currentImageType;
- (id)imageForType:(unsigned long long)arg1;
- (void)setImage:(id)arg1 withType:(unsigned long long)arg2;
- (void)setHighlightedImage:(id)arg1;
- (void)setImage:(id)arg1;
- (id)initWithImage:(id)arg1 highlightedImage:(id)arg2;
- (id)initWithImage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

