//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKDataJson.h"

@class NSArray, NSDate;

@interface TuSDKPermission : TuSDKDataJson
{
    _Bool _noPower;
    _Bool _renderFilterThumb;
    _Bool _smudgeEnabled;
    _Bool _wipeFilterEnabled;
    _Bool _hdrFilterEnabled;
    _Bool _videoRecordEnabled;
    _Bool _videoDurationEnabled;
    _Bool _videoStreamEnabled;
    _Bool _videoEditEnabled;
    _Bool _faceLocalImageSupport;
    _Bool _faceLocalVideoSupport;
    _Bool _faceLocalBeautySupport;
    _Bool _filterAPIEnabled;
    long long _level;
    NSDate *_serviceExpire;
    long long _resolution;
    long long _stickerUseCount;
    long long _localFilterCount;
    long long _localStickerCount;
    long long _beautyLevel;
    long long _userType;
    long long _faceLocalMarks;
    NSArray *_filterAPIList;
}

@property(retain, nonatomic) NSArray *filterAPIList; // @synthesize filterAPIList=_filterAPIList;
@property(nonatomic) _Bool filterAPIEnabled; // @synthesize filterAPIEnabled=_filterAPIEnabled;
@property(nonatomic) _Bool faceLocalBeautySupport; // @synthesize faceLocalBeautySupport=_faceLocalBeautySupport;
@property(nonatomic) _Bool faceLocalVideoSupport; // @synthesize faceLocalVideoSupport=_faceLocalVideoSupport;
@property(nonatomic) _Bool faceLocalImageSupport; // @synthesize faceLocalImageSupport=_faceLocalImageSupport;
@property(nonatomic) long long faceLocalMarks; // @synthesize faceLocalMarks=_faceLocalMarks;
@property(nonatomic) _Bool videoEditEnabled; // @synthesize videoEditEnabled=_videoEditEnabled;
@property(nonatomic) _Bool videoStreamEnabled; // @synthesize videoStreamEnabled=_videoStreamEnabled;
@property(nonatomic) _Bool videoDurationEnabled; // @synthesize videoDurationEnabled=_videoDurationEnabled;
@property(nonatomic) _Bool videoRecordEnabled; // @synthesize videoRecordEnabled=_videoRecordEnabled;
@property(nonatomic) long long userType; // @synthesize userType=_userType;
@property(nonatomic) long long beautyLevel; // @synthesize beautyLevel=_beautyLevel;
@property(nonatomic) _Bool hdrFilterEnabled; // @synthesize hdrFilterEnabled=_hdrFilterEnabled;
@property(nonatomic) _Bool wipeFilterEnabled; // @synthesize wipeFilterEnabled=_wipeFilterEnabled;
@property(nonatomic) _Bool smudgeEnabled; // @synthesize smudgeEnabled=_smudgeEnabled;
@property(nonatomic) _Bool renderFilterThumb; // @synthesize renderFilterThumb=_renderFilterThumb;
@property(nonatomic) long long localStickerCount; // @synthesize localStickerCount=_localStickerCount;
@property(nonatomic) long long localFilterCount; // @synthesize localFilterCount=_localFilterCount;
@property(nonatomic) long long stickerUseCount; // @synthesize stickerUseCount=_stickerUseCount;
@property(nonatomic) long long resolution; // @synthesize resolution=_resolution;
@property(retain, nonatomic) NSDate *serviceExpire; // @synthesize serviceExpire=_serviceExpire;
@property(nonatomic) _Bool noPower; // @synthesize noPower=_noPower;
@property(nonatomic) long long level; // @synthesize level=_level;
- (void).cxx_destruct;
- (void)deserializationWithJson:(id)arg1;

@end

