//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPComponentErrorDelegate-Protocol.h"

@class TuSDKPFEditMultipleController, TuSDKResult;

@protocol TuSDKPFEditMultipleControllerDelegate <TuSDKCPComponentErrorDelegate>
- (void)onTuSDKPFEditMultiple:(TuSDKPFEditMultipleController *)arg1 action:(long long)arg2;
- (void)onTuSDKPFEditMultiple:(TuSDKPFEditMultipleController *)arg1 result:(TuSDKResult *)arg2;

@optional
- (_Bool)onAsyncTuSDKPFEditMultiple:(TuSDKPFEditMultipleController *)arg1 result:(TuSDKResult *)arg2;
@end

