//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDate, NSDictionary, NSString, UIImage;

@protocol TuSDKTSAssetInterface <NSObject>
@property(readonly, nonatomic) NSDictionary *metadata;
@property(readonly, nonatomic) struct CGSize fullResolutionImageSize;
@property(readonly, nonatomic) UIImage *fullResolutionImage;
@property(readonly, nonatomic) UIImage *fullScreenImage;
@property(readonly, nonatomic) UIImage *thumbnailImage;
@property(readonly, nonatomic) long long imageOrientation;
@property(readonly, nonatomic) NSDate *creationDate;
@property(readonly, nonatomic) NSString *localIdentifier;
- (void)cancelLoadImageWithPixelSize:(struct CGSize)arg1;
- (void)loadImageWithPixelSize:(struct CGSize)arg1 completed:(void (^)(UIImage *))arg2;
- (void)cancelLoadFullResolutionImage;
- (void)asyncFullResolutionImage:(void (^)(UIImage *, double, NSError *))arg1;
@end

