//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKFilterFacePositionProtocol-Protocol.h"

@class NSArray;

@protocol TuSDKFilterStickerProtocol <TuSDKFilterFacePositionProtocol>
- (void)setStickerShowTime:(CDStruct_1b6d18a9)arg1;
- (void)setAutoplayStickers:(_Bool)arg1;
- (void)setStickerVisibility:(_Bool)arg1;
- (void)setDisplayRect:(struct CGRect)arg1 withRatio:(double)arg2;
- (void)setLiveStickers:(NSArray *)arg1;
@end

