//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TuSDKCPComponentErrorDelegate-Protocol.h"

@class NSString, UIViewController;

@interface TuSDKCPComponent : NSObject <TuSDKCPComponentErrorDelegate>
{
    _Bool _autoPushViewController;
    _Bool _autoDismissWhenCompelted;
    UIViewController *_sourceController;
    CDUnknownBlockType _callbackBlock;
}

+ (id)initWithSourceController:(id)arg1 callbackBlock:(CDUnknownBlockType)arg2;
@property(nonatomic) _Bool autoDismissWhenCompelted; // @synthesize autoDismissWhenCompelted=_autoDismissWhenCompelted;
@property(nonatomic) _Bool autoPushViewController; // @synthesize autoPushViewController=_autoPushViewController;
@property(copy, nonatomic) CDUnknownBlockType callbackBlock; // @synthesize callbackBlock=_callbackBlock;
@property(nonatomic) UIViewController *sourceController; // @synthesize sourceController=_sourceController;
- (void).cxx_destruct;
- (void)notifyResult:(id)arg1 error:(id)arg2 controller:(id)arg3;
- (void)onComponent:(id)arg1 result:(id)arg2 error:(id)arg3;
- (void)showComponent;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

