//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, TuSDKConfig;

@interface TuSDKAOValid : NSObject
{
    NSArray *_privateKeys;
    NSString *_appKey;
    _Bool _isLsqDevValid;
    NSString *_devType;
    TuSDKConfig *_lsqSDKConfig;
    TuSDKConfig *_lsqPermissionConfig;
    NSString *_developerId;
}

+ (id)shared;
@property(readonly, nonatomic) NSString *developerId; // @synthesize developerId=_developerId;
- (void).cxx_destruct;
- (void)initValid;
- (void)onResponseConfiguration:(id)arg1 arg:(id)arg2;
- (void)fetchConfigFromService;
- (id)loadSdkConfigFromKeychain;
- (_Bool)keychainConfigEnable;
- (id)encryptResWithIndex:(unsigned long long)arg1 type:(unsigned long long)arg2 resId:(unsigned long long)arg3 resType:(unsigned long long)arg4;
- (_Bool)validResWithKey:(id)arg1 type:(unsigned long long)arg2 resId:(unsigned long long)arg3 resType:(unsigned long long)arg4;
- (_Bool)brushValidWithKey:(id)arg1 type:(unsigned long long)arg2 brushId:(unsigned long long)arg3;
- (_Bool)brushValidWithID:(unsigned long long)arg1 type:(unsigned long long)arg2;
- (_Bool)stickerValidWithKey:(id)arg1 type:(unsigned long long)arg2 stickerId:(unsigned long long)arg3;
- (_Bool)stickerValidWithID:(unsigned long long)arg1 type:(unsigned long long)arg2;
- (id)brushVaildKeyWithID:(unsigned long long)arg1;
- (id)stickerVaildKeyWithID:(unsigned long long)arg1;
- (_Bool)filterAPIValidWithID:(unsigned long long)arg1;
- (_Bool)videoFilterValidWithKey:(id)arg1 type:(unsigned long long)arg2 filterId:(unsigned long long)arg3;
- (_Bool)videoFilterValidWithID:(unsigned long long)arg1 type:(unsigned long long)arg2;
- (_Bool)filterValidWithKey:(id)arg1 type:(unsigned long long)arg2 filterId:(unsigned long long)arg3;
- (_Bool)filterValidWithID:(unsigned long long)arg1 type:(unsigned long long)arg2;
- (id)filterVaildKeyWithID:(unsigned long long)arg1;
- (id)sdkPublicTextKey:(id)arg1 type:(unsigned long long)arg2 appkey:(id)arg3;
- (id)sdkDecodeWithData:(id)arg1 key:(id)arg2 type:(unsigned long long)arg3;
- (id)sdkDecodeWithString:(id)arg1 appkey:(id)arg2;
- (id)sdkDecodeWithString:(id)arg1;
- (void)loadSdkConfigWithDevType:(id)arg1;
- (_Bool)_sdkValid;
- (_Bool)sdkValid;
- (_Bool)filterAPIEnabled;
- (_Bool)faceLocalBeautySupport;
- (_Bool)faceLocalVideoSupport;
- (_Bool)faceLocalImageSupport;
- (unsigned long long)faceLocalMarks;
- (_Bool)videoStreamEnabled;
- (_Bool)videoEditEnabled;
- (_Bool)videoDurationEnabled;
- (_Bool)videoRecordEnabled;
- (unsigned long long)beautyLevel;
- (_Bool)hdrFilterEnabled;
- (_Bool)wipeFilterEnabled;
- (_Bool)smudgeEnabled;
- (_Bool)renderFilterThumb;
- (_Bool)noPower;
- (_Bool)serviceExpire;
- (unsigned long long)localStickerCount;
- (unsigned long long)localFilterCount;
- (unsigned long long)maxStickers;
- (double)maxImageSide;
- (_Bool)allowLevel:(unsigned long long)arg1;
- (_Bool)sdkValidWithKey:(id)arg1 devType:(id)arg2;
- (id)buildValidKeyWithLevel:(long long)arg1;
- (id)buildWithAppIdentify:(id)arg1 level:(long long)arg2 devId:(id)arg3 index:(unsigned long long)arg4;
- (id)appIdentify;
- (long long)userType;
@property(readonly, nonatomic, getter=level) long long level;
@property(readonly, nonatomic) TuSDKConfig *sdkConfig;
@property(readonly, nonatomic, getter=isValid) _Bool isValid;
- (id)init;

@end

