//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AVCaptureDevice, NSString, UIColor, UIView;
@protocol TuSDKCPRegionHandler, TuSDKVideoCameraExtendViewInterface, TuSDKVideoCameraSampleBufferDelegate;

@protocol TuSDKVideoCameraInterface <NSObject>
@property(readonly, nonatomic) double supportMaxFocalDistanceScale;
@property(nonatomic) double focalDistanceScale;
@property(nonatomic) _Bool enableFocalDistance;
@property(nonatomic) _Bool enableFaceDetection;
@property(nonatomic) struct CGSize outputSize;
@property(retain, nonatomic) id <TuSDKCPRegionHandler> regionHandler;
@property(nonatomic) _Bool displayGuideLine;
@property(retain, nonatomic) UIColor *regionViewColor;
@property(nonatomic) double cameraViewRatio;
@property(nonatomic) double longTouchDelay;
@property(nonatomic) double autoFoucsDelay;
@property(nonatomic) _Bool disableContinueFoucs;
@property(nonatomic) _Bool enableLongTouchCapture;
@property(nonatomic) _Bool enableFilterConfig;
@property(readonly, nonatomic) long long state;
@property(nonatomic) _Bool disableMirrorFrontFacing;
@property(nonatomic) _Bool horizontallyMirrorRearFacingCamera;
@property(nonatomic) _Bool horizontallyMirrorFrontFacingCamera;
@property(readonly, getter=isBackFacingCameraPresent) _Bool backFacingCameraPresent;
@property(readonly, getter=isFrontFacingCameraPresent) _Bool frontFacingCameraPresent;
@property(nonatomic) long long outputImageOrientation;
@property(readonly) AVCaptureDevice *inputCamera;
@property(nonatomic) __weak id <TuSDKVideoCameraSampleBufferDelegate> sampleBufferDelegate;
- (void)destory;
- (_Bool)switchFilterWithCode:(NSString *)arg1;
- (void)tryStartCameraCapture;
- (void)captureImage;
- (void)stopCameraCapture;
- (void)pauseCameraCapture;
- (void)resumeCameraCapture;
- (void)rotateCamera;
- (void)changeCameraViewRatio:(double)arg1;
- (long long)getFlashModel;
- (void)flashWithMode:(long long)arg1;
- (_Bool)hasFlash;
- (void)bindFocusTouchView:(UIView<TuSDKVideoCameraExtendViewInterface> *)arg1;
- (_Bool)isSupportExposureWithMode:(long long)arg1;
- (_Bool)isSupportFocusWithMode:(long long)arg1;
- (long long)cameraPosition;
@end

