//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKICTableView.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSString;
@protocol TuSDKPFAlbumPopListProtocol;

@interface TuSDKPFAlbumPopList : TuSDKICTableView <UITableViewDataSource, UITableViewDelegate>
{
    _Bool _stateHidden;
    Class _cellViewClazz;
    NSArray *_groups;
    id <TuSDKPFAlbumPopListProtocol> _groupProtocol;
}

@property(nonatomic) id <TuSDKPFAlbumPopListProtocol> groupProtocol; // @synthesize groupProtocol=_groupProtocol;
@property(nonatomic) _Bool stateHidden; // @synthesize stateHidden=_stateHidden;
@property(retain, nonatomic) NSArray *groups; // @synthesize groups=_groups;
@property(retain, nonatomic) Class cellViewClazz; // @synthesize cellViewClazz=_cellViewClazz;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)selectGroup:(id)arg1;
- (void)updateOriginY;
- (void)toggleGroupShowState;
- (void)lsqInitView;
- (void)setRowHeight:(double)arg1;
- (double)rowHeight;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

