//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TuSDKPFEditTextColorAdjustDelegate-Protocol.h"
#import "TuSDKPFEditTextStyleAdjustDelegate-Protocol.h"
#import "TuSDKPFTextViewDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class NSMutableParagraphStyle, NSString, TuSDKICMaskRegionView, TuSDKPFEditAdjustOptionBar, TuSDKPFEditTextBottomBar, TuSDKPFEditTextColorAdjustView, TuSDKPFEditTextStyleAdjustView, TuSDKPFEditTextViewOptions, TuSDKPFTextView, UIButton, UIColor, UIImageView, UITextView;

@interface TuSDKPFEditTextView : UIView <UITextViewDelegate, TuSDKPFEditTextColorAdjustDelegate, TuSDKPFEditTextStyleAdjustDelegate, TuSDKPFTextViewDelegate>
{
    UIImageView *_imageView;
    TuSDKPFEditTextBottomBar *_bottomBar;
    TuSDKPFTextView *_textView;
    TuSDKICMaskRegionView *_cutRegionView;
    TuSDKPFEditAdjustOptionBar *_optionBar;
    UIButton *_optionBackButton;
    UIView *_optionActionContainer;
    UIColor *_textColor;
    UITextView *_textInputView;
    UIView *_optionEnterBackView;
    TuSDKPFEditTextColorAdjustView *_colorAdjustView;
    TuSDKPFEditTextStyleAdjustView *_styleAdjustView;
    UIView *_imageBackView;
    NSMutableParagraphStyle *_textParaStyle;
    struct CGPoint _itemCenter;
    TuSDKPFEditTextViewOptions *_textOptions;
}

@property(retain, nonatomic) TuSDKPFEditTextViewOptions *textOptions; // @synthesize textOptions=_textOptions;
@property(readonly, nonatomic) UIButton *optionBackButton; // @synthesize optionBackButton=_optionBackButton;
@property(readonly, nonatomic) TuSDKPFEditAdjustOptionBar *optionBar; // @synthesize optionBar=_optionBar;
@property(readonly, nonatomic) TuSDKPFEditTextBottomBar *bottomBar; // @synthesize bottomBar=_bottomBar;
@property(readonly, nonatomic) TuSDKPFTextView *textView; // @synthesize textView=_textView;
@property(readonly, nonatomic) TuSDKICMaskRegionView *cutRegionView; // @synthesize cutRegionView=_cutRegionView;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)dealloc;
- (void)textViewDidChange:(id)arg1;
- (void)onSelectStyle:(unsigned long long)arg1;
- (void)onSelectColorWith:(id)arg1 styleType:(unsigned long long)arg2;
- (void)deleteSelectedItem;
- (_Bool)canCancelAllSelected;
- (void)switchSelectedItem:(id)arg1 itemCenter:(struct CGPoint)arg2;
- (void)clickToEnterEvent:(id)arg1 itemCenter:(struct CGPoint)arg2;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)selectedIndexWith:(long long)arg1;
- (void)setOptionViewHiddenState:(_Bool)arg1;
- (void)setImage:(id)arg1;
- (void)appendTextWithOption:(id)arg1;
- (void)initEventMethod;
- (void)initOptionEnterView;
- (void)initOptionConfigView;
- (void)lsqInitView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

