//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKICEmptyView.h"

@class UIButton, UILabel;

@interface TuSDKPFStickerLocalEmptyView : TuSDKICEmptyView
{
    UILabel *_msgView;
    UIButton *_moreButton;
}

@property(readonly, nonatomic) UIButton *moreButton; // @synthesize moreButton=_moreButton;
@property(readonly, nonatomic) UILabel *msgView; // @synthesize msgView=_msgView;
- (void).cxx_destruct;
- (void)resetFrame:(struct CGRect)arg1;
- (void)lsqInitView;

@end

