//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIColor;
@protocol TuSDKPFEditTextColorAdjustDelegate;

@interface TuSDKPFEditTextColorAdjustView : UIView
{
    double _itemWidth;
    double _itemHeight;
    double _originY;
    long long _currentColorIndex;
    unsigned long long _currentStyeIndex;
    UIView *_displayView;
    _Bool _defaultClearColor;
    id <TuSDKPFEditTextColorAdjustDelegate> _colorDelegate;
    NSArray *_hexColors;
    NSArray *_styleArr;
    UIColor *_styleSelectedColor;
    UIColor *_styleNormalColor;
    struct UIEdgeInsets _edgeInsets;
}

@property(retain, nonatomic) UIColor *styleNormalColor; // @synthesize styleNormalColor=_styleNormalColor;
@property(retain, nonatomic) UIColor *styleSelectedColor; // @synthesize styleSelectedColor=_styleSelectedColor;
@property(retain, nonatomic) NSArray *styleArr; // @synthesize styleArr=_styleArr;
@property(nonatomic) _Bool defaultClearColor; // @synthesize defaultClearColor=_defaultClearColor;
@property(nonatomic) struct UIEdgeInsets edgeInsets; // @synthesize edgeInsets=_edgeInsets;
@property(retain, nonatomic) NSArray *hexColors; // @synthesize hexColors=_hexColors;
@property(nonatomic) __weak id <TuSDKPFEditTextColorAdjustDelegate> colorDelegate; // @synthesize colorDelegate=_colorDelegate;
- (void).cxx_destruct;
- (void)clickStyleBtnWith:(id)arg1;
- (void)resetDisplayViewCenterWith:(struct CGPoint)arg1 isHidden:(_Bool)arg2;
- (id)getColorAtPointX:(double)arg1;
- (id)getStyleNameWith:(unsigned long long)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)resetStyleView;
- (void)resetColorView;
- (id)init;

@end

