//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKNKDownloadAdapter.h"

@class NSArray, NSMutableArray, NSMutableDictionary, TuSDKConfig;

@interface TuSDKStickerAdapter : TuSDKNKDownloadAdapter
{
    NSMutableArray *_catagories;
    NSMutableDictionary *_groups;
    NSMutableArray *_smartGroups;
    NSMutableDictionary *_stickerDatas;
    TuSDKConfig *_config;
    unsigned long long _total;
    _Bool _isInited;
}

+ (id)initWithConfig:(id)arg1;
@property(readonly, nonatomic) _Bool isInited; // @synthesize isInited=_isInited;
- (void).cxx_destruct;
- (id)allGroupID;
- (_Bool)appenDownloaded:(id)arg1;
- (void)removeDownloadDataWithIdt:(unsigned long long)arg1;
- (_Bool)containsWithGroupId:(unsigned long long)arg1;
- (id)asyncTaskLoadImageWithWare:(id)arg1;
- (void)loadThumbWithStickerGroup:(id)arg1 imageView:(id)arg2;
- (void)loadThumbWithSticker:(id)arg1 imageView:(id)arg2;
- (id)loadSmartSticker:(id)arg1 withResName:(id)arg2;
- (_Bool)loadStickerData:(id)arg1;
- (void)mergerSticker:(id)arg1 toData:(id)arg2;
- (void)mergerGroup:(id)arg1 toGroup:(id)arg2;
- (void)asyncLoadLocalSticker:(id)arg1;
- (void)asyncLoadLocalStickers;
- (void)loadCatagories;
- (id)stickerWithIdt:(unsigned long long)arg1;
- (id)categorieWithIdt:(unsigned long long)arg1;
- (id)getGroupListWithCategoryType:(unsigned long long)arg1;
- (id)categoriesWithCategories:(id)arg1;
@property(readonly, nonatomic) NSArray *categories;
- (id)initWithConfig:(id)arg1;

@end

