//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKDataJson.h"

@class NSString;

@interface TuSDKNKFaceArgument : TuSDKDataJson
{
    NSString *_identify;
    NSString *_bin;
    struct CGPoint _contourLeft1;
    struct CGPoint _contourLeft2;
    struct CGPoint _contourLeft3;
    struct CGPoint _contourLeft4;
    struct CGPoint _contourLeft5;
    struct CGPoint _contourLeft6;
    struct CGPoint _contourLeft7;
    struct CGPoint _contourLeft8;
    struct CGPoint _contourChin;
    struct CGPoint _contourRight1;
    struct CGPoint _contourRight2;
    struct CGPoint _contourRight3;
    struct CGPoint _contourRight4;
    struct CGPoint _contourRight5;
    struct CGPoint _contourRight6;
    struct CGPoint _contourRight7;
    struct CGPoint _contourRight8;
    struct CGPoint _leftBrowLeftCorner;
    struct CGPoint _leftBrowLeftQuarter;
    struct CGPoint _leftBrowMiddle;
    struct CGPoint _leftBrowRightQuarter;
    struct CGPoint _leftBrowRightCorner;
    struct CGPoint _rightBrowLeftCorner;
    struct CGPoint _rightBrowLeftQuarter;
    struct CGPoint _rightBrowMiddle;
    struct CGPoint _rightBrowRightQuarter;
    struct CGPoint _rightBrowRightCorner;
    struct CGPoint _noseTop;
    struct CGPoint _noseUpperMiddle;
    struct CGPoint _noseLowerMiddle;
    struct CGPoint _noseBottom;
    struct CGPoint _noseContourLeftCorner;
    struct CGPoint _noseContourLeftQuarter;
    struct CGPoint _noseContourMiddle;
    struct CGPoint _noseContourRightQuarter;
    struct CGPoint _noseContourRightCorner;
    struct CGPoint _leftEyeLeftCorner;
    struct CGPoint _leftEyeTopLeft;
    struct CGPoint _leftEyeTopRight;
    struct CGPoint _leftEyeRightCorner;
    struct CGPoint _leftEyeBottomRight;
    struct CGPoint _leftEyeBottomLeft;
    struct CGPoint _rightEyeLeftCorner;
    struct CGPoint _rightEyeTopLeft;
    struct CGPoint _rightEyeTopRight;
    struct CGPoint _rightEyeRightCorner;
    struct CGPoint _rightEyeBottomRight;
    struct CGPoint _rightEyeBottomLeft;
    struct CGPoint _mouthLeftCornerContour;
    struct CGPoint _mouthUpperLipContour1;
    struct CGPoint _mouthUpperLipContour2;
    struct CGPoint _mouthUpperLipContour3;
    struct CGPoint _mouthUpperLipContour4;
    struct CGPoint _mouthUpperLipContour5;
    struct CGPoint _mouthRightCornerContour;
    struct CGPoint _mouthLowerLipContour1;
    struct CGPoint _mouthLowerLipContour2;
    struct CGPoint _mouthLowerLipContour3;
    struct CGPoint _mouthLowerLipContour4;
    struct CGPoint _mouthLowerLipContour5;
    struct CGPoint _mouthLeftCorner;
    struct CGPoint _mouthUpperLip1;
    struct CGPoint _mouthUpperLip2;
    struct CGPoint _mouthUpperLip3;
    struct CGPoint _mouthRightCorner;
    struct CGPoint _mouthLowerLip1;
    struct CGPoint _mouthLowerLip2;
    struct CGPoint _mouthLowerLip3;
    struct CGRect _rect;
}

@property(nonatomic) struct CGPoint mouthLowerLip3; // @synthesize mouthLowerLip3=_mouthLowerLip3;
@property(nonatomic) struct CGPoint mouthLowerLip2; // @synthesize mouthLowerLip2=_mouthLowerLip2;
@property(nonatomic) struct CGPoint mouthLowerLip1; // @synthesize mouthLowerLip1=_mouthLowerLip1;
@property(nonatomic) struct CGPoint mouthRightCorner; // @synthesize mouthRightCorner=_mouthRightCorner;
@property(nonatomic) struct CGPoint mouthUpperLip3; // @synthesize mouthUpperLip3=_mouthUpperLip3;
@property(nonatomic) struct CGPoint mouthUpperLip2; // @synthesize mouthUpperLip2=_mouthUpperLip2;
@property(nonatomic) struct CGPoint mouthUpperLip1; // @synthesize mouthUpperLip1=_mouthUpperLip1;
@property(nonatomic) struct CGPoint mouthLeftCorner; // @synthesize mouthLeftCorner=_mouthLeftCorner;
@property(nonatomic) struct CGPoint mouthLowerLipContour5; // @synthesize mouthLowerLipContour5=_mouthLowerLipContour5;
@property(nonatomic) struct CGPoint mouthLowerLipContour4; // @synthesize mouthLowerLipContour4=_mouthLowerLipContour4;
@property(nonatomic) struct CGPoint mouthLowerLipContour3; // @synthesize mouthLowerLipContour3=_mouthLowerLipContour3;
@property(nonatomic) struct CGPoint mouthLowerLipContour2; // @synthesize mouthLowerLipContour2=_mouthLowerLipContour2;
@property(nonatomic) struct CGPoint mouthLowerLipContour1; // @synthesize mouthLowerLipContour1=_mouthLowerLipContour1;
@property(nonatomic) struct CGPoint mouthRightCornerContour; // @synthesize mouthRightCornerContour=_mouthRightCornerContour;
@property(nonatomic) struct CGPoint mouthUpperLipContour5; // @synthesize mouthUpperLipContour5=_mouthUpperLipContour5;
@property(nonatomic) struct CGPoint mouthUpperLipContour4; // @synthesize mouthUpperLipContour4=_mouthUpperLipContour4;
@property(nonatomic) struct CGPoint mouthUpperLipContour3; // @synthesize mouthUpperLipContour3=_mouthUpperLipContour3;
@property(nonatomic) struct CGPoint mouthUpperLipContour2; // @synthesize mouthUpperLipContour2=_mouthUpperLipContour2;
@property(nonatomic) struct CGPoint mouthUpperLipContour1; // @synthesize mouthUpperLipContour1=_mouthUpperLipContour1;
@property(nonatomic) struct CGPoint mouthLeftCornerContour; // @synthesize mouthLeftCornerContour=_mouthLeftCornerContour;
@property(nonatomic) struct CGPoint rightEyeBottomLeft; // @synthesize rightEyeBottomLeft=_rightEyeBottomLeft;
@property(nonatomic) struct CGPoint rightEyeBottomRight; // @synthesize rightEyeBottomRight=_rightEyeBottomRight;
@property(nonatomic) struct CGPoint rightEyeRightCorner; // @synthesize rightEyeRightCorner=_rightEyeRightCorner;
@property(nonatomic) struct CGPoint rightEyeTopRight; // @synthesize rightEyeTopRight=_rightEyeTopRight;
@property(nonatomic) struct CGPoint rightEyeTopLeft; // @synthesize rightEyeTopLeft=_rightEyeTopLeft;
@property(nonatomic) struct CGPoint rightEyeLeftCorner; // @synthesize rightEyeLeftCorner=_rightEyeLeftCorner;
@property(nonatomic) struct CGPoint leftEyeBottomLeft; // @synthesize leftEyeBottomLeft=_leftEyeBottomLeft;
@property(nonatomic) struct CGPoint leftEyeBottomRight; // @synthesize leftEyeBottomRight=_leftEyeBottomRight;
@property(nonatomic) struct CGPoint leftEyeRightCorner; // @synthesize leftEyeRightCorner=_leftEyeRightCorner;
@property(nonatomic) struct CGPoint leftEyeTopRight; // @synthesize leftEyeTopRight=_leftEyeTopRight;
@property(nonatomic) struct CGPoint leftEyeTopLeft; // @synthesize leftEyeTopLeft=_leftEyeTopLeft;
@property(nonatomic) struct CGPoint leftEyeLeftCorner; // @synthesize leftEyeLeftCorner=_leftEyeLeftCorner;
@property(nonatomic) struct CGPoint noseContourRightCorner; // @synthesize noseContourRightCorner=_noseContourRightCorner;
@property(nonatomic) struct CGPoint noseContourRightQuarter; // @synthesize noseContourRightQuarter=_noseContourRightQuarter;
@property(nonatomic) struct CGPoint noseContourMiddle; // @synthesize noseContourMiddle=_noseContourMiddle;
@property(nonatomic) struct CGPoint noseContourLeftQuarter; // @synthesize noseContourLeftQuarter=_noseContourLeftQuarter;
@property(nonatomic) struct CGPoint noseContourLeftCorner; // @synthesize noseContourLeftCorner=_noseContourLeftCorner;
@property(nonatomic) struct CGPoint noseBottom; // @synthesize noseBottom=_noseBottom;
@property(nonatomic) struct CGPoint noseLowerMiddle; // @synthesize noseLowerMiddle=_noseLowerMiddle;
@property(nonatomic) struct CGPoint noseUpperMiddle; // @synthesize noseUpperMiddle=_noseUpperMiddle;
@property(nonatomic) struct CGPoint noseTop; // @synthesize noseTop=_noseTop;
@property(nonatomic) struct CGPoint rightBrowRightCorner; // @synthesize rightBrowRightCorner=_rightBrowRightCorner;
@property(nonatomic) struct CGPoint rightBrowRightQuarter; // @synthesize rightBrowRightQuarter=_rightBrowRightQuarter;
@property(nonatomic) struct CGPoint rightBrowMiddle; // @synthesize rightBrowMiddle=_rightBrowMiddle;
@property(nonatomic) struct CGPoint rightBrowLeftQuarter; // @synthesize rightBrowLeftQuarter=_rightBrowLeftQuarter;
@property(nonatomic) struct CGPoint rightBrowLeftCorner; // @synthesize rightBrowLeftCorner=_rightBrowLeftCorner;
@property(nonatomic) struct CGPoint leftBrowRightCorner; // @synthesize leftBrowRightCorner=_leftBrowRightCorner;
@property(nonatomic) struct CGPoint leftBrowRightQuarter; // @synthesize leftBrowRightQuarter=_leftBrowRightQuarter;
@property(nonatomic) struct CGPoint leftBrowMiddle; // @synthesize leftBrowMiddle=_leftBrowMiddle;
@property(nonatomic) struct CGPoint leftBrowLeftQuarter; // @synthesize leftBrowLeftQuarter=_leftBrowLeftQuarter;
@property(nonatomic) struct CGPoint leftBrowLeftCorner; // @synthesize leftBrowLeftCorner=_leftBrowLeftCorner;
@property(nonatomic) struct CGPoint contourRight8; // @synthesize contourRight8=_contourRight8;
@property(nonatomic) struct CGPoint contourRight7; // @synthesize contourRight7=_contourRight7;
@property(nonatomic) struct CGPoint contourRight6; // @synthesize contourRight6=_contourRight6;
@property(nonatomic) struct CGPoint contourRight5; // @synthesize contourRight5=_contourRight5;
@property(nonatomic) struct CGPoint contourRight4; // @synthesize contourRight4=_contourRight4;
@property(nonatomic) struct CGPoint contourRight3; // @synthesize contourRight3=_contourRight3;
@property(nonatomic) struct CGPoint contourRight2; // @synthesize contourRight2=_contourRight2;
@property(nonatomic) struct CGPoint contourRight1; // @synthesize contourRight1=_contourRight1;
@property(nonatomic) struct CGPoint contourChin; // @synthesize contourChin=_contourChin;
@property(nonatomic) struct CGPoint contourLeft8; // @synthesize contourLeft8=_contourLeft8;
@property(nonatomic) struct CGPoint contourLeft7; // @synthesize contourLeft7=_contourLeft7;
@property(nonatomic) struct CGPoint contourLeft6; // @synthesize contourLeft6=_contourLeft6;
@property(nonatomic) struct CGPoint contourLeft5; // @synthesize contourLeft5=_contourLeft5;
@property(nonatomic) struct CGPoint contourLeft4; // @synthesize contourLeft4=_contourLeft4;
@property(nonatomic) struct CGPoint contourLeft3; // @synthesize contourLeft3=_contourLeft3;
@property(nonatomic) struct CGPoint contourLeft2; // @synthesize contourLeft2=_contourLeft2;
@property(nonatomic) struct CGPoint contourLeft1; // @synthesize contourLeft1=_contourLeft1;
@property(nonatomic) struct CGRect rect; // @synthesize rect=_rect;
@property(retain, nonatomic) NSString *bin; // @synthesize bin=_bin;
@property(retain, nonatomic) NSString *identify; // @synthesize identify=_identify;
- (void).cxx_destruct;
- (struct CGPoint)parsePointWithValue:(id)arg1;
- (void)deserializationWithJson:(id)arg1;

@end

