//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TuSDKCPParameterConfigViewInterface-Protocol.h"
#import "TuSDKICSeekBarDelegate-Protocol.h"

@class NSMutableArray, NSString, TuSDKICSeekBar, UIButton, UILabel;
@protocol TuSDKCPParameterConfigDelegate;

@interface TuSDKCPParameterConfigView : UIView <TuSDKICSeekBarDelegate, TuSDKCPParameterConfigViewInterface>
{
    UIView *_paramsView;
    UIButton *_restButton;
    UILabel *_numberView;
    TuSDKICSeekBar *_seekBar;
    NSMutableArray *_mParamViews;
    unsigned long long _mCurrentIndex;
    UIView *_seekWrapView;
    id <TuSDKCPParameterConfigDelegate> _delegate;
}

@property(readonly, nonatomic) TuSDKICSeekBar *seekBar; // @synthesize seekBar=_seekBar;
@property(readonly, nonatomic) UILabel *numberView; // @synthesize numberView=_numberView;
@property(readonly, nonatomic) UIButton *restButton; // @synthesize restButton=_restButton;
@property(readonly, nonatomic) UIView *paramsView; // @synthesize paramsView=_paramsView;
@property(nonatomic) __weak id <TuSDKCPParameterConfigDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)selectWithIndex:(unsigned long long)arg1;
- (void)onParamSelected:(id)arg1;
- (id)createParamViewWithKey:(id)arg1 frame:(struct CGRect)arg2;
- (void)setParams:(id)arg1 selectedIndex:(unsigned long long)arg2;
- (void)onTuSDKICSeekBar:(id)arg1 changedProgress:(double)arg2;
- (void)handleRestAction;
- (void)seekWithProgress:(double)arg1;
- (void)setTitleWithProgress:(double)arg1;
- (void)lsqInitView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

