//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, UIImage, UIImageView;

@protocol TuSDKTKFiltersTaskInterface <NSObject>
@property(nonatomic) _Bool isRenderFilterThumb;
@property(readonly, nonatomic) _Bool taskCompleted;
@property(retain, nonatomic) UIImage *inputImage;
@property(retain, nonatomic) NSArray *filerNames;
- (void)cancelLoadImageWithView:(UIImageView *)arg1;
- (void)loadImageWithView:(UIImageView *)arg1 filterName:(NSString *)arg2;
- (void)appendFilterCode:(NSString *)arg1;
- (void)resetQueues;
- (void)start;
@end

