//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImageFilterGroup.h"

#import "TuSDKFilterFacePositionProtocol-Protocol.h"
#import "TuSDKFilterParameterProtocol-Protocol.h"
#import "TuSDKFilterTexturesProtocol-Protocol.h"

@class NSString, TuSDKFilter, TuSDKFilterParameter, TuSDKGPUColorMixedFilter, TuSDKGPUSurfaceBlurFilter, _TuSDKGPUFaceFilter, _TuSDKGPUSkinFilter;

@interface TuSDKGPUSkinWhiteningFilter : GPUImageFilterGroup <TuSDKFilterParameterProtocol, TuSDKFilterTexturesProtocol, TuSDKFilterFacePositionProtocol>
{
    TuSDKGPUColorMixedFilter *_colorFilter;
    TuSDKGPUSurfaceBlurFilter *_blurFilter;
    TuSDKFilter *_gaussianFilter;
    _TuSDKGPUSkinFilter *_skinFilter;
    _TuSDKGPUFaceFilter *_faceBeautyFilter;
    TuSDKFilterParameter *_parameter;
    double _smoothing;
    double _whitening;
    double _skinColor;
    double _eyeSize;
    double _chinSize;
    double _retouch;
}

@property(nonatomic) double retouch; // @synthesize retouch=_retouch;
@property(nonatomic) double chinSize; // @synthesize chinSize=_chinSize;
@property(nonatomic) double eyeSize; // @synthesize eyeSize=_eyeSize;
@property(nonatomic) double skinColor; // @synthesize skinColor=_skinColor;
@property(nonatomic) double whitening; // @synthesize whitening=_whitening;
@property(nonatomic) double smoothing; // @synthesize smoothing=_smoothing;
- (void).cxx_destruct;
- (void)submitParameter:(id)arg1;
- (void)submitParameter;
@property(retain, nonatomic) TuSDKFilterParameter *parameter; // @synthesize parameter=_parameter;
- (void)submitFilterArg:(id)arg1;
- (id)configParams:(id)arg1;
- (void)resetPosition;
- (void)updateFaceFeatures:(id)arg1 angle:(float)arg2;
- (void)appendTextures:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

