//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol TuSDKICMessageHubInterface;

@interface TuSDK : NSObject
{
    _Bool _isInited;
    _Bool _useSSL;
    NSString *_style;
    NSString *_userIdentify;
    id <TuSDKICMessageHubInterface> _messageHub;
}

+ (id)cameraWithSessionPreset:(id)arg1 cameraPosition:(long long)arg2 cameraView:(id)arg3;
+ (void)checkManagerWithDelegate:(id)arg1;
+ (id)stickerManager;
+ (id)filterManager;
+ (id)filterCodes;
+ (id)appDownloadPath;
+ (id)appTempPath;
+ (void)setLogLevel:(long long)arg1;
+ (void)initSdkWithAppKey:(id)arg1 devType:(id)arg2;
+ (void)initSdkWithAppKey:(id)arg1;
+ (id)shared;
@property(nonatomic) _Bool useSSL; // @synthesize useSSL=_useSSL;
@property(retain, nonatomic) id <TuSDKICMessageHubInterface> messageHub; // @synthesize messageHub=_messageHub;
@property(copy, nonatomic) NSString *userIdentify; // @synthesize userIdentify=_userIdentify;
@property(copy, nonatomic) NSString *style; // @synthesize style=_style;
- (void).cxx_destruct;
- (void)initSdk;
- (id)init;

@end

