//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPComponentErrorDelegate-Protocol.h"

@class TuSDKPFCameraViewController, TuSDKResult;

@protocol TuSDKPFCameraDelegate <TuSDKCPComponentErrorDelegate>
- (void)onTuSDKPFCamera:(TuSDKPFCameraViewController *)arg1 captureResult:(TuSDKResult *)arg2;

@optional
- (void)onTuSDKAlbumDemand:(TuSDKPFCameraViewController *)arg1;
- (_Bool)onAsyncTuSDKPFCamera:(TuSDKPFCameraViewController *)arg1 captureResult:(TuSDKResult *)arg2;
@end

