//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPResultOptions.h"

@class NSArray, NSString, TuSDKWaterMarkOption, UIColor;

@interface TuSDKPFCameraOptions : TuSDKCPResultOptions
{
    _Bool _enableFilters;
    _Bool _showFilterDefault;
    _Bool _enableFilterHistory;
    _Bool _enableNormalFilter;
    _Bool _enableOnlineFilter;
    _Bool _displayFilterSubtitles;
    _Bool _saveLastFilter;
    _Bool _autoSelectGroupDefaultFilter;
    _Bool _enableFilterConfig;
    _Bool _enableLongTouchCapture;
    _Bool _disableContinueFoucs;
    _Bool _disableMirrorFrontFacing;
    _Bool _displayAlbumPoster;
    _Bool _displayGuideLine;
    _Bool _enableFaceDetection;
    _Bool _enableCaptureWithVolumeKeys;
    _Bool _enableFocalDistance;
    Class _viewClazz;
    Class _configBarViewClazz;
    Class _bottomBarViewClazz;
    Class _flashViewClazz;
    Class _filterViewClazz;
    Class _focusTouchViewClazz;
    long long _cameraPostion;
    long long _cameraDefaultFlashMode;
    NSString *_sessionPreset;
    Class _onlineControllerClazz;
    double _filterBarCellWidth;
    double _filterBarHeight;
    Class _filterBarGroupCellClazz;
    Class _filterBarTableCellClazz;
    NSArray *_filterGroup;
    double _cameraViewRatio;
    long long _ratioType;
    double _autoFoucsDelay;
    double _longTouchDelay;
    UIColor *_regionViewColor;
    TuSDKWaterMarkOption *_waterMarkOption;
    double _focalDistanceScale;
    struct CGSize _outputSize;
}

@property(nonatomic) double focalDistanceScale; // @synthesize focalDistanceScale=_focalDistanceScale;
@property(nonatomic) _Bool enableFocalDistance; // @synthesize enableFocalDistance=_enableFocalDistance;
@property(nonatomic) _Bool enableCaptureWithVolumeKeys; // @synthesize enableCaptureWithVolumeKeys=_enableCaptureWithVolumeKeys;
@property(retain, nonatomic) TuSDKWaterMarkOption *waterMarkOption; // @synthesize waterMarkOption=_waterMarkOption;
@property(nonatomic) _Bool enableFaceDetection; // @synthesize enableFaceDetection=_enableFaceDetection;
@property(nonatomic) _Bool displayGuideLine; // @synthesize displayGuideLine=_displayGuideLine;
@property(nonatomic) _Bool displayAlbumPoster; // @synthesize displayAlbumPoster=_displayAlbumPoster;
@property(nonatomic) _Bool disableMirrorFrontFacing; // @synthesize disableMirrorFrontFacing=_disableMirrorFrontFacing;
@property(nonatomic) struct CGSize outputSize; // @synthesize outputSize=_outputSize;
@property(retain, nonatomic) UIColor *regionViewColor; // @synthesize regionViewColor=_regionViewColor;
@property(nonatomic) double longTouchDelay; // @synthesize longTouchDelay=_longTouchDelay;
@property(nonatomic) double autoFoucsDelay; // @synthesize autoFoucsDelay=_autoFoucsDelay;
@property(nonatomic) _Bool disableContinueFoucs; // @synthesize disableContinueFoucs=_disableContinueFoucs;
@property(nonatomic) _Bool enableLongTouchCapture; // @synthesize enableLongTouchCapture=_enableLongTouchCapture;
@property(nonatomic) long long ratioType; // @synthesize ratioType=_ratioType;
@property(nonatomic) double cameraViewRatio; // @synthesize cameraViewRatio=_cameraViewRatio;
@property(nonatomic) _Bool enableFilterConfig; // @synthesize enableFilterConfig=_enableFilterConfig;
@property(nonatomic) _Bool autoSelectGroupDefaultFilter; // @synthesize autoSelectGroupDefaultFilter=_autoSelectGroupDefaultFilter;
@property(nonatomic) _Bool saveLastFilter; // @synthesize saveLastFilter=_saveLastFilter;
@property(retain, nonatomic) NSArray *filterGroup; // @synthesize filterGroup=_filterGroup;
@property(retain, nonatomic) Class filterBarTableCellClazz; // @synthesize filterBarTableCellClazz=_filterBarTableCellClazz;
@property(retain, nonatomic) Class filterBarGroupCellClazz; // @synthesize filterBarGroupCellClazz=_filterBarGroupCellClazz;
@property(nonatomic) double filterBarHeight; // @synthesize filterBarHeight=_filterBarHeight;
@property(nonatomic) double filterBarCellWidth; // @synthesize filterBarCellWidth=_filterBarCellWidth;
@property(nonatomic) _Bool displayFilterSubtitles; // @synthesize displayFilterSubtitles=_displayFilterSubtitles;
@property(retain, nonatomic) Class onlineControllerClazz; // @synthesize onlineControllerClazz=_onlineControllerClazz;
@property(nonatomic) _Bool enableOnlineFilter; // @synthesize enableOnlineFilter=_enableOnlineFilter;
@property(nonatomic) _Bool enableNormalFilter; // @synthesize enableNormalFilter=_enableNormalFilter;
@property(nonatomic) _Bool enableFilterHistory; // @synthesize enableFilterHistory=_enableFilterHistory;
@property(nonatomic) _Bool showFilterDefault; // @synthesize showFilterDefault=_showFilterDefault;
@property(nonatomic) _Bool enableFilters; // @synthesize enableFilters=_enableFilters;
@property(copy, nonatomic) NSString *sessionPreset; // @synthesize sessionPreset=_sessionPreset;
@property(nonatomic) long long cameraDefaultFlashMode; // @synthesize cameraDefaultFlashMode=_cameraDefaultFlashMode;
@property(nonatomic) long long cameraPostion; // @synthesize cameraPostion=_cameraPostion;
@property(retain, nonatomic) Class focusTouchViewClazz; // @synthesize focusTouchViewClazz=_focusTouchViewClazz;
@property(retain, nonatomic) Class filterViewClazz; // @synthesize filterViewClazz=_filterViewClazz;
@property(retain, nonatomic) Class flashViewClazz; // @synthesize flashViewClazz=_flashViewClazz;
@property(retain, nonatomic) Class bottomBarViewClazz; // @synthesize bottomBarViewClazz=_bottomBarViewClazz;
@property(retain, nonatomic) Class configBarViewClazz; // @synthesize configBarViewClazz=_configBarViewClazz;
@property(retain, nonatomic) Class viewClazz; // @synthesize viewClazz=_viewClazz;
- (void).cxx_destruct;
- (id)viewController;
- (Class)defaultComponentClazz;
- (void)initOptions;

@end

