//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPImageResultOptions.h"

@class NSArray;

@interface TuSDKPFEditTurnAndCutOptions : TuSDKCPImageResultOptions
{
    _Bool _enableFilters;
    _Bool _enableFilterHistory;
    _Bool _enableOnlineFilter;
    _Bool _displayFilterSubtitles;
    _Bool _isRenderFilterThumb;
    Class _viewClazz;
    Class _bottomBarViewClazz;
    Class _editImageViewClazz;
    Class _filterViewClazz;
    Class _onlineControllerClazz;
    NSArray *_filterGroup;
    double _filterBarCellWidth;
    double _filterBarHeight;
    Class _filterBarGroupCellClazz;
    Class _filterBarTableCellClazz;
    struct CGSize _cutSize;
}

@property(nonatomic) _Bool isRenderFilterThumb; // @synthesize isRenderFilterThumb=_isRenderFilterThumb;
@property(nonatomic) struct CGSize cutSize; // @synthesize cutSize=_cutSize;
@property(retain, nonatomic) Class filterBarTableCellClazz; // @synthesize filterBarTableCellClazz=_filterBarTableCellClazz;
@property(retain, nonatomic) Class filterBarGroupCellClazz; // @synthesize filterBarGroupCellClazz=_filterBarGroupCellClazz;
@property(nonatomic) double filterBarHeight; // @synthesize filterBarHeight=_filterBarHeight;
@property(nonatomic) double filterBarCellWidth; // @synthesize filterBarCellWidth=_filterBarCellWidth;
@property(retain, nonatomic) NSArray *filterGroup; // @synthesize filterGroup=_filterGroup;
@property(retain, nonatomic) Class onlineControllerClazz; // @synthesize onlineControllerClazz=_onlineControllerClazz;
@property(nonatomic) _Bool displayFilterSubtitles; // @synthesize displayFilterSubtitles=_displayFilterSubtitles;
@property(nonatomic) _Bool enableOnlineFilter; // @synthesize enableOnlineFilter=_enableOnlineFilter;
@property(nonatomic) _Bool enableFilterHistory; // @synthesize enableFilterHistory=_enableFilterHistory;
@property(nonatomic) _Bool enableFilters; // @synthesize enableFilters=_enableFilters;
@property(retain, nonatomic) Class filterViewClazz; // @synthesize filterViewClazz=_filterViewClazz;
@property(retain, nonatomic) Class editImageViewClazz; // @synthesize editImageViewClazz=_editImageViewClazz;
@property(retain, nonatomic) Class bottomBarViewClazz; // @synthesize bottomBarViewClazz=_bottomBarViewClazz;
@property(retain, nonatomic) Class viewClazz; // @synthesize viewClazz=_viewClazz;
- (void).cxx_destruct;
- (id)viewController;
- (Class)defaultComponentClazz;

@end

