//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class TuSDKPFPhotosGridPreview, UIButton;

@interface TuSDKPFPhotoPreview : UIView
{
    UIButton *_backButton;
    UIButton *_selectButton;
    UIButton *_completeButton;
    Class _photosViewClazz;
    TuSDKPFPhotosGridPreview *_photosView;
    UIView *_topBar;
    UIButton *_selectView;
    UIView *_bottomBar;
}

@property(retain, nonatomic) UIView *bottomBar; // @synthesize bottomBar=_bottomBar;
@property(retain, nonatomic) UIButton *selectView; // @synthesize selectView=_selectView;
@property(retain, nonatomic) UIView *topBar; // @synthesize topBar=_topBar;
@property(retain, nonatomic) UIButton *completeButton; // @synthesize completeButton=_completeButton;
@property(retain, nonatomic) UIButton *selectButton; // @synthesize selectButton=_selectButton;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) TuSDKPFPhotosGridPreview *photosView; // @synthesize photosView=_photosView;
@property(retain, nonatomic) Class photosViewClazz; // @synthesize photosViewClazz=_photosViewClazz;
- (void).cxx_destruct;
- (void)reloadViewDownloading:(_Bool)arg1;
- (void)toggleToolBarState;
- (void)setCompleteButtonTitle:(id)arg1;
- (void)setBackButtonTitle:(id)arg1;
- (double)barHeight;
- (void)configTopBar;
- (void)setSelectButtonTitle:(id)arg1;
- (void)configBottomBar;
- (void)lsqInitView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

