//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TuSDKTSAssetInterface-Protocol.h"

@class NSDate, NSDictionary, NSString, PHAsset, UIImage;

@interface TuSDKTSPHAsset : NSObject <TuSDKTSAssetInterface>
{
    PHAsset *_asset;
    struct CGSize _thumbnailSize;
    int _requestId;
}

+ (id)initWithPHAsset:(id)arg1;
@property(readonly, nonatomic) PHAsset *asset; // @synthesize asset=_asset;
- (void).cxx_destruct;
- (void)loadMetadataWithBlock:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) NSDictionary *metadata;
@property(readonly, nonatomic) struct CGSize fullResolutionImageSize;
- (id)optionsWithSynchronous:(_Bool)arg1 resizeMode:(long long)arg2;
- (void)cancelLoadImageWithSize:(struct CGSize)arg1 synchronous:(_Bool)arg2 resizeMode:(long long)arg3;
- (int)asyncLoadImageWithSize:(struct CGSize)arg1 resizeMode:(long long)arg2 handler:(CDUnknownBlockType)arg3;
- (int)loadImageWithSize:(struct CGSize)arg1 contentMode:(long long)arg2 synchronous:(_Bool)arg3 resizeMode:(long long)arg4 handler:(CDUnknownBlockType)arg5;
- (void)cancelLoadImageWithPixelSize:(struct CGSize)arg1;
- (void)loadImageWithPixelSize:(struct CGSize)arg1 completed:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) UIImage *fullScreenImage;
- (void)cancelLoadFullResolutionImage;
- (void)asyncFullResolutionImage:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) UIImage *fullResolutionImage;
@property(readonly, nonatomic) UIImage *thumbnailImage;
@property(readonly, nonatomic) long long imageOrientation;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) NSString *localIdentifier;
@property(readonly, nonatomic) NSDate *creationDate;
- (void)initPHAsset;
- (id)initWithPHAsset:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

