//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;

@interface TuSDKPFCameraBottomView : UIView
{
    UIButton *_captureButton;
    UIButton *_filterButton;
    UIButton *_albumPoster;
}

@property(readonly, nonatomic) UIButton *albumPoster; // @synthesize albumPoster=_albumPoster;
@property(readonly, nonatomic) UIButton *filterButton; // @synthesize filterButton=_filterButton;
@property(readonly, nonatomic) UIButton *captureButton; // @synthesize captureButton=_captureButton;
- (void).cxx_destruct;
- (void)buildAlbumButton;
- (void)buildFilterButton;
- (id)lsqSetSizeHeight:(double)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)lsqInitView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

