//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TuSDKCPOptions : NSObject
{
    Class _componentClazz;
}

+ (id)build;
- (void).cxx_destruct;
- (id)componentInstance;
@property(retain, nonatomic) Class componentClazz; // @synthesize componentClazz=_componentClazz;
- (Class)defaultComponentClazz;
- (void)initOptions;
- (id)init;

@end

