//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TuSDKFilterGroup, TuSDKFilterOption;

@interface TuSDKCPGroupFilterItem : NSObject
{
    _Bool _isInActingType;
    _Bool _isSelected;
    long long _type;
    TuSDKFilterOption *_option;
    TuSDKFilterGroup *_group;
}

+ (id)initWithGroup:(id)arg1;
+ (id)initWithOption:(id)arg1;
+ (id)initWithType:(long long)arg1;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(nonatomic) _Bool isInActingType; // @synthesize isInActingType=_isInActingType;
@property(retain, nonatomic) TuSDKFilterGroup *group; // @synthesize group=_group;
@property(retain, nonatomic) TuSDKFilterOption *option; // @synthesize option=_option;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)filterCode;

@end

