//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class TuSDKCPGroupFilterGroupCellBase, TuSDKCPGroupFilterItem, UITableViewCell;
@protocol TuSDKCPGroupFilterItemCellInterface;

@protocol TuSDKCPGroupFilterGroupCellDelegate <NSObject>
- (void)onFilterGroupViewClick:(UITableViewCell<TuSDKCPGroupFilterItemCellInterface> *)arg1 mode:(TuSDKCPGroupFilterItem *)arg2 enableStack:(_Bool)arg3;
- (void)onFilterGroupCellRemove:(TuSDKCPGroupFilterGroupCellBase *)arg1;
- (void)onFilterGroupCellLongClick:(TuSDKCPGroupFilterGroupCellBase *)arg1;
@end

