//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol OS_dispatch_queue;

@interface TuSDKLiveStickerManager : NSObject
{
    NSObject<OS_dispatch_queue> *_loadQueue;
    NSMutableArray *_stickerImages;
    NSMutableArray *_imageCachePool;
    NSMutableArray *_stickers;
    _Bool _stickerGroupUsed;
}

+ (id)sharedLoadQueue;
+ (id)shared;
- (void).cxx_destruct;
- (void)dealloc;
- (id)getCachedStickerImage;
- (id)getStickerImageBy:(id)arg1;
- (unsigned long long)stickerCount;
- (id)getStickers;
- (void)startStickersFromFirstFrame;
- (void)removeAllStickers;
- (_Bool)isStickerGroupExists:(id)arg1;
- (_Bool)showStickerGroup:(id)arg1;
- (void)removeSticker:(id)arg1;
- (_Bool)isStickerExists:(id)arg1;
- (_Bool)addSticker:(id)arg1;
- (id)loadQueue;
- (id)init;

@end

