//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKGPUImageFourInputFilter.h"

@class GPUImageFramebuffer;

@interface TuSDKGPUImageFiveInputFilter : TuSDKGPUImageFourInputFilter
{
    GPUImageFramebuffer *fiveInputFramebuffer;
    int filterFifthTextureCoordinateAttribute;
    int filterInputTextureUniform5;
    unsigned long long inputRotation5;
    unsigned int filterSourceTexture5;
    CDStruct_1b6d18a9 fifthFrameTime;
    _Bool hasSetFourthTexture;
    _Bool hasReceivedFifthFrame;
    _Bool fifthFrameWasVideo;
    _Bool fifthFrameCheckDisabled;
}

- (void).cxx_destruct;
- (_Bool)newFrameReadyAtTimeHook:(long long)arg1 frameTime:(CDStruct_1b6d18a9)arg2;
- (void)newFrameReadyAtTimeHookReceivedFramesAtIndex:(long long)arg1;
- (void)newFrameReadyAtTimeHookAllReceivedFrames:(_Bool)arg1;
- (_Bool)newFrameReadyAtTimeHasReceivedHook;
- (unsigned long long)rotatedSizeHook:(long long)arg1;
- (void)setInputRotation:(unsigned long long)arg1 atIndex:(long long)arg2;
- (void)setInputSize:(struct CGSize)arg1 atIndex:(long long)arg2;
- (void)setInputFramebuffer:(id)arg1 atIndex:(long long)arg2;
- (long long)nextAvailableTextureIndex;
- (void)renderToTextureglVertexAttribPointerHook;
- (void)renderToTextureglABUHook;
- (void)unlockInputFramebuffer;
- (void)disableFifthFrameCheck;
- (void)initializeAttributes;
- (id)initWithVertexShaderFromString:(id)arg1 fragmentShaderFromString:(id)arg2;
- (id)initWithFragmentShaderFromString:(id)arg1;

@end

