//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPImageResultOptions.h"

@class NSArray;

@interface TuSDKPFEditFilterOptions : TuSDKCPImageResultOptions
{
    _Bool _enableFilterConfig;
    _Bool _enableFilterHistory;
    _Bool _enableNormalFilter;
    _Bool _enableOnlineFilter;
    _Bool _displayFilterSubtitles;
    _Bool _onlyReturnFilter;
    _Bool _isRenderFilterThumb;
    Class _viewClazz;
    NSArray *_filterGroup;
    double _filterBarCellWidth;
    double _filterBarHeight;
    Class _filterBarGroupCellClazz;
    Class _filterBarTableCellClazz;
    Class _onlineControllerClazz;
}

@property(nonatomic) _Bool isRenderFilterThumb; // @synthesize isRenderFilterThumb=_isRenderFilterThumb;
@property(nonatomic) _Bool onlyReturnFilter; // @synthesize onlyReturnFilter=_onlyReturnFilter;
@property(retain, nonatomic) Class onlineControllerClazz; // @synthesize onlineControllerClazz=_onlineControllerClazz;
@property(nonatomic) _Bool displayFilterSubtitles; // @synthesize displayFilterSubtitles=_displayFilterSubtitles;
@property(nonatomic) _Bool enableOnlineFilter; // @synthesize enableOnlineFilter=_enableOnlineFilter;
@property(nonatomic) _Bool enableNormalFilter; // @synthesize enableNormalFilter=_enableNormalFilter;
@property(nonatomic) _Bool enableFilterHistory; // @synthesize enableFilterHistory=_enableFilterHistory;
@property(nonatomic) _Bool enableFilterConfig; // @synthesize enableFilterConfig=_enableFilterConfig;
@property(retain, nonatomic) Class filterBarTableCellClazz; // @synthesize filterBarTableCellClazz=_filterBarTableCellClazz;
@property(retain, nonatomic) Class filterBarGroupCellClazz; // @synthesize filterBarGroupCellClazz=_filterBarGroupCellClazz;
@property(nonatomic) double filterBarHeight; // @synthesize filterBarHeight=_filterBarHeight;
@property(nonatomic) double filterBarCellWidth; // @synthesize filterBarCellWidth=_filterBarCellWidth;
@property(retain, nonatomic) NSArray *filterGroup; // @synthesize filterGroup=_filterGroup;
@property(retain, nonatomic) Class viewClazz; // @synthesize viewClazz=_viewClazz;
- (void).cxx_destruct;
- (id)viewController;
- (Class)defaultComponentClazz;
- (void)initOptions;

@end

