//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, TuSDKPFBrush, TuSDKPFBrushLocalPackage;

@interface TuSDKPFBrushManager : NSObject
{
    TuSDKPFBrushLocalPackage *_config;
    TuSDKPFBrush *_currentBrush;
    NSArray *_brushCodes;
}

+ (id)initWithConfig:(id)arg1;
+ (id)manager;
@property(readonly, nonatomic) NSArray *brushCodes; // @synthesize brushCodes=_brushCodes;
- (void).cxx_destruct;
- (id)brushWithCode:(id)arg1;
@property(readonly, nonatomic) _Bool isInited;
- (void)initWithConfig:(id)arg1;

@end

