//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKICGridView.h"

#import "TuSDKPFPhotosGridCellDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSArray, NSString;
@protocol TuSDKPFPhotoGridProtocol, TuSDKTSAssetsGroupInterface;

@interface TuSDKPFPhotosGridView : TuSDKICGridView <TuSDKPFPhotosGridCellDelegate, UICollectionViewDataSource, UICollectionViewDelegate>
{
    NSArray *_photos;
    double thumbSize;
    double thumbPadding;
    _Bool _enableMultiSelection;
    _Bool _displayCameraCell;
    Class _cellViewClazz;
    unsigned long long _photoColumnNumber;
    long long _photosSortKeyType;
    id <TuSDKTSAssetsGroupInterface> _group;
    id <TuSDKPFPhotoGridProtocol> _gridProtocol;
}

@property(nonatomic) id <TuSDKPFPhotoGridProtocol> gridProtocol; // @synthesize gridProtocol=_gridProtocol;
@property(retain, nonatomic) id <TuSDKTSAssetsGroupInterface> group; // @synthesize group=_group;
@property(nonatomic) long long photosSortKeyType; // @synthesize photosSortKeyType=_photosSortKeyType;
@property(nonatomic) _Bool displayCameraCell; // @synthesize displayCameraCell=_displayCameraCell;
@property(nonatomic) _Bool enableMultiSelection; // @synthesize enableMultiSelection=_enableMultiSelection;
@property(nonatomic) unsigned long long photoColumnNumber; // @synthesize photoColumnNumber=_photoColumnNumber;
@property(retain, nonatomic) Class cellViewClazz; // @synthesize cellViewClazz=_cellViewClazz;
- (void).cxx_destruct;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)didSelectCell:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)reloadItemWithData:(id)arg1;
- (void)refreshViewWithData:(id)arg1;
- (void)lsqInitView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

