//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSMutableArray;

@interface TuSDKFilterParameter : NSObject
{
    NSMutableArray *_mArgs;
    NSDictionary *_defaultArgs;
    _Bool _isInited;
    NSArray *_points;
}

+ (id)parameterWithArgs:(id)arg1;
+ (id)parameter;
@property(retain, nonatomic) NSArray *points; // @synthesize points=_points;
@property(readonly, nonatomic) _Bool isInited; // @synthesize isInited=_isInited;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (void)appendFloatArgWithKey:(id)arg1 value:(double)arg2 minValue:(double)arg3 maxValue:(double)arg4;
- (id)changedArgs;
- (void)stepArgWithKey:(id)arg1 precent:(double)arg2;
- (void)setArgWithKey:(id)arg1 precent:(double)arg2;
- (double)argWithDefaultKey:(id)arg1;
- (id)argWithKey:(id)arg1;
- (void)resetWithKey:(id)arg1;
- (void)forceProcessing;
- (void)reset;
@property(readonly, nonatomic) NSArray *argKeys;
@property(readonly, nonatomic) NSArray *args;
@property(readonly, nonatomic) unsigned long long count;
- (id)initWithArgs:(id)arg1;

@end

