//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKICTableViewCell.h"

@class NSArray, NSMutableArray, TuSDKAOCellGridViewAlgorithmic;
@protocol TuSDKPFPhotosCellProtocol;

@interface TuSDKPFPhotosCell : TuSDKICTableViewCell
{
    NSMutableArray *_gridViews;
    Class _gridViewClazz;
    TuSDKAOCellGridViewAlgorithmic *_algorithmic;
    id <TuSDKPFPhotosCellProtocol> _gridProtocol;
}

@property(nonatomic) id <TuSDKPFPhotosCellProtocol> gridProtocol; // @synthesize gridProtocol=_gridProtocol;
@property(readonly, nonatomic) NSArray *gridViews; // @synthesize gridViews=_gridViews;
@property(retain, nonatomic) TuSDKAOCellGridViewAlgorithmic *algorithmic; // @synthesize algorithmic=_algorithmic;
@property(retain, nonatomic) Class gridViewClazz; // @synthesize gridViewClazz=_gridViewClazz;
- (void).cxx_destruct;
- (void)onSelectedGrid:(id)arg1;
- (void)viewNeedRest;
- (void)setData:(id)arg1;
- (void)lsqInitView;

@end

