//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

@interface TuSDKAOFile : NSObject
{
    NSMutableArray *_headers;
    unsigned long long _pos;
    unsigned long long _fileTotal;
    _Bool _isSdkFile;
    NSString *_file;
    unsigned long long _fileLength;
}

+ (void)test;
+ (id)initWithFile:(id)arg1;
@property(readonly, nonatomic) unsigned long long fileLength; // @synthesize fileLength=_fileLength;
@property(readonly, nonatomic) _Bool isSdkFile; // @synthesize isSdkFile=_isSdkFile;
@property(copy, nonatomic) NSString *file; // @synthesize file=_file;
- (void).cxx_destruct;
- (id)getImageWithName:(id)arg1;
- (id)getTextWithName:(id)arg1;
- (id)fileHeaderWithName:(id)arg1 type:(unsigned char)arg2;
- (id)readText:(id)arg1;
- (unsigned long long)readLength:(id)arg1;
- (void)parserImageHeader:(id)arg1 data:(id)arg2;
- (void)parserTextHeader:(id)arg1 data:(id)arg2;
- (_Bool)parserHeader:(id)arg1;
- (id)getDataWithHeader:(id)arg1;
- (id)getFileData;
- (void)readHeaders;
- (id)initWithFile:(id)arg1;

@end

