//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class TuSDKCPGroupFilterItem;
@protocol TuSDKTKFiltersTaskInterface;

@protocol TuSDKCPGroupFilterItemCellInterface <NSObject>
@property(nonatomic) id <TuSDKTKFiltersTaskInterface> filterTask;
@property(nonatomic) _Bool displaySelectionIcon;
@property(retain, nonatomic) TuSDKCPGroupFilterItem *mode;
@property(readonly, nonatomic) _Bool activating;
@property(nonatomic) long long action;
- (void)stopActivating;
- (void)waitInActivate:(double)arg1;
- (_Bool)isCameraAction;
@end

