//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIImage;

@interface TuSDKPFSmudgeLog : NSObject
{
    NSString *_cacheTempFilePath;
    unsigned char _cached;
    UIImage *_image;
}

@property(readonly, nonatomic) unsigned char cached; // @synthesize cached=_cached;
- (void).cxx_destruct;
- (id)buildTempFile;
- (void)destroy;
- (void)runCacheJob;
@property(readonly, nonatomic) UIImage *image; // @synthesize image=_image;
- (id)initWithImage:(id)arg1;

@end

