//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TuSDKPFStickerLocalPackageDelegate-Protocol.h"

@class NSMutableArray, NSString;

@interface TuSDKPFStickerBarViewBase : UIView <TuSDKPFStickerLocalPackageDelegate>
{
    NSMutableArray *_cates;
    long long _cateIndex;
}

- (void).cxx_destruct;
- (void)stickerManager:(id)arg1 item:(id)arg2 changedStatus:(long long)arg3;
- (id)stickerAllDatas;
- (id)stickerDatasWithId:(unsigned long long)arg1;
- (void)selectCateWithIndex:(long long)arg1;
- (id)currentCategory;
- (void)selectCateButtonWithIndex:(unsigned long long)arg1;
- (id)buildButtonWithCategory:(id)arg1 left:(double)arg2 width:(double)arg3 index:(unsigned long long)arg4;
- (void)refreshCateDatas;
- (void)initCateParamsView;
- (void)loadCatategories:(id)arg1;
- (void)viewWillDestory;
- (void)lsqInitView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

