//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class TuSDKPFEditCuterBottomBar, TuSDKPFEditCuterOptionBar;
@protocol TuSDKICTouchImageViewInterface;

@interface TuSDKPFEditCuterView : UIView
{
    TuSDKPFEditCuterBottomBar *_bottomBar;
    TuSDKPFEditCuterOptionBar *_optionBar;
    UIView<TuSDKICTouchImageViewInterface> *_imageView;
}

@property(readonly, nonatomic) UIView<TuSDKICTouchImageViewInterface> *imageView; // @synthesize imageView=_imageView;
@property(readonly, nonatomic) TuSDKPFEditCuterOptionBar *optionBar; // @synthesize optionBar=_optionBar;
@property(readonly, nonatomic) TuSDKPFEditCuterBottomBar *bottomBar; // @synthesize bottomBar=_bottomBar;
- (void).cxx_destruct;
- (void)needUpdateLayout;
- (void)lsqInitView;

@end

