//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKGPUImageTwoInputFilter.h"

#import "TuSDKFilterParameterProtocol-Protocol.h"
#import "TuSDKFilterStickerProtocol-Protocol.h"

@class NSString, TuSDKFilterParameter;

@interface TuSDKGPULightGlareFilter : TuSDKGPUImageTwoInputFilter <TuSDKFilterParameterProtocol, TuSDKFilterStickerProtocol>
{
    int mixUniform;
    int aspectRatioUniform;
    unsigned long long textureRotation;
    double _aspectRatio;
    TuSDKFilterParameter *_parameter;
    double _mix;
}

@property(nonatomic) double mix; // @synthesize mix=_mix;
@property(nonatomic) double aspectRatio; // @synthesize aspectRatio=_aspectRatio;
- (void).cxx_destruct;
- (void)submitParameter:(id)arg1;
- (void)submitParameter;
@property(retain, nonatomic) TuSDKFilterParameter *parameter; // @synthesize parameter=_parameter;
- (void)submitFilterArg:(id)arg1;
- (id)configParams:(id)arg1;
- (void)setInputRotation:(unsigned long long)arg1 atIndex:(long long)arg2;
- (void)setInputSize:(struct CGSize)arg1 atIndex:(long long)arg2;
- (void)forceProcessingAtSize:(struct CGSize)arg1;
- (void)adjustAspectRatio;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

