//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKTKFiltersTaskBase.h"

@interface TuSDKTKFiltersTempTask : TuSDKTKFiltersTaskBase
{
    _Bool _isCancelTask;
}

+ (id)initWithInputImage:(id)arg1;
@property(readonly, nonatomic) _Bool isCancelTask; // @synthesize isCancelTask=_isCancelTask;
- (void)resetQueues;
- (void)asyncBuildWithFilterName:(id)arg1;
- (void)setInputImage:(id)arg1;
- (id)sampleRootPath;
- (id)init;
- (id)initWithInputImage:(id)arg1;

@end

