//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKGaussianBlurFiveRadiusFilter.h"

@interface TuSDKGPUSurfaceBlurFilter : TuSDKGaussianBlurFiveRadiusFilter
{
    double firstThresholdLevelUniform;
    double secondThresholdLevelUniform;
    double _thresholdLevel;
    double _maxBlursize;
    double _maxThresholdLevel;
}

@property(readonly, nonatomic) double maxThresholdLevel; // @synthesize maxThresholdLevel=_maxThresholdLevel;
@property(readonly, nonatomic) double maxBlursize; // @synthesize maxBlursize=_maxBlursize;
@property(nonatomic) double thresholdLevel; // @synthesize thresholdLevel=_thresholdLevel;
- (id)initWithVertexShaderFromString:(id)arg1 fragmentShaderFromString:(id)arg2;
- (id)initOnPerformance;
- (id)init;

@end

