//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKPFBrushTableItemCellBase.h"

@class UIButton, UIImageView, UILabel, UIView;

@interface TuSDKPFBrushTableItemCell : TuSDKPFBrushTableItemCellBase
{
    UIView *_wrapView;
    UIImageView *_thumbView;
    UILabel *_titleView;
    UIView *_titleBgView;
    UIImageView *_selectedView;
    UIButton *_removeButton;
}

@property(readonly, nonatomic) UIImageView *selectedView; // @synthesize selectedView=_selectedView;
@property(readonly, nonatomic) UIView *titleBgView; // @synthesize titleBgView=_titleBgView;
@property(readonly, nonatomic) UILabel *titleView; // @synthesize titleView=_titleView;
@property(readonly, nonatomic) UIView *wrapView; // @synthesize wrapView=_wrapView;
- (void).cxx_destruct;
- (void)onRemoveConfirm;
- (void)handleTypeEraser:(id)arg1;
- (void)handleTypeOnlie:(id)arg1;
- (void)handleTypeBrush:(id)arg1;
- (void)handleRemoveButton;
- (void)cancelRemoveFlag;
- (void)viewNeedRest;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setMode:(id)arg1;
- (id)thumbView;
- (id)lsqSetSize:(struct CGSize)arg1;
- (void)lsqInitView;

@end

