//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKPFSimpleProcessor.h"

@class TuSDKFilterWrap;

@interface TuSDKPFFilterSmudgeProcessor : TuSDKPFSimpleProcessor
{
    TuSDKFilterWrap *_filterWrap;
    struct CGImage *_filterImageRef;
}

@property(retain, nonatomic) TuSDKFilterWrap *filterWrap; // @synthesize filterWrap=_filterWrap;
- (void).cxx_destruct;
- (void)destroy;
- (void)drawAt:(struct CGPoint)arg1 scaleFactor:(double)arg2;
- (void)drawAtPoint:(struct CGPoint)arg1 withOrientation:(float)arg2 withScale:(float)arg3 withAlphaFactor:(float)arg4;
- (struct CGImage *)generatedFilteredImage;
- (void)setBrushSize:(double)arg1;
- (void)setCurrentBrush:(id)arg1;
- (void)initDefaultBrush;
- (void)setImage:(id)arg1;
- (id)init;

@end

