//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKFilter.h"

#import "TuSDKFilterParameterProtocol-Protocol.h"

@class NSString, TuSDKFilterParameter;

@interface TuSDKGPUColorMultiAdjustmentFilter : TuSDKFilter <TuSDKFilterParameterProtocol>
{
    int brightnessUniform;
    int contrastUniform;
    int saturationUniform;
    int exposureUniform;
    int shadowsUniform;
    int highlightsUniform;
    int temperatureUniform;
    int holyLightUniform;
    int vignetteUniform;
    int sharpnessUniform;
    TuSDKFilterParameter *_parameter;
    double _brightness;
    double _contrast;
    double _saturation;
    double _exposure;
    double _shadows;
    double _highlights;
    double _temperature;
    double _holyLight;
    double _vignette;
    double _sharpness;
}

@property(nonatomic) double sharpness; // @synthesize sharpness=_sharpness;
@property(nonatomic) double vignette; // @synthesize vignette=_vignette;
@property(nonatomic) double holyLight; // @synthesize holyLight=_holyLight;
@property(nonatomic) double temperature; // @synthesize temperature=_temperature;
@property(nonatomic) double highlights; // @synthesize highlights=_highlights;
@property(nonatomic) double shadows; // @synthesize shadows=_shadows;
@property(nonatomic) double exposure; // @synthesize exposure=_exposure;
@property(nonatomic) double saturation; // @synthesize saturation=_saturation;
@property(nonatomic) double contrast; // @synthesize contrast=_contrast;
@property(nonatomic) double brightness; // @synthesize brightness=_brightness;
- (void).cxx_destruct;
- (void)submitParameter:(id)arg1;
- (void)submitParameter;
@property(retain, nonatomic) TuSDKFilterParameter *parameter; // @synthesize parameter=_parameter;
- (void)submitFilterArg:(id)arg1;
- (id)configParams:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

