//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TuSDKTSLog : NSObject
{
    long long _outputLevel;
}

+ (void)debug:(id)arg1;
+ (void)info:(id)arg1;
+ (void)warn:(id)arg1;
+ (void)error:(id)arg1;
+ (void)log:(id)arg1;
+ (void)log:(id)arg1 arguments:(char *)arg2;
+ (id)sharedLog;
@property(nonatomic) long long outputLevel; // @synthesize outputLevel=_outputLevel;

@end

