//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKDataJson.h"

@class NSArray, NSString;

@interface TuSDKNKFaceMark5FaceResult : TuSDKDataJson
{
    long long _count;
    NSArray *_points;
    NSString *_faceId;
    struct CGPoint _eye_left;
    struct CGPoint _eye_right;
    struct CGPoint _mouth_left;
    struct CGPoint _mouth_right;
    struct CGPoint _nose;
}

@property(nonatomic) struct CGPoint nose; // @synthesize nose=_nose;
@property(nonatomic) struct CGPoint mouth_right; // @synthesize mouth_right=_mouth_right;
@property(nonatomic) struct CGPoint mouth_left; // @synthesize mouth_left=_mouth_left;
@property(nonatomic) struct CGPoint eye_right; // @synthesize eye_right=_eye_right;
@property(nonatomic) struct CGPoint eye_left; // @synthesize eye_left=_eye_left;
@property(copy, nonatomic) NSString *faceId; // @synthesize faceId=_faceId;
@property(retain, nonatomic) NSArray *points; // @synthesize points=_points;
@property(nonatomic) long long count; // @synthesize count=_count;
- (void).cxx_destruct;
- (struct CGPoint)parsePointWithValue:(id)arg1;
- (id)parseValueWithPoint:(struct CGPoint)arg1;
- (void)deserializationWithJson:(id)arg1;

@end

