//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKDataJson.h"

@class NSArray, NSDictionary, NSString;
@protocol RuntimeTextureDelegate;

@interface TuSDKFilterOption : TuSDKDataJson
{
    _Bool _texturesKeepInput;
    _Bool _canDefinition;
    _Bool _disableRuntime;
    _Bool _isInternal;
    unsigned long long _filterId;
    unsigned long long _groupId;
    NSString *_code;
    NSString *_name;
    NSString *_thumb;
    NSString *_thumbKey;
    unsigned long long _filterType;
    NSString *_color;
    NSArray *_textures;
    unsigned long long _encryptType;
    NSDictionary *_args;
    NSString *_argList;
    NSString *_vertex;
    NSString *_fragment;
    unsigned long long _version;
    NSArray *_internalTextures;
    id <RuntimeTextureDelegate> _runtimeTextureDelegate;
}

@property(nonatomic) __weak id <RuntimeTextureDelegate> runtimeTextureDelegate; // @synthesize runtimeTextureDelegate=_runtimeTextureDelegate;
@property(retain, nonatomic) NSArray *internalTextures; // @synthesize internalTextures=_internalTextures;
@property(nonatomic) _Bool isInternal; // @synthesize isInternal=_isInternal;
@property(nonatomic) _Bool disableRuntime; // @synthesize disableRuntime=_disableRuntime;
@property(nonatomic) unsigned long long version; // @synthesize version=_version;
@property(copy, nonatomic) NSString *fragment; // @synthesize fragment=_fragment;
@property(copy, nonatomic) NSString *vertex; // @synthesize vertex=_vertex;
@property(copy, nonatomic) NSString *argList; // @synthesize argList=_argList;
@property(retain, nonatomic) NSDictionary *args; // @synthesize args=_args;
@property(nonatomic) unsigned long long encryptType; // @synthesize encryptType=_encryptType;
@property(nonatomic) _Bool canDefinition; // @synthesize canDefinition=_canDefinition;
@property(nonatomic) _Bool texturesKeepInput; // @synthesize texturesKeepInput=_texturesKeepInput;
@property(retain, nonatomic) NSArray *textures; // @synthesize textures=_textures;
@property(retain, nonatomic) NSString *color; // @synthesize color=_color;
@property(nonatomic) unsigned long long filterType; // @synthesize filterType=_filterType;
@property(retain, nonatomic) NSString *thumbKey; // @synthesize thumbKey=_thumbKey;
@property(retain, nonatomic) NSString *thumb; // @synthesize thumb=_thumb;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *code; // @synthesize code=_code;
@property(nonatomic) unsigned long long groupId; // @synthesize groupId=_groupId;
@property(nonatomic) unsigned long long filterId; // @synthesize filterId=_filterId;
- (void).cxx_destruct;
- (id)getFilterName;
- (id)getFilter;
- (id)copy;
- (_Bool)isEqual:(id)arg1;
- (void)deserializationWithJson:(id)arg1;

@end

