//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPAlbumOptions.h"

@class TuSDKPFCameraOptions, TuSDKPFEditTurnAndCutOptions;

@interface TuSDKCPAvatarOptions : TuSDKCPAlbumOptions
{
    TuSDKPFCameraOptions *_cameraOptions;
    TuSDKPFEditTurnAndCutOptions *_editTurnAndCutOptions;
}

@property(readonly, nonatomic) TuSDKPFEditTurnAndCutOptions *editTurnAndCutOptions; // @synthesize editTurnAndCutOptions=_editTurnAndCutOptions;
@property(readonly, nonatomic) TuSDKPFCameraOptions *cameraOptions; // @synthesize cameraOptions=_cameraOptions;
- (void).cxx_destruct;
- (void)initOptions;

@end

