//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TuSDKNKDownloadMangerDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, TuSDKBrushAdapter;

@interface TuSDKPFBrushLocalPackage : NSObject <TuSDKNKDownloadMangerDelegate>
{
    TuSDKBrushAdapter *_adapter;
    NSMutableArray *_delegates;
}

+ (id)initWithConfig:(id)arg1;
+ (id)package;
- (void).cxx_destruct;
- (void)removeDelegate:(id)arg1;
- (void)appenDelegate:(id)arg1;
- (void)notifyDelegatesWithItem:(id)arg1 status:(long long)arg2;
- (id)jsonAllData;
- (void)downloadManger:(id)arg1 item:(id)arg2 changedStatus:(long long)arg3;
- (void)removeDownloadWithIdt:(unsigned long long)arg1;
- (void)cancelDownloadWithIdt:(unsigned long long)arg1;
- (void)downloadWithIdt:(unsigned long long)arg1 key:(id)arg2 fileId:(id)arg3;
- (_Bool)loadBrushData:(id)arg1;
- (void)cancelLoadImage:(id)arg1;
- (void)loadThumbWithBrush:(id)arg1 imageView:(id)arg2;
- (id)brushWithCodes:(id)arg1;
- (id)verifyCodes:(id)arg1;
- (id)brushWithCode:(id)arg1;
- (id)eraserBrush;
@property(readonly, nonatomic) NSArray *codes;
@property(readonly, nonatomic) _Bool isInited;
- (void)initWithConfig:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

