//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKDataJson.h"

@class NSDictionary, NSString, UIImage;

@interface TuSDKPFBrush : TuSDKDataJson
{
    _Bool _isInternal;
    unsigned long long _brushId;
    unsigned long long _groupId;
    NSString *_code;
    NSString *_name;
    NSString *_thumb;
    NSString *_thumbKey;
    NSString *_brushImageKey;
    long long _brushType;
    long long _rotateType;
    long long _positionType;
    long long _sizeType;
    NSDictionary *_args;
    UIImage *_image;
}

+ (id)brushWithType:(long long)arg1;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) _Bool isInternal; // @synthesize isInternal=_isInternal;
@property(retain, nonatomic) NSDictionary *args; // @synthesize args=_args;
@property(nonatomic) long long sizeType; // @synthesize sizeType=_sizeType;
@property(nonatomic) long long positionType; // @synthesize positionType=_positionType;
@property(nonatomic) long long rotateType; // @synthesize rotateType=_rotateType;
@property(nonatomic) long long brushType; // @synthesize brushType=_brushType;
@property(copy, nonatomic) NSString *brushImageKey; // @synthesize brushImageKey=_brushImageKey;
@property(copy, nonatomic) NSString *thumbKey; // @synthesize thumbKey=_thumbKey;
@property(retain, nonatomic) NSString *thumb; // @synthesize thumb=_thumb;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *code; // @synthesize code=_code;
@property(nonatomic) unsigned long long groupId; // @synthesize groupId=_groupId;
@property(nonatomic) unsigned long long brushId; // @synthesize brushId=_brushId;
- (void).cxx_destruct;
- (id)copy;
- (id)nameKey;
- (_Bool)isEqual:(id)arg1;
- (void)deserializationWithJson:(id)arg1;

@end

