//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray;
@protocol TuSDKTSAssetInterface;

@interface TuSDKTSALAssetsGroupedCTD : NSObject
{
    NSArray<TuSDKTSAssetInterface> *_assets;
    NSMutableArray *_sections;
    NSMutableArray *_items;
}

+ (id)groupedWithAssets:(id)arg1;
+ (id)groupedWithAssetsGroup:(id)arg1;
@property(readonly, nonatomic) NSArray *items; // @synthesize items=_items;
@property(readonly, nonatomic) NSArray *sections; // @synthesize sections=_sections;
- (void).cxx_destruct;
- (id)rowDatasIndexPath:(id)arg1 withLimit:(unsigned long long)arg2;
- (unsigned long long)countRowInSection:(long long)arg1 withLimit:(unsigned long long)arg2;
- (void)countGroups;
@property(readonly, nonatomic) unsigned long long count;
- (id)initWithAssets:(id)arg1;

@end

