//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKThreeInputFilter.h"

#import "TuSDKFilterParameterProtocol-Protocol.h"

@class NSString, TuSDKFilterParameter;

@interface TuSDKColorMixCoverFilter : TuSDKThreeInputFilter <TuSDKFilterParameterProtocol>
{
    int vignetteCenterUniform;
    int vignetteColorUniform;
    int vignetteStartUniform;
    int vignetteEndUniform;
    unsigned int mixedUniform;
    unsigned int coverUniform;
    int aspectRatioUniform;
    unsigned long long textureRotation;
    float _mixed;
    float _cover;
    double _aspectRatio;
    TuSDKFilterParameter *_parameter;
    double _vignetteStart;
    double _vignetteEnd;
    struct GPUVector3 _vignetteColor;
    struct CGPoint _vignetteCenter;
}

@property(nonatomic) double vignetteEnd; // @synthesize vignetteEnd=_vignetteEnd;
@property(nonatomic) double vignetteStart; // @synthesize vignetteStart=_vignetteStart;
@property(nonatomic) struct GPUVector3 vignetteColor; // @synthesize vignetteColor=_vignetteColor;
@property(nonatomic) struct CGPoint vignetteCenter; // @synthesize vignetteCenter=_vignetteCenter;
@property(nonatomic) float cover; // @synthesize cover=_cover;
@property(nonatomic) float mixed; // @synthesize mixed=_mixed;
@property(nonatomic) double aspectRatio; // @synthesize aspectRatio=_aspectRatio;
- (void).cxx_destruct;
- (void)submitParameter:(id)arg1;
- (void)submitParameter;
@property(retain, nonatomic) TuSDKFilterParameter *parameter; // @synthesize parameter=_parameter;
- (void)submitFilterArg:(id)arg1;
- (id)configParams:(id)arg1;
- (void)setInputRotation:(unsigned long long)arg1 atIndex:(long long)arg2;
- (void)setInputSize:(struct CGSize)arg1 atIndex:(long long)arg2;
- (void)forceProcessingAtSize:(struct CGSize)arg1;
- (void)adjustAspectRatio;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

