//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKPFPhotoPreviewControllerBase.h"

#import "TuSDKPFPhotosGridPreviewProtocol-Protocol.h"

@class NSArray, NSIndexPath, NSMutableArray, NSString, TuSDKPFPhotoPreview;
@protocol TuSDKPFPhotoPreviewControllerDelegate, TuSDKTSAssetInterface, TuSDKTSAssetsGroupInterface;

@interface TuSDKPFPhotoPreviewController : TuSDKPFPhotoPreviewControllerBase <TuSDKPFPhotosGridPreviewProtocol>
{
    TuSDKPFPhotoPreview *_defaultStyleView;
    id <TuSDKTSAssetInterface> _asset;
    NSIndexPath *_indexPath;
    _Bool _downloading;
    NSArray *_photos;
    Class _viewClazz;
    Class _cellViewClazz;
    Class _photosViewClazz;
    unsigned long long _maxSelectionNumber;
    long long _photosSortKeyType;
    unsigned long long _currentIndex;
    NSMutableArray *_selectedItems;
    id <TuSDKTSAssetsGroupInterface> _group;
    id <TuSDKPFPhotoPreviewControllerDelegate> _delegate;
    struct CGSize _maxSelectionImageSize;
}

@property(nonatomic) __weak id <TuSDKPFPhotoPreviewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) id <TuSDKTSAssetsGroupInterface> group; // @synthesize group=_group;
@property(retain, nonatomic) NSMutableArray *selectedItems; // @synthesize selectedItems=_selectedItems;
@property(nonatomic) unsigned long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(nonatomic) long long photosSortKeyType; // @synthesize photosSortKeyType=_photosSortKeyType;
@property(nonatomic) struct CGSize maxSelectionImageSize; // @synthesize maxSelectionImageSize=_maxSelectionImageSize;
@property(nonatomic) unsigned long long maxSelectionNumber; // @synthesize maxSelectionNumber=_maxSelectionNumber;
@property(retain, nonatomic) Class photosViewClazz; // @synthesize photosViewClazz=_photosViewClazz;
@property(retain, nonatomic) Class cellViewClazz; // @synthesize cellViewClazz=_cellViewClazz;
@property(retain, nonatomic) Class viewClazz; // @synthesize viewClazz=_viewClazz;
@property(readonly, nonatomic) TuSDKPFPhotoPreview *defaultStyleView; // @synthesize defaultStyleView=_defaultStyleView;
- (void).cxx_destruct;
- (void)onTuSDKPFPhotosCellSelectedWithAsset:(id)arg1;
- (_Bool)selectedItemsContainsObject:(id)arg1;
- (void)reloadButtonsWithObject:(id)arg1;
- (void)reloadSelecteButtonWithObject:(id)arg1;
- (void)photosGridVPreviewScrollToIndex:(long long)arg1;
- (void)reloadSelections;
- (void)selecteAction;
- (void)notifySelectedAsset:(id)arg1;
- (void)completeAction;
- (void)configToolBar;
- (void)configDefaultStyleView:(id)arg1;
- (void)buildDefaultStyleView;
- (void)viewDidLoad;
- (_Bool)prefersStatusBarHidden;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

