//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class TuSDKPFSticker, TuSDKPFStickerLocalController;

@protocol TuSDKPFStickerLocalControllerDelegate <NSObject>
- (void)onTuSDKPFStickerLocal:(TuSDKPFStickerLocalController *)arg1 sticker:(TuSDKPFSticker *)arg2;
@end

