//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKPFEditFilterGroupViewBase.h"

#import "TuSDKCPParameterConfigDelegate-Protocol.h"

@class NSString, UIButton, UIView;
@protocol TuSDKCPGroupFilterBarInterface, TuSDKCPParameterConfigViewInterface, TuSDKCPSubtitlesViewInterface, TuSDKPFEditFilterGroupDelegate;

@interface TuSDKPFEditFilterGroupView : TuSDKPFEditFilterGroupViewBase <TuSDKCPParameterConfigDelegate>
{
    UIView<TuSDKCPGroupFilterBarInterface> *_filterBar;
    UIView<TuSDKCPSubtitlesViewInterface> *_titleView;
    UIView<TuSDKCPParameterConfigViewInterface> *_configView;
    UIView *_bottomBar;
    UIButton *_cancelButton;
    UIButton *_completeButton;
    id <TuSDKPFEditFilterGroupDelegate> _delegate;
    double _filterBarBottom;
}

@property(nonatomic) double filterBarBottom; // @synthesize filterBarBottom=_filterBarBottom;
@property(readonly, nonatomic) UIButton *completeButton; // @synthesize completeButton=_completeButton;
@property(readonly, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(readonly, nonatomic) UIView *bottomBar; // @synthesize bottomBar=_bottomBar;
@property(readonly, nonatomic) UIView<TuSDKCPParameterConfigViewInterface> *configView; // @synthesize configView=_configView;
@property(nonatomic) __weak id <TuSDKPFEditFilterGroupDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onTuSDKCPParameterConfig:(id)arg1 resetWithIndex:(unsigned long long)arg2;
- (double)onTuSDKCPParameterConfig:(id)arg1 valueWithIndex:(unsigned long long)arg2;
- (void)onTuSDKCPParameterConfig:(id)arg1 changeWithIndex:(unsigned long long)arg2 progress:(double)arg3;
- (_Bool)onFilterSelectedWithData:(id)arg1;
- (void)setConfigViewParams:(id)arg1;
- (void)configViewShow:(_Bool)arg1;
- (void)loadFilters:(id)arg1;
- (void)requestRender;
- (void)handleCompleteAction;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)setDefaultShowState:(_Bool)arg1;
- (void)setFilterBarHeight:(double)arg1;
- (id)titleView;
- (id)filterBar;
- (void)lsqInitView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

