//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class TuSDKICGPUImageView, TuSDKLogoView;

@interface TuSDKICFilterMovieViewWrap : UIView
{
    TuSDKICGPUImageView *_view;
    TuSDKLogoView *_logoView;
    struct CGRect _cropRect;
}

@property(nonatomic) struct CGRect cropRect; // @synthesize cropRect=_cropRect;
- (void).cxx_destruct;
@property(readonly, nonatomic) TuSDKICGPUImageView *view;
- (void)needUpdateLayout;
- (void)setBackgroundColor:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)lsqInitView;
- (id)logoView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

