//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKPFSmudgeViewBase.h"

@class TuSDKPFEditSmudgeBottomBar, TuSDKPFEditWipeAndFilterConfigBar, UIImageView, UIView;
@protocol TuSDKICSmudgeImageViewInterface;

@interface TuSDKPFEditWipeAndFilterView : TuSDKPFSmudgeViewBase
{
    long long _currentBrushSize;
    long long _defaultBrushSize;
    UIView<TuSDKICSmudgeImageViewInterface> *_imageView;
    TuSDKPFEditWipeAndFilterConfigBar *_brushConfigBar;
    TuSDKPFEditSmudgeBottomBar *_bottomBar;
    UIView *_brushSizeAnimView;
    UIImageView *_zoomInImage;
    unsigned long long _maxUndoCount;
}

@property(nonatomic) unsigned long long maxUndoCount; // @synthesize maxUndoCount=_maxUndoCount;
@property(readonly, nonatomic) UIImageView *zoomInImage; // @synthesize zoomInImage=_zoomInImage;
@property(readonly, nonatomic) UIView *brushSizeAnimView; // @synthesize brushSizeAnimView=_brushSizeAnimView;
@property(readonly, nonatomic) TuSDKPFEditSmudgeBottomBar *bottomBar; // @synthesize bottomBar=_bottomBar;
@property(readonly, nonatomic) TuSDKPFEditWipeAndFilterConfigBar *brushConfigBar; // @synthesize brushConfigBar=_brushConfigBar;
@property(readonly, nonatomic) UIView<TuSDKICSmudgeImageViewInterface> *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)viewWillDestory;
- (unsigned long long)getBrushSizeInPoint;
- (void)updateBrushSizeWithValue:(unsigned long long)arg1;
- (void)setBrushSize:(long long)arg1;
@property(nonatomic) long long defaultBrushSize;
- (void)setImage:(id)arg1;
- (void)needUpdateLayout;
- (id)sizeAnimView;
- (id)smudgeWrap;
- (void)lsqInitView;

@end

