//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKFilter.h"

@class GLProgram, NSArray;

@interface TuSDKGPUImageFilter : TuSDKFilter
{
    GLProgram *stickerProgram;
    int stickerPositionAttribute;
    int stickerTextureCoordinateAttribute;
    int stickerInputTextureUniform;
    NSArray *_stickerImages;
    struct CGRect _displayRect;
    double _displayRatio;
    _Bool _stickerVisibility;
    NSArray *_featurePoints;
    float _deviceAngle;
    CDStruct_461fb6ec _glTextureMatrix;
    CDStruct_461fb6ec _glMVPMatrix;
    unsigned int _glMVPMatrixUniform;
    unsigned int _glTextureMatrixUniform;
    _Bool _enableLiveSticker;
}

@property(nonatomic) _Bool enableLiveSticker; // @synthesize enableLiveSticker=_enableLiveSticker;
- (void).cxx_destruct;
- (struct CGPoint)getReferPoint:(id)arg1 fromPoint:(id)arg2;
- (id)getRelativePointIndexes:(unsigned long long)arg1 isLeft:(_Bool)arg2;
- (void)calculateMatrix:(struct CGSize)arg1 textureSize:(struct CGSize)arg2 point:(struct CGPoint)arg3 rotation:(double)arg4;
- (void)calcalateFaceStickerSizeAndPos:(id)arg1 canvasSize:(struct CGSize)arg2;
- (void)calculateStickerSizeAndPos:(id)arg1 canvasSize:(struct CGSize)arg2 textureInfo:(id)arg3;
- (void)renderStickerImage:(id)arg1;
- (void)renderStickers;
- (void)seekToStickerIndexByTime:(CDStruct_1b6d18a9)arg1;
- (void)setStickerShowTime:(CDStruct_1b6d18a9)arg1;
- (void)setAutoplayStickers:(_Bool)arg1;
- (void)setStickerVisibility:(_Bool)arg1;
- (void)setDisplayRect:(struct CGRect)arg1 withRatio:(double)arg2;
- (id)getStickerImageBy:(id)arg1;
- (unsigned long long)stickerCount;
- (void)setLiveStickers:(id)arg1;
- (void)updateFaceFeatures:(id)arg1 angle:(float)arg2;
- (void)newFrameReadyAtTime:(CDStruct_1b6d18a9)arg1 atIndex:(long long)arg2;
- (void)inputFramebufferUnlock;
- (void)inputFramebufferBindTexture;
- (void)renderToTextureWithVertices:(const float *)arg1 textureCoordinates:(const float *)arg2;
- (id)initWithVertexShaderFromString:(id)arg1 fragmentShaderFromString:(id)arg2;

@end

