//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPImageDecoder.h"

@class NSArray;

@interface TuSDKCPGifDecoder : TuSDKCPImageDecoder
{
    struct _opaque_pthread_mutex_t {
        long long __sig;
        char __opaque[56];
    } _lock;
    _Bool _sourceTypeDetected;
    struct CGImageSource *_source;
    int _framesLock;
    NSArray *_frames;
    unsigned long long _frameCount;
    unsigned long long _loopCount;
    double _duration;
}

+ (id)decodeData:(id)arg1 scale:(double)arg2;
@property(readonly, nonatomic) double duration; // @synthesize duration=_duration;
@property(readonly, nonatomic) unsigned long long loopCount; // @synthesize loopCount=_loopCount;
@property(readonly, nonatomic) unsigned long long frameCount; // @synthesize frameCount=_frameCount;
- (void).cxx_destruct;
- (void)resetData;
- (struct CGImage *)_newUnblendedImageAtIndex:(unsigned long long)arg1 extendToCanvas:(_Bool)arg2 decoded:(_Bool *)arg3;
- (id)_frameAtIndex:(unsigned long long)arg1 shouldDecodeData:(_Bool)arg2;
- (void)parseData;
- (void)updateSource;
- (unsigned long long)detectImageType:(struct __CFData *)arg1;
- (_Bool)doUpdateData:(id)arg1 stopAppend:(_Bool)arg2;
- (double)frameDurationAtIndex:(unsigned long long)arg1;
- (id)frameAtIndex:(unsigned long long)arg1 shouldDecodeData:(_Bool)arg2;
- (_Bool)updateData:(id)arg1 stopAppend:(_Bool)arg2;
- (id)supportedTypes;
- (id)initWithScale:(double)arg1;

@end

