//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKICPagerHolderDelegate-Protocol.h"

@class TuSDKICPagerHolder, TuSDKICPagerView;

@protocol TuSDKICPagerViewDataSource <TuSDKICPagerHolderDelegate>
- (void)pagerView:(TuSDKICPagerView *)arg1 didShowPageIndex:(unsigned long long)arg2;
- (void)pagerView:(TuSDKICPagerView *)arg1 holder:(TuSDKICPagerHolder *)arg2 pageIndex:(unsigned long long)arg3;
- (unsigned long long)numberOfPagesInPagerView:(TuSDKICPagerView *)arg1;

@optional
- (void)didScrollEndWithPagerView:(TuSDKICPagerView *)arg1;
@end

