//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPImageResultController.h"

@class NSArray, TuSDKResult, UIView;
@protocol TuSDKICTouchImageViewInterface;

@interface TuSDKPFEditCuterControllerBase : TuSDKCPImageResultController
{
    struct CGRect _zoomRect;
    double _zoomScale;
    long long _imageOrientation;
    long long _currentRatioType;
    double _currentRatio;
    _Bool _onlyReturnCuter;
    UIView<TuSDKICTouchImageViewInterface> *_imageView;
    long long _ratioType;
    NSArray *_ratioTypeList;
    TuSDKResult *_cuterResult;
}

@property(nonatomic) double currentRatio; // @synthesize currentRatio=_currentRatio;
@property(nonatomic) double zoomScale; // @synthesize zoomScale=_zoomScale;
@property(nonatomic) struct CGRect zoomRect; // @synthesize zoomRect=_zoomRect;
@property(retain, nonatomic, setter=setCuterResult:) TuSDKResult *cuterResult; // @synthesize cuterResult=_cuterResult;
@property(nonatomic) _Bool onlyReturnCuter; // @synthesize onlyReturnCuter=_onlyReturnCuter;
@property(retain, nonatomic) NSArray *ratioTypeList; // @synthesize ratioTypeList=_ratioTypeList;
@property(nonatomic) long long ratioType; // @synthesize ratioType=_ratioType;
@property(readonly, nonatomic) UIView<TuSDKICTouchImageViewInterface> *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)asyncEditWithResult:(id)arg1;
- (void)onImageCompleteAtion;
- (void)viewDidLoad;
@property(nonatomic) long long currentRatioType;
- (id)getRatioTypes;

@end

