//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPImageResultOptions.h"

@protocol TuSDKPFStickerViewDelegate;

@interface TuSDKPFEditEntryOptions : TuSDKCPImageResultOptions
{
    _Bool _enableCuter;
    _Bool _enableFilter;
    _Bool _enableSticker;
    _Bool _limitForScreen;
    Class _viewClazz;
    unsigned long long _limitSideSize;
    id <TuSDKPFStickerViewDelegate> _stickerViewDelegate;
}

@property(nonatomic) __weak id <TuSDKPFStickerViewDelegate> stickerViewDelegate; // @synthesize stickerViewDelegate=_stickerViewDelegate;
@property(nonatomic) _Bool limitForScreen; // @synthesize limitForScreen=_limitForScreen;
@property(nonatomic) unsigned long long limitSideSize; // @synthesize limitSideSize=_limitSideSize;
@property(nonatomic) _Bool enableSticker; // @synthesize enableSticker=_enableSticker;
@property(nonatomic) _Bool enableFilter; // @synthesize enableFilter=_enableFilter;
@property(nonatomic) _Bool enableCuter; // @synthesize enableCuter=_enableCuter;
@property(retain, nonatomic) Class viewClazz; // @synthesize viewClazz=_viewClazz;
- (void).cxx_destruct;
- (id)viewController;
- (Class)defaultComponentClazz;

@end

