//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIScrollView;
@protocol TuSDKPFEditTextStyleAdjustDelegate;

@interface TuSDKPFEditTextStyleAdjustView : UIView
{
    UIScrollView *_backScroll;
    id <TuSDKPFEditTextStyleAdjustDelegate> _styleDelegate;
    NSArray *_styleImageNames;
    struct UIEdgeInsets _edgeInsets;
}

@property(nonatomic) struct UIEdgeInsets edgeInsets; // @synthesize edgeInsets=_edgeInsets;
@property(retain, nonatomic) NSArray *styleImageNames; // @synthesize styleImageNames=_styleImageNames;
@property(nonatomic) __weak id <TuSDKPFEditTextStyleAdjustDelegate> styleDelegate; // @synthesize styleDelegate=_styleDelegate;
- (void).cxx_destruct;
- (void)clickStyleBtnWith:(id)arg1;
- (id)getStyleNameWith:(unsigned long long)arg1;
- (void)resetStyleView;
- (void)initDefaultData;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

