//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TuSDKTSAssetsManager : NSObject
{
}

+ (_Bool)saveWithVideo:(id)arg1 toAblum:(id)arg2 completionBlock:(CDUnknownBlockType)arg3 ablumCompletionBlock:(CDUnknownBlockType)arg4;
+ (_Bool)saveWithImage:(id)arg1 compress:(double)arg2 metadata:(id)arg3 toAblum:(id)arg4 completionBlock:(CDUnknownBlockType)arg5 ablumCompletionBlock:(CDUnknownBlockType)arg6;
+ (void)imageAlbumsWithBlock:(CDUnknownBlockType)arg1;
+ (void)testLibraryAuthor:(CDUnknownBlockType)arg1;
+ (id)accessFailedInfo;
+ (void)showAlertWithController:(id)arg1 loadFailure:(id)arg2;
+ (id)assetsGroupsLoadFailure:(id)arg1;
+ (_Bool)notDetermined;
+ (_Bool)hasAuthor;
+ (id)sharedAssetsManager;

@end

