//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;
@protocol TuSDKPFEditWipeAndFilterConfigBarDelegate;

@interface TuSDKPFEditWipeAndFilterConfigBar : UIView
{
    UIButton *_smallSizeButton;
    UIButton *_mediumSizeButton;
    UIButton *_largeSizeButton;
    id <TuSDKPFEditWipeAndFilterConfigBarDelegate> _delegate;
}

@property(readonly, nonatomic) UIButton *largeSizeButton; // @synthesize largeSizeButton=_largeSizeButton;
@property(readonly, nonatomic) UIButton *mediumSizeButton; // @synthesize mediumSizeButton=_mediumSizeButton;
@property(readonly, nonatomic) UIButton *smallSizeButton; // @synthesize smallSizeButton=_smallSizeButton;
@property(nonatomic) __weak id <TuSDKPFEditWipeAndFilterConfigBarDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)notifySizeChangeEvent:(long long)arg1;
- (void)onButtonClicked:(id)arg1;
- (void)updateSizeButtonIcon:(id)arg1 iconName:(id)arg2 selected:(_Bool)arg3;
- (void)setBrushSize:(long long)arg1;
- (void)needUpdateLayout;
- (void)lsqInitView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

