//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TuSDKPFStickerFactory : NSObject
{
}

+ (void)appenTextLayout:(id)arg1 parentRect:(struct CGRect)arg2 context:(struct CGContext *)arg3 fontScale:(double)arg4 degree:(double)arg5;
+ (void)appendTextLayout:(id)arg1 size:(struct CGSize)arg2 context:(struct CGContext *)arg3 laySize:(struct CGSize)arg4;
+ (void)appendImageLayout:(id)arg1 size:(struct CGSize)arg2 context:(struct CGContext *)arg3 laySize:(struct CGSize)arg4;
+ (void)appendLayout:(id)arg1 size:(struct CGSize)arg2 context:(struct CGContext *)arg3;
+ (id)megerStickers:(id)arg1 image:(id)arg2;

@end

