//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPOptions.h"

@class NSArray;

@interface TuSDKPFStickerLocalOptions : TuSDKCPOptions
{
    Class _viewClazz;
    Class _cellViewClazz;
    Class _gridViewClazz;
    Class _cellHeaderViewClazz;
    Class _emptyViewClazz;
    NSArray *_categories;
}

@property(retain, nonatomic) NSArray *categories; // @synthesize categories=_categories;
@property(retain, nonatomic) Class emptyViewClazz; // @synthesize emptyViewClazz=_emptyViewClazz;
@property(retain, nonatomic) Class cellHeaderViewClazz; // @synthesize cellHeaderViewClazz=_cellHeaderViewClazz;
@property(retain, nonatomic) Class gridViewClazz; // @synthesize gridViewClazz=_gridViewClazz;
@property(retain, nonatomic) Class cellViewClazz; // @synthesize cellViewClazz=_cellViewClazz;
@property(retain, nonatomic) Class viewClazz; // @synthesize viewClazz=_viewClazz;
- (void).cxx_destruct;
- (id)viewController;
- (Class)defaultComponentClazz;

@end

