//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class TuSDKICMaskRegionView, TuSDKPFEditStickerBottomBar, TuSDKPFStickerBarView, TuSDKPFStickerView, UIImageView;

@interface TuSDKPFEditStickerView : UIView
{
    UIImageView *_imageView;
    TuSDKICMaskRegionView *_cutRegionView;
    TuSDKPFStickerView *_stickerView;
    TuSDKPFStickerBarView *_stickerBar;
    TuSDKPFEditStickerBottomBar *_bottomBar;
}

@property(readonly, nonatomic) TuSDKPFEditStickerBottomBar *bottomBar; // @synthesize bottomBar=_bottomBar;
@property(readonly, nonatomic) TuSDKPFStickerBarView *stickerBar; // @synthesize stickerBar=_stickerBar;
@property(readonly, nonatomic) TuSDKPFStickerView *stickerView; // @synthesize stickerView=_stickerView;
@property(readonly, nonatomic) TuSDKICMaskRegionView *cutRegionView; // @synthesize cutRegionView=_cutRegionView;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)setImage:(id)arg1;
- (void)needUpdateLayout;
- (void)lsqInitView;

@end

