//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TuSDKPFTextItemViewInterface-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSMutableParagraphStyle, NSString, TuSDKPFSticker, TuSDKPFTextLabel, UIButton, UIColor, UIFont, UILabel, UIPanGestureRecognizer, UIPinchGestureRecognizer, UIRotationGestureRecognizer;
@protocol TuSDKPFTextItemViewDelegate;

@interface TuSDKPFTextItemView : UIView <UIGestureRecognizerDelegate, TuSDKPFTextItemViewInterface>
{
    TuSDKPFTextLabel *_textView;
    UIButton *_cancelButton;
    UIButton *_turnButton;
    UIButton *_stretchButton;
    struct UIEdgeInsets _mImageEdge;
    struct CGSize _mCSize;
    struct CGSize _mCMargin;
    struct CGSize _textViewMargin;
    double _mMaxScale;
    struct CGSize _mDefaultViewSize;
    double _mCHypotenuse;
    double _mDefaultFontSize;
    UIFont *_textFont;
    NSMutableDictionary *_textStyleDic;
    double _mScale;
    double _mDegree;
    NSMutableArray *_mTextViews;
    _Bool _isRotatScaleAction;
    _Bool _isStretchAction;
    UIPanGestureRecognizer *_panGesture;
    UIRotationGestureRecognizer *_rotationGesture;
    UIPinchGestureRecognizer *_pinchGesture;
    struct CGPoint _lastPotion;
    _Bool _hasTouched;
    _Bool _isInGesture;
    _Bool _selected;
    _Bool _enableUnderline;
    id <TuSDKPFTextItemViewDelegate> _delegate;
    double _minScale;
    double _textBorderWidth;
    UIColor *_textBorderColor;
    UIColor *_textColor;
    NSString *_textString;
    TuSDKPFSticker *_textSticker;
    NSMutableParagraphStyle *_textParaStyle;
    NSArray *_writingDirection;
    long long _textAlignment;
    UIColor *_textBackgroudColor;
    UIColor *_textStrokeColor;
    double _textMaxScale;
    struct UIEdgeInsets _textEdgeInsets;
}

@property(nonatomic) double textMaxScale; // @synthesize textMaxScale=_textMaxScale;
@property(nonatomic) struct UIEdgeInsets textEdgeInsets; // @synthesize textEdgeInsets=_textEdgeInsets;
@property(retain, nonatomic) UIColor *textStrokeColor; // @synthesize textStrokeColor=_textStrokeColor;
@property(retain, nonatomic) UIColor *textBackgroudColor; // @synthesize textBackgroudColor=_textBackgroudColor;
@property(nonatomic) long long textAlignment; // @synthesize textAlignment=_textAlignment;
@property(retain, nonatomic) NSArray *writingDirection; // @synthesize writingDirection=_writingDirection;
@property(nonatomic) _Bool enableUnderline; // @synthesize enableUnderline=_enableUnderline;
@property(retain, nonatomic) NSMutableParagraphStyle *textParaStyle; // @synthesize textParaStyle=_textParaStyle;
@property(retain, nonatomic) TuSDKPFSticker *textSticker; // @synthesize textSticker=_textSticker;
@property(retain, nonatomic) NSString *textString; // @synthesize textString=_textString;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) UIColor *textBorderColor; // @synthesize textBorderColor=_textBorderColor;
@property(nonatomic) double textBorderWidth; // @synthesize textBorderWidth=_textBorderWidth;
@property(nonatomic) double minScale; // @synthesize minScale=_minScale;
@property(nonatomic) __weak id <TuSDKPFTextItemViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UIButton *stretchButton; // @synthesize stretchButton=_stretchButton;
@property(readonly, nonatomic) UIButton *turnButton; // @synthesize turnButton=_turnButton;
@property(readonly, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(readonly, nonatomic) UILabel *textView; // @synthesize textView=_textView;
- (void).cxx_destruct;
- (void)dealloc;
- (void)loginfo:(id)arg1;
- (struct CGRect)centerOfParentRegin:(struct CGRect)arg1;
- (id)imageWithTextView:(id)arg1;
- (id)resultWithRegionRect:(struct CGRect)arg1;
- (void)computerScaleWithScale:(double)arg1 center:(struct CGPoint)arg2;
- (void)computerScaleWithPoint:(struct CGPoint)arg1 lastPoint:(struct CGPoint)arg2 center:(struct CGPoint)arg3;
- (void)computerAngleWithPoint:(struct CGPoint)arg1 lastPoint:(struct CGPoint)arg2 center:(struct CGPoint)arg3;
- (void)handlePanGestureRotatScaleAction:(struct CGPoint)arg1;
- (void)handlePanGestureStretchAction:(struct CGPoint)arg1;
- (struct CGPoint)fixedCenterPoint:(struct CGPoint)arg1;
- (void)handlePanGestureTransAction:(struct CGPoint)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)handlePinchGesture:(id)arg1;
- (void)handleRotationGesture:(id)arg1;
- (void)handlePanGesture:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)removeGestureRecognizer;
- (void)appendGestureRecognizer;
- (void)handleCancelButton;
- (void)resetTextFont:(id)arg1;
- (void)resetViewsBounds;
- (void)resetTextEdge;
- (void)resetBasicInfo;
- (void)initStickerPostion;
- (void)initDefaultData;
- (void)lsqInitView;
- (void)initWithTextFont:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)viewWillDestory;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

