//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPGroupFilterGroupCellBase.h"

@class UIButton, UIImageView, UILabel, UIView;

@interface TuSDKCPGroupFilterGroupCell : TuSDKCPGroupFilterGroupCellBase
{
    UIView *_wrapView;
    UIImageView *_thumbView;
    UIView *_thumbMaskView;
    UILabel *_titleView;
    UIView *_selectedView;
    UIImageView *_iconView;
    UIButton *_removeButton;
    UIView *_flagView;
}

@property(readonly, nonatomic) UIButton *removeButton; // @synthesize removeButton=_removeButton;
@property(readonly, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(readonly, nonatomic) UIView *selectedView; // @synthesize selectedView=_selectedView;
@property(readonly, nonatomic) UIView *flagView; // @synthesize flagView=_flagView;
@property(readonly, nonatomic) UILabel *titleView; // @synthesize titleView=_titleView;
@property(readonly, nonatomic) UIView *wrapView; // @synthesize wrapView=_wrapView;
- (void).cxx_destruct;
- (void)onRemoveConfirm;
- (void)handleRemoveButton;
- (void)cancelRemoveFlag;
- (void)startRemoveAnim;
- (void)stopActivating;
- (void)waitInActivate:(double)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)viewNeedRest;
- (void)setImageColor:(id)arg1;
- (void)handleBlockView:(id)arg1 icon:(id)arg2;
- (void)handleTypeOnlie:(id)arg1;
- (void)handleTypeHistory:(id)arg1;
- (void)handleTypeFilter:(id)arg1;
- (void)handleTypeGroup:(id)arg1;
- (void)handleTypeOrgin:(id)arg1;
- (void)setSelectedIcon:(id)arg1 needIcon:(_Bool)arg2;
- (void)setMode:(id)arg1;
- (id)thumbView;
- (id)lsqSetSize:(struct CGSize)arg1;
- (void)lsqInitView;

@end

