//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface TuSDKICGuideRegionView : UIView
{
    struct CGRect _regionRect;
    _Bool _displayGuideLine;
    UIColor *_guideLineColor;
    double _guideLineWidth;
    struct CGRect _displayRect;
}

@property(nonatomic) struct CGRect displayRect; // @synthesize displayRect=_displayRect;
@property(nonatomic) _Bool displayGuideLine; // @synthesize displayGuideLine=_displayGuideLine;
@property(nonatomic) double guideLineWidth; // @synthesize guideLineWidth=_guideLineWidth;
@property(retain, nonatomic) UIColor *guideLineColor; // @synthesize guideLineColor=_guideLineColor;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)lsqInitView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

