//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKGaussianBlurFiveRadiusFilter.h"

@interface TuSDKGaussianBilateralFilter : TuSDKGaussianBlurFiveRadiusFilter
{
    double firstDistanceNormalizationFactorUniform;
    double secondDistanceNormalizationFactorUniform;
    double firstWeightTypeUniform;
    double secondWeightTypeUniform;
    double _distanceNormalizationFactor;
    double _bilateralWeightType;
}

@property(nonatomic) double bilateralWeightType; // @synthesize bilateralWeightType=_bilateralWeightType;
@property(nonatomic) double distanceNormalizationFactor; // @synthesize distanceNormalizationFactor=_distanceNormalizationFactor;
- (id)initWithVertexShaderFromString:(id)arg1 fragmentShaderFromString:(id)arg2;
- (id)initOnPerformance;
- (id)init;

@end

