//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, TuSDKFilterWrap, TuSDKICMaskRegionView, TuSDKPFStickerView, UIImage, UIView;
@protocol TuSDKICFilterImageViewInterface;

@protocol TuSDKCPFilterStickerViewInterface <NSObject>
@property(readonly, nonatomic) UIView<TuSDKICFilterImageViewInterface> *filterView;
@property(readonly, nonatomic) TuSDKPFStickerView *stickerView;
@property(readonly, nonatomic) TuSDKICMaskRegionView *cutRegionView;
- (NSArray *)stickerResults;
- (void)setFilterWrap:(TuSDKFilterWrap *)arg1;
- (void)setImage:(UIImage *)arg1;
- (void)needUpdateLayout;
@end

