//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPImageResultController.h"

@class NSString, UIImage, UIView;
@protocol TuSDKICTouchImageViewInterface;

@interface TuSDKPFEditTurnAndCutViewControllerBase : TuSDKCPImageResultController
{
    NSString *_selectedFilterCode;
    UIImage *_cachedOriginalImage;
    UIView<TuSDKICTouchImageViewInterface> *_imageView;
    struct CGSize _cutSize;
}

@property(nonatomic) struct CGSize cutSize; // @synthesize cutSize=_cutSize;
@property(readonly, nonatomic) UIView<TuSDKICTouchImageViewInterface> *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)dealloc;
- (void)asyncEditWithResult:(id)arg1;
- (void)onImageCompleteAtion;
- (void)loadedInputImage:(id)arg1;
- (id)inputImage;
- (void)processedFilter:(id)arg1;
- (void)asyncProcessingFilter:(id)arg1;
- (_Bool)onSelectedFilterCode:(id)arg1;
- (void)viewDidLoad;

@end

