//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIViewController;

@interface TuSDKTSDeviceSettings : NSObject
{
    CDUnknownBlockType _completed;
    long long _type;
    UIViewController *_controller;
}

+ (id)shared;
+ (void)checkAllowWithController:(id)arg1 type:(long long)arg2 completed:(CDUnknownBlockType)arg3;
@property(nonatomic) UIViewController *controller; // @synthesize controller=_controller;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(copy, nonatomic) CDUnknownBlockType completed; // @synthesize completed=_completed;
- (void).cxx_destruct;
- (void)notifyResult:(_Bool)arg1;
- (void)showSettingDisableMessage:(id)arg1 title:(id)arg2;
- (void)handleSettingsLocation;
- (void)handleSettingsCamera;
- (void)showPhotosDisableMessage;
- (void)handleSettingsPhoto;
- (void)checkAllowType:(long long)arg1;

@end

