//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKThreeInputFilter.h"

#import "TuSDKFilterParameterProtocol-Protocol.h"

@class NSString, TuSDKFilterParameter;

@interface TuSDKGPUColorHDRFilter : TuSDKThreeInputFilter <TuSDKFilterParameterProtocol>
{
    int clipXUniform;
    int clipYUniform;
    int strengthUniform;
    double _clipX;
    double _clipY;
    float _strength;
    TuSDKFilterParameter *_parameter;
}

@property(nonatomic) float strength; // @synthesize strength=_strength;
- (void).cxx_destruct;
- (void)submitParameter:(id)arg1;
- (void)submitParameter;
@property(retain, nonatomic) TuSDKFilterParameter *parameter; // @synthesize parameter=_parameter;
- (void)submitFilterArg:(id)arg1;
- (id)configParams:(id)arg1;
- (void)setClipY:(double)arg1;
- (void)setClipX:(double)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

