//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface TuSDKCircularProgressView : UIView
{
    float _progress;
    UIColor *_backColor;
    UIColor *_progressColor;
    double _lineWidth;
}

@property(nonatomic) float progress; // @synthesize progress=_progress;
@property(nonatomic) double lineWidth; // @synthesize lineWidth=_lineWidth;
@property(retain, nonatomic) UIColor *progressColor; // @synthesize progressColor=_progressColor;
@property(retain, nonatomic) UIColor *backColor; // @synthesize backColor=_backColor;
- (void).cxx_destruct;
- (void)updateProgressCircle:(float)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 backColor:(id)arg2 progressColor:(id)arg3 lineWidth:(double)arg4;
- (id)initWithFrame:(struct CGRect)arg1;

@end

