//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKTween.h"

@interface TuSDKTweenElastic : TuSDKTween
{
    float _period;
    float _amplitude;
}

@property(nonatomic) float period; // @synthesize period=_period;
@property(nonatomic) float amplitude; // @synthesize amplitude=_amplitude;
- (double)speed;

@end

