//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPImageResultOptions.h"

@class NSArray;
@protocol TuSDKPFStickerViewDelegate;

@interface TuSDKPFEditStickerOptions : TuSDKCPImageResultOptions
{
    Class _viewClazz;
    unsigned long long _gridWidth;
    unsigned long long _gridHeight;
    long long _gridPadding;
    Class _gridViewClazz;
    NSArray *_categories;
    id <TuSDKPFStickerViewDelegate> _stickerViewDelegate;
}

@property(nonatomic) __weak id <TuSDKPFStickerViewDelegate> stickerViewDelegate; // @synthesize stickerViewDelegate=_stickerViewDelegate;
@property(retain, nonatomic) NSArray *categories; // @synthesize categories=_categories;
@property(retain, nonatomic) Class gridViewClazz; // @synthesize gridViewClazz=_gridViewClazz;
@property(nonatomic) long long gridPadding; // @synthesize gridPadding=_gridPadding;
@property(nonatomic) unsigned long long gridHeight; // @synthesize gridHeight=_gridHeight;
@property(nonatomic) unsigned long long gridWidth; // @synthesize gridWidth=_gridWidth;
@property(retain, nonatomic) Class viewClazz; // @synthesize viewClazz=_viewClazz;
- (void).cxx_destruct;
- (id)viewController;
- (Class)defaultComponentClazz;
- (void)initOptions;

@end

