//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, TuSDKFilterOption, UIImage, UIViewController;
@protocol TuSDKCPGroupFilterBarDelegate;

@protocol TuSDKCPGroupFilterBarInterface <NSObject>
@property(nonatomic) _Bool isRenderFilterThumb;
@property(retain, nonatomic) Class onlineControllerClazz;
@property(nonatomic) _Bool enableHistory;
@property(nonatomic) UIViewController *controller;
@property(nonatomic) _Bool enableOnlineFilter;
@property(nonatomic) _Bool enableNormalFilter;
@property(nonatomic) _Bool allowsSelection;
@property(retain, nonatomic) NSArray *filterGroup;
@property(nonatomic) _Bool autoSelectGroupDefaultFilter;
@property(nonatomic) _Bool saveLastFilter;
@property(retain, nonatomic) Class filterTableCellClazz;
@property(retain, nonatomic) Class groupTableCellClazz;
@property(nonatomic) double stackViewWidth;
@property(nonatomic) double cellWidth;
@property(nonatomic) _Bool enableFilterConfig;
@property(nonatomic) long long action;
@property(nonatomic) __weak id <TuSDKCPGroupFilterBarDelegate> delegate;
- (void)exitRemoveState;
- (void)removeWithGroupId:(unsigned long long)arg1;
- (void)loadFiltersWithOption:(TuSDKFilterOption *)arg1;
- (void)loadFilters;
- (void)setThumbImage:(UIImage *)arg1;
@end

