//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKGPUSkinColorFilter.h"

#import "TuSDKFilterParameterProtocol-Protocol.h"
#import "TuSDKFilterTexturesProtocol-Protocol.h"

@class NSString, TuSDKFilterParameter;

@interface TuSDKGPUSkinSmoothFilter : TuSDKGPUSkinColorFilter <TuSDKFilterParameterProtocol, TuSDKFilterTexturesProtocol>
{
    TuSDKFilterParameter *_parameter;
}

@property(retain, nonatomic) TuSDKFilterParameter *parameter; // @synthesize parameter=_parameter;
- (void).cxx_destruct;
- (id)configParams:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

