//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TuSDKCPFilterOnlineControllerDelegate-Protocol.h"
#import "TuSDKCPGroupFilterGroupCellDelegate-Protocol.h"
#import "TuSDKCPStackFilterBarInterface-Protocol.h"
#import "TuSDKCPStackFilterTableViewDelegate-Protocol.h"
#import "TuSDKFilterLocalPackageDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, TuSDKFilterOption, UIViewController;
@protocol TuSDKCPStackFilterBarDelegate, TuSDKCPStackFilterTableViewInterface, TuSDKTKFiltersTaskInterface;

@interface TuSDKCPStackFilterBarBase : UIView <TuSDKFilterLocalPackageDelegate, TuSDKCPStackFilterTableViewDelegate, TuSDKCPGroupFilterGroupCellDelegate, TuSDKCPFilterOnlineControllerDelegate, TuSDKCPStackFilterBarInterface>
{
    TuSDKFilterOption *_lastOption;
    _Bool _mNeedSelected;
    double _mGroupItemCenter;
    unsigned long long _mHistoryTotal;
    NSMutableArray *_mHistories;
    unsigned long long _lastFilterId;
    id <TuSDKTKFiltersTaskInterface> _filterTask;
    _Bool _saveLastFilter;
    _Bool _autoSelectGroupDefaultFilter;
    _Bool _allowsSelection;
    _Bool _enableFilterConfig;
    _Bool _enableNormalFilter;
    _Bool _enableOnlineFilter;
    _Bool _enableHistory;
    UIView<TuSDKCPStackFilterTableViewInterface> *_filterTable;
    id <TuSDKCPStackFilterBarDelegate> _delegate;
    long long _action;
    double _cellWidth;
    double _stackViewWidth;
    Class _filterTableCellClazz;
    Class _stackViewClazz;
    NSArray *_filterGroup;
    UIViewController *_controller;
    Class _onlineControllerClazz;
}

@property(retain, nonatomic) Class onlineControllerClazz; // @synthesize onlineControllerClazz=_onlineControllerClazz;
@property(nonatomic) _Bool enableHistory; // @synthesize enableHistory=_enableHistory;
@property(nonatomic) UIViewController *controller; // @synthesize controller=_controller;
@property(nonatomic) _Bool enableOnlineFilter; // @synthesize enableOnlineFilter=_enableOnlineFilter;
@property(nonatomic) _Bool enableNormalFilter; // @synthesize enableNormalFilter=_enableNormalFilter;
@property(nonatomic) _Bool enableFilterConfig; // @synthesize enableFilterConfig=_enableFilterConfig;
@property(nonatomic) _Bool allowsSelection; // @synthesize allowsSelection=_allowsSelection;
@property(retain, nonatomic) NSArray *filterGroup; // @synthesize filterGroup=_filterGroup;
@property(nonatomic) _Bool autoSelectGroupDefaultFilter; // @synthesize autoSelectGroupDefaultFilter=_autoSelectGroupDefaultFilter;
@property(nonatomic) _Bool saveLastFilter; // @synthesize saveLastFilter=_saveLastFilter;
@property(retain, nonatomic) Class stackViewClazz; // @synthesize stackViewClazz=_stackViewClazz;
@property(retain, nonatomic) Class filterTableCellClazz; // @synthesize filterTableCellClazz=_filterTableCellClazz;
@property(nonatomic) double stackViewWidth; // @synthesize stackViewWidth=_stackViewWidth;
@property(nonatomic) double cellWidth; // @synthesize cellWidth=_cellWidth;
@property(nonatomic) long long action; // @synthesize action=_action;
@property(nonatomic) __weak id <TuSDKCPStackFilterBarDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UIView<TuSDKCPStackFilterTableViewInterface> *filterTable; // @synthesize filterTable=_filterTable;
- (void).cxx_destruct;
- (void)onTuSDKStickerOnline:(id)arg1 selectedGroupId:(unsigned long long)arg2;
- (void)setGroupRemoveState:(_Bool)arg1;
- (void)exitRemoveState;
- (void)removeWithGroupId:(unsigned long long)arg1;
- (void)onFilterGroupViewClick:(id)arg1 mode:(id)arg2 enableStack:(_Bool)arg3;
- (void)showFilterTableWithCenterX:(double)arg1 showed:(_Bool)arg2;
- (void)onFilterGroupCellRemove:(id)arg1;
- (void)onFilterGroupCellLongClick:(id)arg1;
- (id)buildGroupItemsInActingType;
- (long long)getFirstNormalIndexWithGroups:(id)arg1;
- (long long)getRowWithGroups:(id)arg1 groupId:(unsigned long long)arg2;
- (long long)getIndexWithGroups:(id)arg1 groupId:(unsigned long long)arg2;
- (void)handleGroupRemoveWithItem:(id)arg1;
- (void)handleGroupAppendWithItem:(id)arg1;
- (void)filterManager:(id)arg1 item:(id)arg2 changedStatus:(long long)arg3;
- (void)handleOnlineAction;
- (void)saveHistoryFilterWithOption:(id)arg1;
- (id)loadHistoryFilters;
- (void)saveLastFilterWithOption:(id)arg1;
- (id)loadLastFilter;
- (_Bool)onFilterItemSelecedCell:(id)arg1 mode:(id)arg2 indexPath:(id)arg3;
- (id)onFilterOption;
- (void)handleGroupOrginWithCell:(id)arg1 mode:(id)arg2 indexPath:(id)arg3;
- (id)buildGroupItems;
- (id)buildGroupItemsOutIndex:(id)arg1;
- (void)bindGroupData;
- (void)bindFiltersData;
- (void)loadFilters;
- (void)loadFiltersWithOption:(id)arg1;
- (_Bool)onTuSDKCPGroupFilterTableView:(id)arg1 selectedCell:(id)arg2 model:(id)arg3 indexPath:(id)arg4;
- (_Bool)notifyDelegateWithMode:(id)arg1 cell:(id)arg2;
- (void)notifyDelegateWithOption:(id)arg1;
- (id)lsqSetSizeHeight:(double)arg1;
@property(nonatomic) _Bool isRenderFilterThumb;
- (void)setThumbImage:(id)arg1;
- (void)viewWillDestory;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

