//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TuSDKTSPixSort : NSObject
{
    unsigned long long _red;
    unsigned long long _green;
    unsigned long long _blue;
    unsigned long long _alpha;
}

+ (id)initWithRed:(unsigned long long)arg1 green:(unsigned long long)arg2 blue:(unsigned long long)arg3 alpha:(unsigned long long)arg4;
@property(nonatomic) unsigned long long alpha; // @synthesize alpha=_alpha;
@property(nonatomic) unsigned long long blue; // @synthesize blue=_blue;
@property(nonatomic) unsigned long long green; // @synthesize green=_green;
@property(nonatomic) unsigned long long red; // @synthesize red=_red;
- (unsigned long long)total;
- (void)setRed:(unsigned long long)arg1 green:(unsigned long long)arg2 blue:(unsigned long long)arg3 alpha:(unsigned long long)arg4;
- (id)_initWithRed:(unsigned long long)arg1 green:(unsigned long long)arg2 blue:(unsigned long long)arg3 alpha:(unsigned long long)arg4;

@end

