//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TuSDKStickerAnimationItem : NSObject
{
    unsigned int _textureID;
    unsigned long long _imageWidth;
}

@property(readonly, nonatomic) unsigned int textureID; // @synthesize textureID=_textureID;
@property(readonly, nonatomic) unsigned long long imageWidth; // @synthesize imageWidth=_imageWidth;
- (id)initWithTextueID:(unsigned int)arg1 imageWidth:(unsigned long long)arg2;

@end

