//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UIActionSheetDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, UIViewController;

@interface TuSDKICAlertView : NSObject <UIActionSheetDelegate>
{
    NSMutableArray *_actions;
    NSString *_title;
    NSString *_message;
    long long _preferredStyle;
    UIViewController *_controller;
}

+ (id)actionSheetWithController:(id)arg1 title:(id)arg2 message:(id)arg3;
+ (id)alertWithController:(id)arg1 title:(id)arg2 message:(id)arg3;
+ (void)alertShowConfigWithController:(id)arg1 title:(id)arg2 message:(id)arg3;
+ (void)alertShowWithController:(id)arg1 title:(id)arg2 message:(id)arg3 cancelTitle:(id)arg4;
+ (void)alertShowWithController:(id)arg1 message:(id)arg2 cancelTitle:(id)arg3;
+ (void)alertShowWithController:(id)arg1 title:(id)arg2 message:(id)arg3;
+ (void)alertShowWithController:(id)arg1 message:(id)arg2;
@property(nonatomic) UIViewController *controller; // @synthesize controller=_controller;
@property(readonly, nonatomic) long long preferredStyle; // @synthesize preferredStyle=_preferredStyle;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) NSArray *actions; // @synthesize actions=_actions;
- (void).cxx_destruct;
- (long long)uiAlertControllerStyle;
- (void)handleActionWithIndex:(long long)arg1;
- (void)showAlertController;
- (void)handleCancelAction;
- (void)alertViewCancel:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showAlertView;
- (void)showAlert;
- (void)actionSheetCancel:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showActionSheetView;
- (void)showActionSheet;
- (void)show;
- (void)addAction:(id)arg1;
- (id)initWithController:(id)arg1 title:(id)arg2 message:(id)arg3 preferredStyle:(long long)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

