//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPImageResultController.h"

#import "TuSDKICSmudgeImageViewDelegate-Protocol.h"

@class NSObject, NSString, UIImageView, UIView;
@protocol OS_dispatch_queue, TuSDKICSmudgeImageViewInterface;

@interface TuSDKPFEditWipeAndFilterControllerBase : TuSDKCPImageResultController <TuSDKICSmudgeImageViewDelegate>
{
    NSObject<OS_dispatch_queue> *taskQueue;
    _Bool _displayMagnifier;
    UIView<TuSDKICSmudgeImageViewInterface> *_smudgeView;
    double _brushStrength;
    UIImageView *_zoomInPreviewImage;
    unsigned long long _currentBrushSize;
}

@property(nonatomic) unsigned long long currentBrushSize; // @synthesize currentBrushSize=_currentBrushSize;
@property(readonly, nonatomic) UIImageView *zoomInPreviewImage; // @synthesize zoomInPreviewImage=_zoomInPreviewImage;
@property(nonatomic) double brushStrength; // @synthesize brushStrength=_brushStrength;
@property(nonatomic) _Bool displayMagnifier; // @synthesize displayMagnifier=_displayMagnifier;
@property(readonly, nonatomic) UIView<TuSDKICSmudgeImageViewInterface> *smudgeView; // @synthesize smudgeView=_smudgeView;
- (void).cxx_destruct;
- (void)dealloc;
- (void)asyncEditWithResult:(id)arg1;
- (void)onImageCompleteAction;
- (void)onAsyncImageLoaded:(id)arg1;
- (void)onSmudgeActionEnd;
- (void)updateZoomInImage:(struct CGPoint)arg1 viewLocation:(struct CGPoint)arg2;
- (void)onSmudgeActionChanged:(struct CGPoint)arg1 viewLocation:(struct CGPoint)arg2 canvasWidth:(double)arg3 canvasHeight:(double)arg4;
- (void)onRefreshStepStatesWithHistories:(unsigned long long)arg1 redoCount:(unsigned long long)arg2;
- (void)onOriginalActionEnd;
- (void)onOriginalActionStart;
- (void)onRedoAction;
- (void)onUndoAction;
- (id)_buildfilterWrap;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

