//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TuSDKCPSubtitlesViewInterface-Protocol.h"

@class NSString, UILabel;

@interface TuSDKCPSubtitlesView : UIView <TuSDKCPSubtitlesViewInterface>
{
    UILabel *_titleView;
    UILabel *_subTitleView;
}

@property(readonly, nonatomic) UILabel *subTitleView; // @synthesize subTitleView=_subTitleView;
@property(readonly, nonatomic) UILabel *titleView; // @synthesize titleView=_titleView;
- (void).cxx_destruct;
- (void)setViewHidden;
- (void)setTitle:(id)arg1 subTitle:(id)arg2;
- (void)lsqInitView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

