//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuSDKCPImageResultController.h"

#import "TuSDKICSmudgeImageViewDelegate-Protocol.h"

@class NSString, TuSDKPFBrush, UIView;
@protocol TuSDKICSmudgeImageViewInterface;

@interface TuSDKPFEditSmudgeControllerBase : TuSDKCPImageResultController <TuSDKICSmudgeImageViewDelegate>
{
    TuSDKPFBrush *_brush;
    UIView<TuSDKICSmudgeImageViewInterface> *_smudgeView;
}

@property(readonly, nonatomic) UIView<TuSDKICSmudgeImageViewInterface> *smudgeView; // @synthesize smudgeView=_smudgeView;
@property(retain, nonatomic) TuSDKPFBrush *brush; // @synthesize brush=_brush;
- (void).cxx_destruct;
- (void)dealloc;
- (void)asyncEditWithResult:(id)arg1;
- (void)onImageCompleteAction;
- (void)onSmudgeActionEnd;
- (void)onSmudgeActionChanged:(struct CGPoint)arg1 viewLocation:(struct CGPoint)arg2 canvasWidth:(double)arg3 canvasHeight:(double)arg4;
- (void)onRefreshStepStatesWithHistories:(unsigned long long)arg1 redoCount:(unsigned long long)arg2;
- (void)onOriginalActionEnd;
- (void)onOriginalActionStart;
- (void)onRedoAction;
- (void)onUndoAction;
- (_Bool)selectBrushCode:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

