//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol TuSDKOnlineStickerFetcherDelegate;

@interface TuSDKOnlineStickerFetcher : NSObject
{
    id <TuSDKOnlineStickerFetcherDelegate> _delegate;
}

@property(nonatomic) __weak id <TuSDKOnlineStickerFetcherDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)notifyFetchFailed;
- (void)notifyStickerGroups:(id)arg1;
- (void)onResponseStickerGroups:(id)arg1 arg:(id)arg2;
- (void)fetchStickGroupsWithCursor:(unsigned long long)arg1 isSmart:(_Bool)arg2;

@end

