//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, UIScrollView;

@interface TuSDKPFEditMultipleOptionBar : UIView
{
    UIScrollView *_wrapView;
    NSMutableArray *_buttons;
}

@property(readonly, nonatomic) UIScrollView *wrapView; // @synthesize wrapView=_wrapView;
- (void).cxx_destruct;
- (void)needUpdateLayout;
- (id)buildButtonWithActionType:(long long)arg1 moduleCount:(unsigned long long)arg2;
- (void)bindModules:(id)arg1 target:(id)arg2 action:(SEL)arg3;
- (void)lsqInitView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

