//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TuSDKCPFilterResultViewInterface-Protocol.h"

@class NSString, TuSDKPFEditFilterBottomBar;
@protocol TuSDKCPParameterConfigViewInterface, TuSDKICFilterImageViewInterface;

@interface TuSDKCPFilterResultView : UIView <TuSDKCPFilterResultViewInterface>
{
    UIView<TuSDKICFilterImageViewInterface> *_imageView;
    UIView<TuSDKCPParameterConfigViewInterface> *_configView;
    TuSDKPFEditFilterBottomBar *_bottomBar;
}

@property(readonly, nonatomic) TuSDKPFEditFilterBottomBar *bottomBar; // @synthesize bottomBar=_bottomBar;
@property(readonly, nonatomic) UIView<TuSDKCPParameterConfigViewInterface> *configView; // @synthesize configView=_configView;
@property(readonly, nonatomic) UIView<TuSDKICFilterImageViewInterface> *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)lsqInitView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

