//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (ImageExtend)
+ (id)lsqDecodedImageWithImage:(id)arg1;
+ (_Bool)lsqSizeTransposed:(long long)arg1;
+ (id)lsqCreateRectImage:(struct CGSize)arg1 fillColor:(id)arg2;
+ (id)lsqCreateOvalImage:(unsigned long long)arg1 fillColor:(id)arg2;
+ (id)lsqImageFromColor:(id)arg1;
- (void)updateChannelInfo:(int *)arg1 value:(unsigned int)arg2 reverseValue:(unsigned int)arg3 index:(int)arg4 pixelsNum:(unsigned long long)arg5;
- (id)lsqGetBitmapHistRange;
- (unsigned int *)lsqGetBitmapHistList;
- (char *)lsqGetBitmapClipHistListWithClipX:(unsigned long long)arg1 ClipY:(unsigned long long)arg2 fLimit:(double)arg3;
- (id)lsqScaledImageForKey:(id)arg1;
- (_Bool)lsqSizeTransposed;
- (id)lsqWriteExifWithData:(id)arg1 meta:(id)arg2;
- (id)lsqJpegDataWithCompress:(double)arg1 meta:(id)arg2;
- (id)lsqMergeAboveImage:(id)arg1;
- (id)lsqChangeOrientation:(long long)arg1;
- (id)lsqFullScreenImageKeepOrientation;
- (id)lsqFullScreenImage;
- (id)lsqImageCorpWithRatio:(double)arg1;
- (id)lsqImageRotatedToUp;
- (id)lsqImageScale:(double)arg1;
- (id)lsqImageLimit:(double)arg1;
- (id)lsqScaleGeometricAndRotate:(struct CGSize)arg1;
- (id)lsqScaleImage:(struct CGSize)arg1;
@end

