//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (ResizeAndRotate)
+ (struct CGAffineTransform)lsqTransformForOrientation:(long long)arg1 size:(struct CGSize)arg2;
- (struct CGAffineTransform)lsqTransformForOrientation:(struct CGSize)arg1;
- (struct CGRect)lsqComputerRatio:(double)arg1 resize:(struct CGSize)arg2 orientation:(long long)arg3;
- (struct CGSize)lsqComputerMaximumSize:(struct CGSize)arg1;
- (struct CGSize)lsqComputerMinimalSize:(struct CGSize)arg1;
- (id)lsqImageResize:(struct CGSize)arg1 transform:(struct CGAffineTransform)arg2 drawTransposed:(_Bool)arg3 interpolationQuality:(int)arg4 ratioRect:(struct CGRect)arg5;
- (id)lsqImageResize:(struct CGSize)arg1 orientation:(long long)arg2 baseLongSide:(_Bool)arg3 interpolationQuality:(int)arg4 ratio:(double)arg5;
- (id)lsqImageResize:(struct CGSize)arg1 orientation:(long long)arg2 baseLongSide:(_Bool)arg3 ratio:(double)arg4;
- (id)lsqImageResize:(struct CGSize)arg1 baseLongSide:(_Bool)arg2 ratio:(double)arg3;
- (id)lsqImageResize:(struct CGSize)arg1 baseLongSide:(_Bool)arg2 interpolationQuality:(int)arg3;
- (id)lsqImageResize:(struct CGSize)arg1 orientation:(long long)arg2 baseLongSide:(_Bool)arg3;
- (id)lsqImageResize:(struct CGSize)arg1 baseLongSide:(_Bool)arg2;
@end

