//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (ImageCorp)
- (struct CGRect)lsqFixedCorpRect:(struct CGRect)arg1 orientation:(long long)arg2;
- (id)lsqImageCorpWithSize:(struct CGSize)arg1 rect:(struct CGRect)arg2 outputSize:(struct CGSize)arg3 orientation:(long long)arg4 interpolationQuality:(int)arg5;
- (id)lsqImageCorpWithPrecentRect:(struct CGRect)arg1 outputSize:(struct CGSize)arg2;
- (id)lsqImageCorpWithPrecentRect:(struct CGRect)arg1;
- (id)lsqImageCorpResizeWithSize:(struct CGSize)arg1;
@end

