//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

@interface UIImageView (TuSDKNetworkAdditions)
+ (void)setDefaultEngine:(id)arg1;
- (void)lsq_cancelCurrentImageLoad;
- (id)lsq_imageURL;
- (void)lsq_loadRemoteImageWithURL:(id)arg1 options:(unsigned long long)arg2 progress:(CDUnknownBlockType)arg3 completed:(CDUnknownBlockType)arg4;
- (void)lsq_setImageWithURL:(id)arg1 placeholderImage:(id)arg2 options:(unsigned long long)arg3 progress:(CDUnknownBlockType)arg4 completed:(CDUnknownBlockType)arg5;
- (void)lsq_setImageWithURL:(id)arg1 placeholderImage:(id)arg2 options:(unsigned long long)arg3 completed:(CDUnknownBlockType)arg4;
- (void)lsq_setImageWithURL:(id)arg1 placeholderImage:(id)arg2 completed:(CDUnknownBlockType)arg3;
- (void)lsq_setImageWithURL:(id)arg1 completed:(CDUnknownBlockType)arg2;
- (void)lsq_setImageWithURL:(id)arg1 placeholderImage:(id)arg2 options:(unsigned long long)arg3;
- (void)lsq_setImageWithURL:(id)arg1 placeholderImage:(id)arg2;
- (void)lsq_setImageWithURL:(id)arg1;
- (void)setLsqImageFetchOperation:(id)arg1;
- (id)lsqImageFetchOperation;
@end

