//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScreen.h>

@interface UIScreen (TuSDKTSScreenExtend)
+ (_Bool)hasRetinaDisplay;
+ (double)navgationBarHeight;
+ (double)topIfNavgationBarLayout;
+ (double)topIfStatusNavgationBarLayout;
+ (double)topIfStatusBarLayout;
+ (double)excludeStatusBarAutoHeight;
+ (double)excludeStatusBarHeight;
+ (double)midViewAutoHeight;
+ (double)midViewHeight;
+ (double)minViewAutoHeight;
+ (double)minViewHeight;
+ (double)minScreenRatio;
+ (double)height;
+ (double)width;
+ (struct CGSize)sizePixies;
+ (double)scale;
+ (struct CGSize)size;
@end

